Basic Tensor Algebra Subprograms (BTAS): Quantum Class Reference
Quantum Class Reference
Default quantum number class.
#include <Quantum.h>
Public Member Functions
Quantum ()
Default constructor.
Quantum (int q_val)
Initializer.
bool operator== (const Quantum &other) const
Equal to.
bool operator!= (const Quantum &other) const
Not equal to.
bool operator< (const Quantum &other) const
Less than.
bool operator> (const Quantum &other) const
Greater than.
Quantum operator* (const Quantum &other) const
Product of two quantum number.
bool parity () const
Parity, i.e. return -1 if fermion and odd particle number.
double clebsch () const
Clebsch-Gordan coefficient for non-Abelian symmetry.
Quantum operator+ () const
Unary plus.
Quantum operator- () const
Unary minus to return conjugated quantum number.
Static Public Member Functions
static const Quantum zero ()
Global function to return zero quantum number.
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Boost serialization.
Private Attributes
int m_q_val
Quantum number.
Friends
class boost::serialization::access
std::ostream & operator<< (std::ostream &ost, const Quantum &q)
Printing function.
Detailed Description
Default quantum number class.
Minimum design of quantum number class provided in BTAS (designed as a spin quantum number).
Quantum number class requires,
Boost serialization function
Global function which returns zero quantum number
Default constructor
Comparison operators, ==, !=, <, and >
Multiplication operator * to take product of two quantum number
Function which returns parity (true for scaling by -1)
Function which returns Clebsch-Gordan coefficient
Unary plus and minus operators for conjugation
Stream printing operator<<
If defined _DEFAULT_QUANTUM, this is included as a default quantum number class.
Definition at line 30 of file Quantum.h.
Constructor & Destructor Documentation
Quantum::Quantum () inline
Default constructor.
Definition at line 40 of file Quantum.h.
Referenced by operator*(), operator+(), operator-(), and zero().
Quantum::Quantum (int q_val) inline
Initializer.
Definition at line 42 of file Quantum.h.
Member Function Documentation
double Quantum::clebsch () const inline
Clebsch-Gordan coefficient for non-Abelian symmetry.
Definition at line 56 of file Quantum.h.
bool Quantum::operator!= (const Quantum & other) const inline
Not equal to.
Definition at line 46 of file Quantum.h.
References m_q_val.
Quantum Quantum::operator* (const Quantum & other) const inline
Product of two quantum number.
Definition at line 52 of file Quantum.h.
References m_q_val, and Quantum().
Quantum Quantum::operator+ () const inline
Unary plus.
Definition at line 58 of file Quantum.h.
References m_q_val, and Quantum().
Quantum Quantum::operator- () const inline
Unary minus to return conjugated quantum number.
Definition at line 60 of file Quantum.h.
References m_q_val, and Quantum().
bool Quantum::operator< (const Quantum & other) const inline
Less than.
Definition at line 48 of file Quantum.h.
References m_q_val.
bool Quantum::operator== (const Quantum & other) const inline
Equal to.
Definition at line 44 of file Quantum.h.
References m_q_val.
bool Quantum::operator> (const Quantum & other) const inline
Greater than.
Definition at line 50 of file Quantum.h.
References m_q_val.
bool Quantum::parity () const inline
Parity, i.e. return -1 if fermion and odd particle number.
Definition at line 54 of file Quantum.h.
template<class Archive > void Quantum::serialize (Archive & ar, const unsigned int version) inline private
Boost serialization.
Definition at line 35 of file Quantum.h.
References m_q_val.
static const Quantum Quantum::zero () inline static
Global function to return zero quantum number.
Definition at line 38 of file Quantum.h.
References Quantum().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Definition at line 32 of file Quantum.h.
std::ostream& operator<< (std::ostream & ost, const Quantum & q) friend
Printing function.
Definition at line 62 of file Quantum.h.
Field Documentation
int Quantum::m_q_val private
Quantum number.
Definition at line 68 of file Quantum.h.
Referenced by operator!=(), operator*(), operator+(), operator-(), operator<(), operator==(), operator>(), and serialize().
The documentation for this class was generated from the following file:
include/btas/QSPARSE/Quantum.h