Basic Tensor Algebra Subprograms (BTAS): btas::R_arglist_double< T, N1, N2 > Class Template Reference
btas::R_arglist_double< T, N1, N2 > Class Template Reference
Replication argment list for double argments function.
#include <Targlist.h>
Public Member Functions
R_arglist_double ()
Default constructor.
virtual ~R_arglist_double ()
Destructor.
R_arglist_double (const shared_ptr< TArray< T, N1 >> &arg1_ptr, const shared_ptr< TArray< T, N2 >> &arg2_ptr)
Initializer.
void reset (const shared_ptr< TArray< T, N1 >> &arg1_ptr, const shared_ptr< TArray< T, N2 >> &arg2_ptr)
Reset argment list.
Public Member Functions inherited from btas::T_arglist_base
T_arglist_base (size_t flops=0)
Default constructor.
virtual ~T_arglist_base ()
Destructor.
bool operator== (const T_arglist_base &other) const
Boolian operator== for compare FLOPS count.
bool operator!= (const T_arglist_base &other) const
Boolian operator!= for compare FLOPS count.
bool operator< (const T_arglist_base &other) const
Boolian operator< for sorting FLOPS count.
bool operator> (const T_arglist_base &other) const
Boolian operator> for sorting FLOPS count.
Protected Member Functions
virtual size_t mf_flops_count ()
Function to compute FLOPS count.
Protected Attributes
shared_ptr< TArray< T, N1 > > m_argment_1
shared_ptr< TArray< T, N2 > > m_argment_2
Protected Attributes inherited from btas::T_arglist_base
size_t m_flops
FLOPS count (aprox.) for load-balancing.
Detailed Description
template<typename T, size_t N1, size_t N2>
class btas::R_arglist_double< T, N1, N2 >
Replication argment list for double argments function.
e.g. BLAS COPY, AXPY
Definition at line 81 of file Targlist.h.
Constructor & Destructor Documentation
template<typename T, size_t N1, size_t N2> btas::R_arglist_double< T, N1, N2 >::R_arglist_double () inline
Default constructor.
Definition at line 89 of file Targlist.h.
template<typename T, size_t N1, size_t N2> virtual btas::R_arglist_double< T, N1, N2 >::~R_arglist_double () inline virtual
Destructor.
Definition at line 91 of file Targlist.h.
template<typename T, size_t N1, size_t N2> btas::R_arglist_double< T, N1, N2 >::R_arglist_double (const shared_ptr< TArray< T, N1 >> & arg1_ptr, const shared_ptr< TArray< T, N2 >> & arg2_ptr) inline
Initializer.
Definition at line 94 of file Targlist.h.
Member Function Documentation
template<typename T, size_t N1, size_t N2> virtual size_t btas::R_arglist_double< T, N1, N2 >::mf_flops_count () inline protected virtual
Function to compute FLOPS count.
Definition at line 86 of file Targlist.h.
Referenced by btas::R_arglist_double< double, N, N >::R_arglist_double(), and btas::R_arglist_double< double, N, N >::reset().
template<typename T, size_t N1, size_t N2> void btas::R_arglist_double< T, N1, N2 >::reset (const shared_ptr< TArray< T, N1 >> & arg1_ptr, const shared_ptr< TArray< T, N2 >> & arg2_ptr) inline
Reset argment list.
Definition at line 102 of file Targlist.h.
Referenced by btas::DaxpyArglist< N >::reset(), and btas::DpermuteArglist< N >::reset().
Field Documentation
template<typename T, size_t N1, size_t N2> shared_ptr<TArray<T, N1> > btas::R_arglist_double< T, N1, N2 >::m_argment_1 protected
Definition at line 83 of file Targlist.h.
Referenced by btas::R_arglist_double< double, N, N >::mf_flops_count(), btas::R_arglist_double< double, N, N >::R_arglist_double(), and btas::R_arglist_double< double, N, N >::reset().
template<typename T, size_t N1, size_t N2> shared_ptr<TArray<T, N2> > btas::R_arglist_double< T, N1, N2 >::m_argment_2 protected
Definition at line 84 of file Targlist.h.
Referenced by btas::R_arglist_double< double, N, N >::R_arglist_double(), and btas::R_arglist_double< double, N, N >::reset().
The documentation for this class was generated from the following file:
include/btas/Targlist.h