Basic Tensor Algebra Subprograms (BTAS): btas::R_arglist_triple< T, N1, N2, N3 > Class Template Reference
btas::R_arglist_triple< T, N1, N2, N3 > Class Template Reference
Replication argment list for triple argments function.
#include <Targlist.h>
Public Member Functions
R_arglist_triple ()
Default constructor.
virtual ~R_arglist_triple ()
Destructor.
R_arglist_triple (const shared_ptr< TArray< T, N1 >> &arg1_ptr, const shared_ptr< TArray< T, N2 >> &arg2_ptr, const shared_ptr< TArray< T, N3 >> &arg3_ptr)
Initializer.
void reset (const shared_ptr< TArray< T, N1 >> &arg1_ptr, const shared_ptr< TArray< T, N2 >> &arg2_ptr, const shared_ptr< TArray< T, N3 >> &arg3_ptr)
Reset argment list.
Public Member Functions inherited from btas::T_arglist_base
T_arglist_base (size_t flops=0)
Default constructor.
virtual ~T_arglist_base ()
Destructor.
bool operator== (const T_arglist_base &other) const
Boolian operator== for compare FLOPS count.
bool operator!= (const T_arglist_base &other) const
Boolian operator!= for compare FLOPS count.
bool operator< (const T_arglist_base &other) const
Boolian operator< for sorting FLOPS count.
bool operator> (const T_arglist_base &other) const
Boolian operator> for sorting FLOPS count.
Protected Member Functions
virtual size_t mf_flops_count ()
Function to compute FLOPS count.
Protected Attributes
shared_ptr< TArray< T, N1 > > m_argment_1
shared_ptr< TArray< T, N2 > > m_argment_2
shared_ptr< TArray< T, N3 > > m_argment_3
Protected Attributes inherited from btas::T_arglist_base
size_t m_flops
FLOPS count (aprox.) for load-balancing.
Detailed Description
template<typename T, size_t N1, size_t N2, size_t N3>
class btas::R_arglist_triple< T, N1, N2, N3 >
Replication argment list for triple argments function.
e.g. LAPACK SYEV, HEEV etc.
Definition at line 113 of file Targlist.h.
Constructor & Destructor Documentation
template<typename T , size_t N1, size_t N2, size_t N3> btas::R_arglist_triple< T, N1, N2, N3 >::R_arglist_triple () inline
Default constructor.
Definition at line 122 of file Targlist.h.
template<typename T , size_t N1, size_t N2, size_t N3> virtual btas::R_arglist_triple< T, N1, N2, N3 >::~R_arglist_triple () inline virtual
Destructor.
Definition at line 124 of file Targlist.h.
template<typename T , size_t N1, size_t N2, size_t N3> btas::R_arglist_triple< T, N1, N2, N3 >::R_arglist_triple (const shared_ptr< TArray< T, N1 >> & arg1_ptr, const shared_ptr< TArray< T, N2 >> & arg2_ptr, const shared_ptr< TArray< T, N3 >> & arg3_ptr) inline
Initializer.
Definition at line 127 of file Targlist.h.
References btas::R_arglist_triple< T, N1, N2, N3 >::m_argment_1, btas::R_arglist_triple< T, N1, N2, N3 >::m_argment_2, btas::R_arglist_triple< T, N1, N2, N3 >::m_argment_3, btas::T_arglist_base::m_flops, and btas::R_arglist_triple< T, N1, N2, N3 >::mf_flops_count().
Member Function Documentation
template<typename T , size_t N1, size_t N2, size_t N3> virtual size_t btas::R_arglist_triple< T, N1, N2, N3 >::mf_flops_count () inline protected virtual
Function to compute FLOPS count.
Definition at line 119 of file Targlist.h.
References btas::R_arglist_triple< T, N1, N2, N3 >::m_argment_1.
Referenced by btas::R_arglist_triple< T, N1, N2, N3 >::R_arglist_triple(), and btas::R_arglist_triple< T, N1, N2, N3 >::reset().
template<typename T , size_t N1, size_t N2, size_t N3> void btas::R_arglist_triple< T, N1, N2, N3 >::reset (const shared_ptr< TArray< T, N1 >> & arg1_ptr, const shared_ptr< TArray< T, N2 >> & arg2_ptr, const shared_ptr< TArray< T, N3 >> & arg3_ptr) inline
Reset argment list.
Definition at line 137 of file Targlist.h.
References btas::R_arglist_triple< T, N1, N2, N3 >::m_argment_1, btas::R_arglist_triple< T, N1, N2, N3 >::m_argment_2, btas::R_arglist_triple< T, N1, N2, N3 >::m_argment_3, btas::T_arglist_base::m_flops, and btas::R_arglist_triple< T, N1, N2, N3 >::mf_flops_count().
Field Documentation
template<typename T , size_t N1, size_t N2, size_t N3> shared_ptr<TArray<T, N1> > btas::R_arglist_triple< T, N1, N2, N3 >::m_argment_1 protected
Definition at line 115 of file Targlist.h.
Referenced by btas::R_arglist_triple< T, N1, N2, N3 >::mf_flops_count(), btas::R_arglist_triple< T, N1, N2, N3 >::R_arglist_triple(), and btas::R_arglist_triple< T, N1, N2, N3 >::reset().
template<typename T , size_t N1, size_t N2, size_t N3> shared_ptr<TArray<T, N2> > btas::R_arglist_triple< T, N1, N2, N3 >::m_argment_2 protected
Definition at line 116 of file Targlist.h.
Referenced by btas::R_arglist_triple< T, N1, N2, N3 >::R_arglist_triple(), and btas::R_arglist_triple< T, N1, N2, N3 >::reset().
template<typename T , size_t N1, size_t N2, size_t N3> shared_ptr<TArray<T, N3> > btas::R_arglist_triple< T, N1, N2, N3 >::m_argment_3 protected
Definition at line 117 of file Targlist.h.
Referenced by btas::R_arglist_triple< T, N1, N2, N3 >::R_arglist_triple(), and btas::R_arglist_triple< T, N1, N2, N3 >::reset().
The documentation for this class was generated from the following file:
include/btas/Targlist.h