Basic Tensor Algebra Subprograms (BTAS): btas::QSTmergeInfo< N, Q > Class Template Reference
btas::QSTmergeInfo< N, Q > Class Template Reference
Merged index infomation by quantum number-based sparse array.
#include <QSTmergeInfo.h>
Public Types
typedef std::multimap< int,
int >::const_iterator const_iterator
typedef std::pair
< const_iterator,
const_iterator > const_range
Public Member Functions
QSTmergeInfo ()
Default constructor.
QSTmergeInfo (const TVector< Qshapes< Q >, N > &qshape, const TVector< Dshapes, N > &dshape)
Initializer.
void reset (const TVector< Qshapes< Q >, N > &qshape, const TVector< Dshapes, N > &dshape)
Reset information.
const TVector< Dshapes, N > & dshape () const
const Dshapes & dshape (int i) const
const Dshapes & dshape_packed () const
const int & dshape_packed (int i) const
const Dshapes & dshape_merged () const
const int & dshape_merged (int i) const
const TVector< Qshapes< Q >, N > & qshape () const
const Qshapes< Q > & qshape (int i) const
const Qshapes< Q > & qshape_merged () const
const Q & qshape_merged (int i) const
const_iterator begin () const
const_iterator end () const
const_iterator find (int i) const
const_range equal_range (int i) const
Private Attributes
TVector< Dshapes, N > m_dshape
Original dense shapes.
Dshapes m_dshape_packed
Dense shapes for packed quantum numbers.
Dshapes m_dshape_merged
Dense shapes for merged quantum numbers.
TVector< Qshapes< Q >, N > m_qshape
Original quantum number indices.
Qshapes< Q > m_qshape_merged
Merged quantum number indices.
std::multimap< int, int > m_index_map
Map from merged index to packed indices.
Detailed Description
template<size_t N, class Q = Quantum>
class btas::QSTmergeInfo< N, Q >
Merged index infomation by quantum number-based sparse array.
Provides reversible conversion of merged quantum number indices.
First, quantum number indices are packed as a vector form. Packed quantum numbers is a set of naive product of quantum number indices. e.g. product of two indices {q1, q2} * {q1, q2} = {q1*q1, q1*q2, q2*q1, q2*q2}
Then, packed indices are merged by quantum number e.g. {q1*q1, q1*q2, q2*q1, q2*q2} -> {q11, q12, q22}
Multi-map m_index_map provides map from {q11, q12, q22} to {q1*q1, {q1*q2, q2*q1}, q2*q2}
Definition at line 26 of file QSTmergeInfo.h.
Member Typedef Documentation
template<size_t N, class Q = Quantum> typedef std::multimap<int, int>::const_iterator btas::QSTmergeInfo< N, Q >::const_iterator
Definition at line 28 of file QSTmergeInfo.h.
template<size_t N, class Q = Quantum> typedef std::pair<const_iterator, const_iterator> btas::QSTmergeInfo< N, Q >::const_range
Definition at line 29 of file QSTmergeInfo.h.
Constructor & Destructor Documentation
template<size_t N, class Q = Quantum> btas::QSTmergeInfo< N, Q >::QSTmergeInfo () inline
Default constructor.
Definition at line 33 of file QSTmergeInfo.h.
template<size_t N, class Q = Quantum> btas::QSTmergeInfo< N, Q >::QSTmergeInfo (const TVector< Qshapes< Q >, N > & qshape, const TVector< Dshapes, N > & dshape) inline
Initializer.
Definition at line 35 of file QSTmergeInfo.h.
References btas::QSTmergeInfo< N, Q >::qshape(), and btas::QSTmergeInfo< N, Q >::reset().
Member Function Documentation
template<size_t N, class Q = Quantum> const_iterator btas::QSTmergeInfo< N, Q >::begin () const inline
Definition at line 94 of file QSTmergeInfo.h.
References btas::QSTmergeInfo< N, Q >::m_index_map.
template<size_t N, class Q = Quantum> const TVector<Dshapes, N>& btas::QSTmergeInfo< N, Q >::dshape () const inline
Definition at line 79 of file QSTmergeInfo.h.
References btas::QSTmergeInfo< N, Q >::m_dshape.
Referenced by btas::QSTexpand(), and btas::QSTmergeInfo< N, Q >::reset().
template<size_t N, class Q = Quantum> const Dshapes& btas::QSTmergeInfo< N, Q >::dshape (int i) const inline
Definition at line 80 of file QSTmergeInfo.h.
References btas::QSTmergeInfo< N, Q >::m_dshape.
template<size_t N, class Q = Quantum> const Dshapes& btas::QSTmergeInfo< N, Q >::dshape_merged () const inline
Definition at line 85 of file QSTmergeInfo.h.
References btas::QSTmergeInfo< N, Q >::m_dshape_merged.
Referenced by btas::QSTmerge().
template<size_t N, class Q = Quantum> const int& btas::QSTmergeInfo< N, Q >::dshape_merged (int i) const inline
Definition at line 86 of file QSTmergeInfo.h.
References btas::QSTmergeInfo< N, Q >::m_dshape_merged.
template<size_t N, class Q = Quantum> const Dshapes& btas::QSTmergeInfo< N, Q >::dshape_packed () const inline
Definition at line 82 of file QSTmergeInfo.h.
References btas::QSTmergeInfo< N, Q >::m_dshape_packed.
Referenced by btas::QSTexpand(), and btas::QSTmerge().
template<size_t N, class Q = Quantum> const int& btas::QSTmergeInfo< N, Q >::dshape_packed (int i) const inline
Definition at line 83 of file QSTmergeInfo.h.
References btas::QSTmergeInfo< N, Q >::m_dshape_packed.
template<size_t N, class Q = Quantum> const_iterator btas::QSTmergeInfo< N, Q >::end () const inline
Definition at line 95 of file QSTmergeInfo.h.
References btas::QSTmergeInfo< N, Q >::m_index_map.
template<size_t N, class Q = Quantum> const_range btas::QSTmergeInfo< N, Q >::equal_range (int i) const inline
Definition at line 98 of file QSTmergeInfo.h.
References btas::QSTmergeInfo< N, Q >::m_index_map.
Referenced by btas::QSTexpand(), and btas::QSTmerge().
template<size_t N, class Q = Quantum> const_iterator btas::QSTmergeInfo< N, Q >::find (int i) const inline
Definition at line 96 of file QSTmergeInfo.h.
References btas::QSTmergeInfo< N, Q >::m_index_map.
template<size_t N, class Q = Quantum> const TVector<Qshapes<Q>, N>& btas::QSTmergeInfo< N, Q >::qshape () const inline
Definition at line 88 of file QSTmergeInfo.h.
References btas::QSTmergeInfo< N, Q >::m_qshape.
Referenced by btas::QSTexpand(), btas::QSTmergeInfo< N, Q >::QSTmergeInfo(), and btas::QSTmergeInfo< N, Q >::reset().
template<size_t N, class Q = Quantum> const Qshapes<Q>& btas::QSTmergeInfo< N, Q >::qshape (int i) const inline
Definition at line 89 of file QSTmergeInfo.h.
References btas::QSTmergeInfo< N, Q >::m_qshape.
template<size_t N, class Q = Quantum> const Qshapes<Q>& btas::QSTmergeInfo< N, Q >::qshape_merged () const inline
Definition at line 91 of file QSTmergeInfo.h.
References btas::QSTmergeInfo< N, Q >::m_qshape_merged.
Referenced by btas::QSDgesvd(), and btas::QSTmerge().
template<size_t N, class Q = Quantum> const Q& btas::QSTmergeInfo< N, Q >::qshape_merged (int i) const inline
Definition at line 92 of file QSTmergeInfo.h.
References btas::QSTmergeInfo< N, Q >::m_qshape_merged.
template<size_t N, class Q = Quantum> void btas::QSTmergeInfo< N, Q >::reset (const TVector< Qshapes< Q >, N > & qshape, const TVector< Dshapes, N > & dshape) inline
Reset information.
Definition at line 38 of file QSTmergeInfo.h.
References BTAS_THROW, btas::QSTmergeInfo< N, Q >::dshape(), btas::QSTmergeInfo< N, Q >::m_dshape, btas::QSTmergeInfo< N, Q >::m_dshape_merged, btas::QSTmergeInfo< N, Q >::m_dshape_packed, btas::QSTmergeInfo< N, Q >::m_index_map, btas::QSTmergeInfo< N, Q >::m_qshape, btas::QSTmergeInfo< N, Q >::m_qshape_merged, and btas::QSTmergeInfo< N, Q >::qshape().
Referenced by mps::add(), mps::gemm(), mps::gemv(), and btas::QSTmergeInfo< N, Q >::QSTmergeInfo().
Field Documentation
template<size_t N, class Q = Quantum> TVector<Dshapes, N> btas::QSTmergeInfo< N, Q >::m_dshape private
Original dense shapes.
Definition at line 103 of file QSTmergeInfo.h.
Referenced by btas::QSTmergeInfo< N, Q >::dshape(), and btas::QSTmergeInfo< N, Q >::reset().
template<size_t N, class Q = Quantum> Dshapes btas::QSTmergeInfo< N, Q >::m_dshape_merged private
Dense shapes for merged quantum numbers.
Definition at line 109 of file QSTmergeInfo.h.
Referenced by btas::QSTmergeInfo< N, Q >::dshape_merged(), and btas::QSTmergeInfo< N, Q >::reset().
template<size_t N, class Q = Quantum> Dshapes btas::QSTmergeInfo< N, Q >::m_dshape_packed private
Dense shapes for packed quantum numbers.
Definition at line 106 of file QSTmergeInfo.h.
Referenced by btas::QSTmergeInfo< N, Q >::dshape_packed(), and btas::QSTmergeInfo< N, Q >::reset().
template<size_t N, class Q = Quantum> std::multimap<int, int> btas::QSTmergeInfo< N, Q >::m_index_map private
Map from merged index to packed indices.
Definition at line 120 of file QSTmergeInfo.h.
Referenced by btas::QSTmergeInfo< N, Q >::begin(), btas::QSTmergeInfo< N, Q >::end(), btas::QSTmergeInfo< N, Q >::equal_range(), btas::QSTmergeInfo< N, Q >::find(), and btas::QSTmergeInfo< N, Q >::reset().
template<size_t N, class Q = Quantum> TVector<Qshapes<Q>, N> btas::QSTmergeInfo< N, Q >::m_qshape private
Original quantum number indices.
Definition at line 113 of file QSTmergeInfo.h.
Referenced by btas::QSTmergeInfo< N, Q >::qshape(), and btas::QSTmergeInfo< N, Q >::reset().
template<size_t N, class Q = Quantum> Qshapes<Q> btas::QSTmergeInfo< N, Q >::m_qshape_merged private
Merged quantum number indices.
Definition at line 116 of file QSTmergeInfo.h.
Referenced by btas::QSTmergeInfo< N, Q >::qshape_merged(), and btas::QSTmergeInfo< N, Q >::reset().
The documentation for this class was generated from the following file:
include/btas/QSPARSE/QSTmergeInfo.h