Basic Tensor Algebra Subprograms (BTAS): btas::R_arglist_single< T, N1 > Class Template Reference
btas::R_arglist_single< T, N1 > Class Template Reference
Replication argment list for single argment function.
#include <Targlist.h>
Public Member Functions
R_arglist_single ()
Default constructor.
virtual ~R_arglist_single ()
Destructor.
R_arglist_single (const shared_ptr< TArray< T, N1 >> &arg1_ptr)
Initializer.
void reset (const shared_ptr< TArray< T, N1 >> &arg1_ptr)
Reset argment list.
Public Member Functions inherited from btas::T_arglist_base
T_arglist_base (size_t flops=0)
Default constructor.
virtual ~T_arglist_base ()
Destructor.
bool operator== (const T_arglist_base &other) const
Boolian operator== for compare FLOPS count.
bool operator!= (const T_arglist_base &other) const
Boolian operator!= for compare FLOPS count.
bool operator< (const T_arglist_base &other) const
Boolian operator< for sorting FLOPS count.
bool operator> (const T_arglist_base &other) const
Boolian operator> for sorting FLOPS count.
Protected Member Functions
virtual size_t mf_flops_count ()
Function to compute FLOPS count.
Protected Attributes
shared_ptr< TArray< T, N1 > > m_argment_1
Protected Attributes inherited from btas::T_arglist_base
size_t m_flops
FLOPS count (aprox.) for load-balancing.
Detailed Description
template<typename T, size_t N1>
class btas::R_arglist_single< T, N1 >
Replication argment list for single argment function.
e.g. BLAS SCAL
Definition at line 54 of file Targlist.h.
Constructor & Destructor Documentation
template<typename T, size_t N1> btas::R_arglist_single< T, N1 >::R_arglist_single () inline
Default constructor.
Definition at line 61 of file Targlist.h.
template<typename T, size_t N1> virtual btas::R_arglist_single< T, N1 >::~R_arglist_single () inline virtual
Destructor.
Definition at line 63 of file Targlist.h.
template<typename T, size_t N1> btas::R_arglist_single< T, N1 >::R_arglist_single (const shared_ptr< TArray< T, N1 >> & arg1_ptr) inline
Initializer.
Definition at line 66 of file Targlist.h.
Member Function Documentation
template<typename T, size_t N1> virtual size_t btas::R_arglist_single< T, N1 >::mf_flops_count () inline protected virtual
Function to compute FLOPS count.
Definition at line 58 of file Targlist.h.
Referenced by btas::R_arglist_single< double, N >::R_arglist_single(), and btas::R_arglist_single< double, N >::reset().
template<typename T, size_t N1> void btas::R_arglist_single< T, N1 >::reset (const shared_ptr< TArray< T, N1 >> & arg1_ptr) inline
Reset argment list.
Definition at line 72 of file Targlist.h.
Referenced by btas::DscalArglist< N >::reset().
Field Documentation
template<typename T, size_t N1> shared_ptr<TArray<T, N1> > btas::R_arglist_single< T, N1 >::m_argment_1 protected
Definition at line 56 of file Targlist.h.
Referenced by btas::R_arglist_single< double, N >::mf_flops_count(), btas::R_arglist_single< double, N >::R_arglist_single(), and btas::R_arglist_single< double, N >::reset().
The documentation for this class was generated from the following file:
include/btas/Targlist.h