Basic Tensor Algebra Subprograms (BTAS): include/lapack/clapack.h File Reference
clapack.h File Reference
C/C++ interface to lapack calls like clapack_xxx.
Data Structures
struct FC_COMPLEX_08
struct FC_COMPLEX_16
Enumerations
enum CLAPACK_TRANSPOSE { ClapackNoTrans = 111, ClapackTrans = 112, ClapackConjTrans = 113 }
Transposition type used in CLAPACK.
enum CLAPACK_UPLO { ClapackUpper = 121, ClapackLower = 122 }
Consider upper or lower triangular elements in symmetric matrix.
enum CLAPACK_CALCVECTOR { ClapackNoCalcVector = 201, ClapackCalcVector = 202, ClapackCalcThinVector = 203 }
Calculate eigenvectors.
Functions
int clapack_dgetrf (int m, int n, double *a, int lda, int *ipiv)
LU decomposition.
int clapack_dpotrf (CLAPACK_UPLO Uplo, int n, double *a, int lda, int *ipiv)
Cholesky decomposition.
int clapack_dsytrf (CLAPACK_UPLO Uplo, int n, double *a, int lda, int *ipiv)
Bunch-Kaufman decomposition.
int clapack_dgetrs (CLAPACK_TRANSPOSE TransA, int n, int nrhs, double *a, int lda, int *ipiv, double *b, int ldb)
Solving linear equation from triangular fragmented matrix.
int clapack_dpotrs (CLAPACK_UPLO Uplo, int n, int nrhs, double *a, int lda, double *b, int ldb)
Solving linear equation from triangular fragmented matrix (symmetric positive definite)
int clapack_dsytrs (CLAPACK_UPLO Uplo, int n, int nrhs, double *a, int lda, int *ipiv, double *b, int ldb)
Solving linear equation from triangular fragmented matrix (symmetric)
int clapack_dgesv (int n, int nrhs, double *a, int lda, int *ipiv, double *b, int ldb)
Solving linear equation (involving dgetrf)
int clapack_dposv (CLAPACK_UPLO Uplo, int n, int nrhs, double *a, int lda, double *b, int ldb)
Solving linear equation (symmetric positive definite)
int clapack_dsysv (CLAPACK_UPLO Uplo, int n, int nrhs, double *a, int lda, int *ipiv, double *b, int ldb)
Solving linear equation (symmetric)
int clapack_dsyev (CLAPACK_CALCVECTOR Jobz, CLAPACK_UPLO Uplo, int n, double *a, int lda, double *w)
eigenvalue decomposition for real-symmetric matrix
int clapack_dgeev (CLAPACK_CALCVECTOR Jobl, CLAPACK_CALCVECTOR Jobr, int n, double *a, int lda, double *wr, double *wi, double *vl, int ldvl, double *vr, int ldvr)
eigenvalue decomposition for non-hermitian matrix
int clapack_dsygv (int itype, CLAPACK_CALCVECTOR Jobz, CLAPACK_UPLO Uplo, int n, double *a, int lda, double *b, int ldb, double *w)
generalized eigenvalue decomposition for real-symmetric matrix
int clapack_dggev (CLAPACK_CALCVECTOR Jobl, CLAPACK_CALCVECTOR Jobr, int n, double *a, int lda, double *b, int ldb, double *alphar, double *alphai, double *beta, double *vl, int ldvl, double *vr, int ldvr)
generalized eigenvalue decomposition for non-hermitian matrix pair
int clapack_dgesvd (CLAPACK_CALCVECTOR Jobu, CLAPACK_CALCVECTOR Jobvt, int m, int n, double *a, int lda, double *s, double *u, int ldu, double *vt, int ldvt)
singularvalue decomposition for real general matrix
int clapack_zheev (CLAPACK_CALCVECTOR Jobz, CLAPACK_UPLO Uplo, int n, void *a, int lda, double *w)
eigenvalue decomposition for complex-hermitian matrix
int clapack_zgesvd (CLAPACK_CALCVECTOR Jobu, CLAPACK_CALCVECTOR Jobvt, int m, int n, void *a, int lda, double *s, void *u, int ldu, void *vt, int ldvt)
singularvalue decomposition for complex general matrix
Detailed Description
C/C++ interface to lapack calls like clapack_xxx.
Definition in file clapack.h.
Enumeration Type Documentation
enum CLAPACK_CALCVECTOR
Calculate eigenvectors.
Enumerator
ClapackNoCalcVector
ClapackCalcVector
ClapackCalcThinVector
Definition at line 46 of file clapack.h.
enum CLAPACK_TRANSPOSE
Transposition type used in CLAPACK.
This is a part of BTAS library to provide C/C++ interface of LAPACK calls. Note that all functions work with Column-Major array with respect to FORTRAN-style, since C-style Row-Major array is not supported in LAPACK library.
Wrapper functions for Row-Major array are provided in BTAS dense array layer.
Enumerator
ClapackNoTrans
ClapackTrans
ClapackConjTrans
Definition at line 42 of file clapack.h.
enum CLAPACK_UPLO
Consider upper or lower triangular elements in symmetric matrix.
Enumerator
ClapackUpper
ClapackLower
Definition at line 44 of file clapack.h.
Function Documentation
int clapack_dgeev (CLAPACK_CALCVECTOR Jobl, CLAPACK_CALCVECTOR Jobr, int n, double * a, int lda, double * wr, double * wi, double * vl, int ldvl, double * vr, int ldvr)
eigenvalue decomposition for non-hermitian matrix
Definition at line 119 of file clapack.C.
References ClapackNoCalcVector, and dgeev_().
Referenced by btas::Dgeev().
int clapack_dgesv (int n, int nrhs, double * a, int lda, int * ipiv, double * b, int ldb)
Solving linear equation (involving dgetrf)
Definition at line 75 of file clapack.C.
References clapack_dgetrf(), clapack_dgetrs(), and ClapackNoTrans.
Referenced by btas::Dgesv().
int clapack_dgesvd (CLAPACK_CALCVECTOR Jobu, CLAPACK_CALCVECTOR Jobvt, int m, int n, double * a, int lda, double * s, double * u, int ldu, double * vt, int ldvt)
singularvalue decomposition for real general matrix
Definition at line 181 of file clapack.C.
References ClapackCalcThinVector, ClapackCalcVector, ClapackNoCalcVector, and dgesvd_().
Referenced by btas::Dgesvd().
int clapack_dgetrf (int m, int n, double * a, int lda, int * ipiv)
LU decomposition.
Definition at line 19 of file clapack.C.
References dgetrf_().
Referenced by clapack_dgesv(), and btas::Dgetrf().
int clapack_dgetrs (CLAPACK_TRANSPOSE TransA, int n, int nrhs, double * a, int lda, int * ipiv, double * b, int ldb)
Solving linear equation from triangular fragmented matrix.
Definition at line 50 of file clapack.C.
References ClapackNoTrans, and dgetrs_().
Referenced by clapack_dgesv().
int clapack_dggev (CLAPACK_CALCVECTOR Jobl, CLAPACK_CALCVECTOR Jobr, int n, double * a, int lda, double * b, int ldb, double * alphar, double * alphai, double * beta, double * vl, int ldvl, double * vr, int ldvr)
generalized eigenvalue decomposition for non-hermitian matrix pair
Definition at line 161 of file clapack.C.
References ClapackNoCalcVector, and dggev_().
Referenced by btas::Dggev().
int clapack_dposv (CLAPACK_UPLO Uplo, int n, int nrhs, double * a, int lda, double * b, int ldb)
Solving linear equation (symmetric positive definite)
Definition at line 83 of file clapack.C.
References clapack_dpotrf(), and clapack_dpotrs().
int clapack_dpotrf (CLAPACK_UPLO Uplo, int n, double * a, int lda, int * ipiv)
Cholesky decomposition.
Referenced by clapack_dposv().
int clapack_dpotrs (CLAPACK_UPLO Uplo, int n, int nrhs, double * a, int lda, double * b, int ldb)
Solving linear equation from triangular fragmented matrix (symmetric positive definite)
Definition at line 58 of file clapack.C.
References ClapackUpper, and dpotrs_().
Referenced by clapack_dposv().
int clapack_dsyev (CLAPACK_CALCVECTOR Jobz, CLAPACK_UPLO Uplo, int n, double * a, int lda, double * w)
eigenvalue decomposition for real-symmetric matrix
Definition at line 100 of file clapack.C.
References ClapackNoCalcVector, ClapackUpper, and dsyev_().
Referenced by btas::Dsyev().
int clapack_dsygv (int itype, CLAPACK_CALCVECTOR Jobz, CLAPACK_UPLO Uplo, int n, double * a, int lda, double * b, int ldb, double * w)
generalized eigenvalue decomposition for real-symmetric matrix
generalized eigenvalue decomposition for real-symmetric matrix
itype = 1: A x = w B x 2: A B x = w x 3: B A x = w x
Definition at line 142 of file clapack.C.
References ClapackNoCalcVector, ClapackUpper, and dsygv_().
Referenced by btas::Dsygv().
int clapack_dsysv (CLAPACK_UPLO Uplo, int n, int nrhs, double * a, int lda, int * ipiv, double * b, int ldb)
Solving linear equation (symmetric)
Definition at line 91 of file clapack.C.
References clapack_dsytrf(), and clapack_dsytrs().
int clapack_dsytrf (CLAPACK_UPLO Uplo, int n, double * a, int lda, int * ipiv)
Bunch-Kaufman decomposition.
Definition at line 34 of file clapack.C.
References ClapackUpper, and dsytrf_().
Referenced by clapack_dsysv().
int clapack_dsytrs (CLAPACK_UPLO Uplo, int n, int nrhs, double * a, int lda, int * ipiv, double * b, int ldb)
Solving linear equation from triangular fragmented matrix (symmetric)
Definition at line 66 of file clapack.C.
References ClapackUpper, and dsytrs_().
Referenced by clapack_dsysv().
int clapack_zgesvd (CLAPACK_CALCVECTOR Jobu, CLAPACK_CALCVECTOR Jobvt, int m, int n, void * a, int lda, double * s, void * u, int ldu, void * vt, int ldvt)
singularvalue decomposition for complex general matrix
Definition at line 228 of file clapack.C.
References ClapackCalcThinVector, ClapackCalcVector, ClapackNoCalcVector, and zgesvd_().
int clapack_zheev (CLAPACK_CALCVECTOR Jobz, CLAPACK_UPLO Uplo, int n, void * a, int lda, double * w)
eigenvalue decomposition for complex-hermitian matrix
Definition at line 207 of file clapack.C.
References ClapackNoCalcVector, ClapackUpper, and zheev_().