Basic Tensor Algebra Subprograms (BTAS): btas::C_arglist_triple< T, N1, N2, N3 > Class Template Reference
btas::C_arglist_triple< T, N1, N2, N3 > Class Template Reference
Argment list for contraction.
#include <Targlist.h>
Public Member Functions
C_arglist_triple ()
Default constructor.
virtual ~C_arglist_triple ()
Destructor.
C_arglist_triple (const shared_ptr< TArray< T, N3 >> &arg3_ptr)
Initializer.
void reset (const shared_ptr< TArray< T, N3 >> &arg3_ptr)
Reset argment 3.
virtual void clear ()
Clear argments.
void add (const shared_ptr< TArray< T, N1 >> &arg1_ptr, const shared_ptr< TArray< T, N2 >> &arg2_ptr)
Add argment list.
size_t size () const
Return number of argment list.
Public Member Functions inherited from btas::T_arglist_base
T_arglist_base (size_t flops=0)
Default constructor.
virtual ~T_arglist_base ()
Destructor.
bool operator== (const T_arglist_base &other) const
Boolian operator== for compare FLOPS count.
bool operator!= (const T_arglist_base &other) const
Boolian operator!= for compare FLOPS count.
bool operator< (const T_arglist_base &other) const
Boolian operator< for sorting FLOPS count.
bool operator> (const T_arglist_base &other) const
Boolian operator> for sorting FLOPS count.
Protected Member Functions
virtual size_t mf_flops_count (const shared_ptr< TArray< T, N1 >> &arg1_ptr, const shared_ptr< TArray< T, N2 >> &arg2_ptr)
Function to compute FLOPS count.
Protected Attributes
std::vector< shared_ptr
< TArray< T, N1 > > > m_argment_1
array list of a
std::vector< shared_ptr
< TArray< T, N2 > > > m_argment_2
array list of b
shared_ptr< TArray< T, N3 > > m_argment_3
Protected Attributes inherited from btas::T_arglist_base
size_t m_flops
FLOPS count (aprox.) for load-balancing.
Detailed Description
template<typename T, size_t N1, size_t N2, size_t N3>
class btas::C_arglist_triple< T, N1, N2, N3 >
Argment list for contraction.
i.e. BLAS (level 2, 3): GEMV, GER, GEMM, etc. m_arglist has pairs of array (a, b) and m_c_ptr has the pointer to array (c), for function call s.t. c = sum_{i} foo(a[i], b[i])
Definition at line 199 of file Targlist.h.
Constructor & Destructor Documentation
template<typename T, size_t N1, size_t N2, size_t N3> btas::C_arglist_triple< T, N1, N2, N3 >::C_arglist_triple () inline
Default constructor.
Definition at line 210 of file Targlist.h.
template<typename T, size_t N1, size_t N2, size_t N3> virtual btas::C_arglist_triple< T, N1, N2, N3 >::~C_arglist_triple () inline virtual
Destructor.
Definition at line 212 of file Targlist.h.
template<typename T, size_t N1, size_t N2, size_t N3> btas::C_arglist_triple< T, N1, N2, N3 >::C_arglist_triple (const shared_ptr< TArray< T, N3 >> & arg3_ptr) inline
Initializer.
Definition at line 215 of file Targlist.h.
Member Function Documentation
template<typename T, size_t N1, size_t N2, size_t N3> void btas::C_arglist_triple< T, N1, N2, N3 >::add (const shared_ptr< TArray< T, N1 >> & arg1_ptr, const shared_ptr< TArray< T, N2 >> & arg2_ptr) inline
Add argment list.
Definition at line 231 of file Targlist.h.
Referenced by btas::DgemvArglist< NA, NB, NC >::add(), btas::DgerArglist< NA, NB, NC >::add(), and btas::DgemmArglist< NA, NB, NC >::add().
template<typename T, size_t N1, size_t N2, size_t N3> virtual void btas::C_arglist_triple< T, N1, N2, N3 >::clear () inline virtual
Clear argments.
Reimplemented in btas::DgemmArglist< NA, NB, NC >, btas::DgerArglist< NA, NB, NC >, and btas::DgemvArglist< NA, NB, NC >.
Definition at line 223 of file Targlist.h.
Referenced by btas::DgemvArglist< NA, NB, NC >::clear(), btas::DgerArglist< NA, NB, NC >::clear(), and btas::DgemmArglist< NA, NB, NC >::clear().
template<typename T, size_t N1, size_t N2, size_t N3> virtual size_t btas::C_arglist_triple< T, N1, N2, N3 >::mf_flops_count (const shared_ptr< TArray< T, N1 >> & arg1_ptr, const shared_ptr< TArray< T, N2 >> & arg2_ptr) inline protected virtual
Function to compute FLOPS count.
Definition at line 206 of file Targlist.h.
Referenced by btas::C_arglist_triple< double, NA, NB, NC >::add().
template<typename T, size_t N1, size_t N2, size_t N3> void btas::C_arglist_triple< T, N1, N2, N3 >::reset (const shared_ptr< TArray< T, N3 >> & arg3_ptr) inline
Reset argment 3.
Definition at line 219 of file Targlist.h.
Referenced by btas::DgemvArglist< NA, NB, NC >::reset(), btas::DgerArglist< NA, NB, NC >::reset(), and btas::DgemmArglist< NA, NB, NC >::reset().
template<typename T, size_t N1, size_t N2, size_t N3> size_t btas::C_arglist_triple< T, N1, N2, N3 >::size () const inline
Return number of argment list.
Definition at line 238 of file Targlist.h.
Field Documentation
template<typename T, size_t N1, size_t N2, size_t N3> std::vector<shared_ptr<TArray<T, N1> > > btas::C_arglist_triple< T, N1, N2, N3 >::m_argment_1 protected
array list of a
Definition at line 201 of file Targlist.h.
Referenced by btas::C_arglist_triple< double, NA, NB, NC >::add(), btas::C_arglist_triple< double, NA, NB, NC >::clear(), and btas::C_arglist_triple< double, NA, NB, NC >::size().
template<typename T, size_t N1, size_t N2, size_t N3> std::vector<shared_ptr<TArray<T, N2> > > btas::C_arglist_triple< T, N1, N2, N3 >::m_argment_2 protected
array list of b
Definition at line 202 of file Targlist.h.
Referenced by btas::C_arglist_triple< double, NA, NB, NC >::add(), and btas::C_arglist_triple< double, NA, NB, NC >::clear().
template<typename T, size_t N1, size_t N2, size_t N3> shared_ptr<TArray<T, N3> > btas::C_arglist_triple< T, N1, N2, N3 >::m_argment_3 protected
array c
Definition at line 203 of file Targlist.h.
Referenced by btas::C_arglist_triple< double, NA, NB, NC >::clear(), btas::C_arglist_triple< double, NA, NB, NC >::mf_flops_count(), and btas::C_arglist_triple< double, NA, NB, NC >::reset().
The documentation for this class was generated from the following file:
include/btas/Targlist.h