Basic Tensor Algebra Subprograms (BTAS): mps Namespace Reference
mps Namespace Reference
Typedefs
template<size_t N, class Q >
using MPX = std::vector< QSDArray< N, Q > >
typedefine MPX as a std::vector< QSDArray<N> > for functions the same for both MPS and MPO
template<class Q >
using MPS = std::vector< QSDArray< 3, Q > >
typedefine MPS as an std::vector< QSDArray<3> >
template<class Q >
using MPO = std::vector< QSDArray< 4, Q > >
typedefine MPO as an std::vector< QSDArray<4> >
Enumerations
enum MPS_DIRECTION { Left, Right }
Functions
template<class Q >
void calc_qdim (int L, const Q &qt, const Qshapes< Q > &qp, std::vector< Qshapes< Q > > &qr, std::vector< Dshapes > &dr, int D)
template<class Q >
MPS< Q > create (int L, const Q &qt, const Qshapes< Q > &qp, int D, const function< double(void)> &f_random_generator)
template<class Q >
MPS< Q > create (int L, const Q &qt, const Qshapes< Q > &qp, int D, double value=0.0)
template<class Q >
MPS< Q > product_state (int L, const Qshapes< Q > &qp, const std::vector< int > &occ)
template<size_t N, class Q >
void scal (double alpha, MPX< N, Q > &mpx)
template<size_t N, class Q >
MPX< N, Q > add (const MPX< N, Q > &A, const MPX< N, Q > &B)
template<size_t N, class Q >
void compress (MPX< N, Q > &mpx, const MPS_DIRECTION &dir, int D)
template<size_t N, class Q >
void clean (MPX< N, Q > &mpx)
template<class Q >
double inprod (const MPS_DIRECTION &dir, const MPS< Q > &A, const MPO< Q > &O, const MPS< Q > &B)
template<class Q >
MPS< Q > gemv (const MPO< Q > &O, const MPS< Q > &A)
template<class Q >
MPO< Q > gemm (const MPO< Q > &O1, const MPO< Q > &O2)
template<class Q >
double dot (const MPS_DIRECTION &dir, const MPS< Q > &X, const MPS< Q > &Y)
template<class Q >
double nrm2 (const MPS< Q > &mps)
template<class Q >
double dist (const MPS< Q > &X, const MPS< Q > &Y)
template<class Q >
void normalize (MPS< Q > &mps)
template<class Q >
MPS< Q > exp (const MPO< Q > &O, const MPS< Q > &A, int cutoff)
template<size_t N, class Q >
void save (const MPX< N, Q > &mpx, const char *filename)
template<size_t N, class Q >
void load (MPX< N, Q > &mpx, const char *filename)
Typedef Documentation
template<class Q > using mps::MPO = typedef std::vector< QSDArray<4,Q> >
typedefine MPO as an std::vector< QSDArray<4> >
Definition at line 81 of file MPSblas.h.
template<class Q > using mps::MPS = typedef std::vector< QSDArray<3,Q> >
typedefine MPS as an std::vector< QSDArray<3> >
Definition at line 77 of file MPSblas.h.
template<size_t N, class Q > using mps::MPX = typedef std::vector< QSDArray<N,Q> >
typedefine MPX as a std::vector< QSDArray<N> > for functions the same for both MPS and MPO
Definition at line 73 of file MPSblas.h.
Enumeration Type Documentation
enum mps::MPS_DIRECTION
Enumerator
Left
Right
left to right
right to left
Definition at line 64 of file MPSblas.h.
Function Documentation
template<size_t N, class Q > MPX<N,Q> mps::add (const MPX< N, Q > & A, const MPX< N, Q > & B)
construct new MPX AB that is the sum of A + B: this is done by making a larger MPX object with larger bond dimension, taking the direct sum of the individual tensors in the chain
Parameters
A input MPX
B input MPX
Returns
the MPX result
Definition at line 481 of file MPSblas.h.
References BTAS_THROW, btas::QSTArray< T, N, Q >::clear(), btas::STArray< T, N >::dshape(), btas::QSDdsum(), btas::QSTArray< T, N, Q >::qshape(), btas::QSTmerge(), and btas::QSTmergeInfo< N, Q >::reset().
Referenced by exp().
template<class Q > void mps::calc_qdim (int L, const Q & qt, const Qshapes< Q > & qp, std::vector< Qshapes< Q > > & qr, std::vector< Dshapes > & dr, int D)
given the length, total quantumnumber and physical quantumnumbers, and some cutoff block dimension
Returns
the right-bond quantumnumbers and dimensions
Parameters
L length of the chain
qt total quantumnumber
qp array of physical quantumnumbers on the sites
qr std::vector of Qshapes length L, will contain the right bond quantumnumbers on exit, input will be destroyed
dr std::vector of Dshapes length L, will contain the right bond dimensions corresponding to the numbers on exit, input will be destroyed
D cutoff block dimension (max dimension of each quantumsector)
Definition at line 94 of file MPSblas.h.
Referenced by create().
template<size_t N, class Q > void mps::clean (MPX< N, Q > & mpx)
clean up the MPX, i.e. make sure the right quantumblocks are connected, remove unnecessary quantumnumbers and blocks
Parameters
mpx input MPX, will be changed 'cleaned' on exit
Definition at line 670 of file MPSblas.h.
template<size_t N, class Q > void mps::compress (MPX< N, Q > & mpx, const MPS_DIRECTION & dir, int D)
Compress an MP object by performing an SVD
Parameters
mpx is the input MPX, will be lost/overwritten by the compressed MPX
dir direction of the canonicalization, from left to right if Left, right to left if Right
D if > 0 this specifies the number of states to be kept if == 0 all the states are kept if < 0 all singular values > 10^-D are kept
Definition at line 574 of file MPSblas.h.
References btas::QSTArray< T, N, Q >::clear(), btas::Left, btas::QSDcontract(), btas::QSDcopy(), btas::QSDdotc(), btas::QSDgesvd(), btas::QSDscal(), btas::RightArrow, scal(), btas::SDdidm(), btas::SDdimd(), and btas::shape().
Referenced by exp().
template<class Q > MPS<Q> mps::create (int L, const Q & qt, const Qshapes< Q > & qp, int D, const function< double(void)> & f_random_generator)
create an MPS chain of length L initialized randomly on total Q number qt, with physical quantumnumber qp
Parameters
L length of the chain
qt total quantumnumber
qp Qshapes object containing the physical quantumnumbers
D maximal dimension of the quantum blocks
Returns
the MPS chain randomly filled and with correct quantumnumbers and dimensions
Definition at line 304 of file MPSblas.h.
References calc_qdim(), and btas::make_array().
template<class Q > MPS<Q> mps::create (int L, const Q & qt, const Qshapes< Q > & qp, int D, double value = 0.0)
create an MPS chain of length L initialized on a contant number on total Q number qt, with physical quantumnumber qp
Parameters
L length of the chain
qt total quantumnumber
qp Qshapes object containing the physical quantumnumbers
D maximal dimension of the quantum blocks
value the number the mps is initialized onto, standard 0
Returns
the MPS chain randomly filled and with correct quantumnumbers and dimensions
Definition at line 359 of file MPSblas.h.
References calc_qdim(), and btas::make_array().
template<class Q > double mps::dist (const MPS< Q > & X, const MPS< Q > & Y)
Returns
the distance between 2 mps's ||X - Y||_2
Definition at line 1116 of file MPSblas.h.
References btas::dot(), btas::Left, and nrm2().
template<class Q > double mps::dot (const MPS_DIRECTION & dir, const MPS< Q > & X, const MPS< Q > & Y)
the contraction of two MPS's
Returns
the overlap of two MPS objects
Parameters
X input MPS
Y input MPS
Definition at line 1028 of file MPSblas.h.
References btas::STArray< T, N >::begin(), btas::QSTArray< T, N, Q >::clear(), btas::STArray< T, N >::end(), btas::STArray< T, N >::find(), btas::Left, btas::QSDcontract(), btas::QSDindexed_contract(), and btas::shape().
template<class Q > MPS<Q> mps::exp (const MPO< Q > & O, const MPS< Q > & A, int cutoff)
Returns
the MPS that is the result of the expontential of the operator MPO O acting on input MPS A.
Parameters
cutoff number of terms in the expansion that will be kept.
Definition at line 1139 of file MPSblas.h.
References add(), compress(), gemv(), Left, Right, and scal().
template<class Q > MPO<Q> mps::gemm (const MPO< Q > & O1, const MPO< Q > & O2)
MPO equivalent of a matrix matrix multiplication. MPO action on MPO gives new MPO: O1-O2|MPS>
Parameters
O1 input MPO
O2 input MPO
Returns
the new MPO object created by the multiplication
Definition at line 963 of file MPSblas.h.
References BTAS_THROW, btas::QSTArray< T, N, Q >::clear(), btas::STArray< T, N >::dshape(), btas::QSDindexed_contract(), btas::QSTArray< T, N, Q >::qshape(), btas::QSTmerge(), btas::QSTmergeInfo< N, Q >::reset(), and btas::shape().
template<class Q > MPS<Q> mps::gemv (const MPO< Q > & O, const MPS< Q > & A)
MPO/S equivalent of a matrix vector multiplication. Let an MPO act on an MPS and return the new MPS
Parameters
O input MPO
A input MPS
Returns
the new MPS object created by the multiplication
Definition at line 897 of file MPSblas.h.
References BTAS_THROW, btas::QSTArray< T, N, Q >::clear(), btas::STArray< T, N >::dshape(), btas::QSDindexed_contract(), btas::QSTArray< T, N, Q >::qshape(), btas::QSTmerge(), btas::QSTmergeInfo< N, Q >::reset(), and btas::shape().
Referenced by exp().
template<class Q > double mps::inprod (const MPS_DIRECTION & dir, const MPS< Q > & A, const MPO< Q > & O, const MPS< Q > & B)
Parameters
dir go from left to right (Left) or right to left (Right) for contraction
A input MPS
O input MPO
B input MPS
Returns
the number containing < A | O | B >
Definition at line 768 of file MPSblas.h.
References btas::STArray< T, N >::begin(), BTAS_THROW, btas::QSTArray< T, N, Q >::clear(), btas::STArray< T, N >::dshape(), btas::STArray< T, N >::end(), btas::STArray< T, N >::find(), btas::Left, btas::QSDindexed_contract(), btas::QSTArray< T, N, Q >::qshape(), btas::QSTmerge(), and btas::shape().
template<size_t N, class Q > void mps::load (MPX< N, Q > & mpx, const char * filename)
load the MPX object from a file in binary format.
Definition at line 1200 of file MPSblas.h.
template<class Q > void mps::normalize (MPS< Q > & mps)
normalize the MPS
Definition at line 1126 of file MPSblas.h.
References nrm2(), and scal().
template<class Q > double mps::nrm2 (const MPS< Q > & mps)
Returns
the norm of the state
Definition at line 1106 of file MPSblas.h.
References btas::dot(), and btas::Left.
Referenced by dist(), btas::Dnormalize(), and normalize().
template<class Q > MPS<Q> mps::product_state (int L, const Qshapes< Q > & qp, const std::vector< int > & occ)
Parameters
L length of the chain
qp physical quantumnumbers
occ std::vector of length L ints containing the local physical quantumnumber on every site in the product state
Returns
create an product state chain of length L with physical indices qp and
Definition at line 411 of file MPSblas.h.
References btas::make_array().
template<size_t N, class Q > void mps::save (const MPX< N, Q > & mpx, const char * filename)
save the MPX object to a file in binary format.
Definition at line 1179 of file MPSblas.h.
template<size_t N, class Q > void mps::scal (double alpha, MPX< N, Q > & mpx)
scale the MPX with a constant factor
Parameters
alpha scalingfactor
mpx the MPX to be scaled
Definition at line 462 of file MPSblas.h.
References btas::QSDscal().
Referenced by compress(), exp(), and normalize().