Basic Tensor Algebra Subprograms (BTAS): btas Namespace Reference
btas Namespace Reference
Data Structures
struct null_deleter
Null-deleter.
class DcopyArglist
class DscalArglist
class DaxpyArglist
class DpermuteArglist
class DgemvArglist
class DgerArglist
class DgemmArglist
class DgesvdArglist
class TArray
Dense array class.
class TSubArray
Sub-array of dense array TArray.
class Qshapes
Quantum number vector.
class QSTArray
Quantum number-based block sparse array.
class QSTmergeInfo
Merged index infomation by quantum number-based sparse array.
class STArray
Block-sparse array class.
class T_arglist_base
Base class of argment list.
class R_arglist_single
Replication argment list for single argment function.
class R_arglist_double
Replication argment list for double argments function.
class R_arglist_triple
Replication argment list for triple argments function.
class R_arglist_quadra
Replication argment list for quadruple argments function.
class C_arglist_triple
Argment list for contraction.
class indexed_loop
Indexed loop for array object.
class indexed_loop< 1 >
Typedefs
typedef unsigned int uint
typedef unsigned long wint
typedef std::vector< int > Dshapes
Alias to dense shape.
template<size_t N>
using CArray = TArray< complex< float >, N >
Alias to single precision complex array.
template<size_t N>
using CSubArray = TSubArray< complex< float >, N >
Alias to single precision complex sub-array.
template<size_t N>
using DArray = TArray< double, N >
Alias to double precision real array.
template<size_t N>
using DSubArray = TSubArray< double, N >
Alias to double precision real sub-array.
template<size_t N>
using SArray = TArray< float, N >
Alias to single precision real array.
template<size_t N>
using SSubArray = TSubArray< float, N >
Alias to single precision real sub-array.
template<size_t N>
using ZArray = TArray< complex< double >, N >
Alias to double precision complex array.
template<size_t N>
using ZSubArray = TSubArray< complex< double >, N >
Alias to double precision complex sub-array.
template<size_t N, class Q = Quantum>
using QSDArray = QSTArray< double, N, Q >
Alias to double precision real quatum number-based sparse-array.
template<size_t N>
using SDArray = STArray< double, N >
alias to double precision real sparse-array
template<typename T , size_t N>
using TVector = std::array< T, N >
Template aliases to std::array<T, N>, for convenience.
template<size_t N>
using IVector = std::array< int, N >
Template aliases to std::array<int, N>, for convenience.
Enumerations
enum BTAS_ORDER { RowMajor =101, ColMajor =102 }
enum BTAS_TRANSPOSE { NoTrans =111, Trans =112, ConjTrans =113 }
enum BTAS_UPLO { Upper =121, Lower =122 }
enum BTAS_DIAG { NonUnit =131, Unit =132 }
enum BTAS_SIDE { Left =141, Right =142 }
enum BTAS_CONTRACT_TUNING {
JOBMASK_A_PMUTE = 0x20, JOBMASK_A_TRANS = 0x10, JOBMASK_B_PMUTE = 0x08, JOBMASK_B_TRANS = 0x04,
JOBMASK_BLAS_TYPE = 0x03
}
enum BTAS_ARROW_DIRECTION { LeftArrow, RightArrow }
Arrow direction of decomposed array Because SVD splits A = U * S * V^T, either U or V has a total quantum number equals to that of A.
Functions
template<size_t NA, size_t NB, size_t NC>
void gemv_contract_shape (const BTAS_TRANSPOSE &TransA, const IVector< NA > &a_shape, const IVector< NB > &b_shape, IVector< NC > &c_shape)
template<size_t NA, size_t NB, size_t NC>
void ger_contract_shape (const IVector< NA > &a_shape, const IVector< NB > &b_shape, IVector< NC > &c_shape)
template<size_t NA, size_t NB, size_t NC, size_t K>
void gemm_contract_shape (const BTAS_TRANSPOSE &TransA, const BTAS_TRANSPOSE &TransB, const IVector< NA > &a_shape, const IVector< NB > &b_shape, IVector< K > &contracts, IVector< NC > &c_shape)
template<size_t NA, size_t NB, size_t K>
unsigned int get_contract_jobs (const IVector< NA > &a_shape, const IVector< K > &a_contract, IVector< NA > &a_permute, const IVector< NB > &b_shape, const IVector< K > &b_contract, IVector< NB > &b_permute)
template<size_t NA, size_t NB, size_t K>
void indexed_contract_shape (const IVector< NA > &a_symbols, IVector< K > &a_contract, const IVector< NB > &b_symbols, IVector< K > &b_contract, IVector< NA+NB-K-K > &axb_symbols)
template<size_t N>
void permute_shape (const IVector< N > &pindex, const IVector< N > &xshape, IVector< N > &xstrides, IVector< N > &yshape)
template<size_t N>
void indexed_permute_shape (const IVector< N > &x_symbols, const IVector< N > &y_symbols, IVector< N > &pindex)
template<>
void _fast_copy< complex< float > > (size_t n, const complex< float > *x, complex< float > *y)
Fast copying for single precision complex array (calling cblas_ccopy)
template<>
void _fast_scal< complex< float > > (size_t n, const complex< float > &alpha, complex< float > *x)
Fast scaling for single precision complex array (calling cblas_cscal)
template<>
void _fast_add< complex< float > > (size_t n, const complex< float > *x, complex< float > *y)
Fast adding for single precision complex array (calling cblas_caxpy)
template<>
void _fast_copy< double > (size_t n, const double *x, double *y)
Fast copying for double precision real array (calling cblas_dcopy)
template<>
void _fast_scal< double > (size_t n, const double &alpha, double *x)
Fast scaling for double precision real array (calling cblas_dscal)
template<>
void _fast_add< double > (size_t n, const double *x, double *y)
Fast adding for double precision real array (calling cblas_daxpy)
template<size_t N>
void Dcopy (const DArray< N > &x, DArray< N > &y)
DCOPY: y := x.
template<size_t NX, size_t NY>
void DcopyFlatten (const DArray< NX > &x, DArray< NY > &y)
DCOPY as flattened vectors: y := x.
template<size_t NX, size_t NY>
void Dreshape (const DArray< NX > &x, const IVector< NY > &y_shape, DArray< NY > &y)
reshape rank of array
template<size_t N>
void Dscal (const double &alpha, DArray< N > &x)
DSCAL: x := alpha * x.
template<size_t N>
void Daxpy (const double &alpha, const DArray< N > &x, DArray< N > &y)
DAXPY: y := alpha * x + y.
template<size_t N>
double Ddot (const DArray< N > &x, const DArray< N > &y)
DDOT: inner product of x and y.
template<size_t N>
double Dnrm2 (const DArray< N > &x)
DNRM2: returns euclidean norm of x.
template<size_t NA, size_t NB, size_t NC>
void Dgemv (const BTAS_TRANSPOSE &TransA, const double &alpha, const DArray< NA > &a, const DArray< NB > &b, const double &beta, DArray< NC > &c)
DGEMV: Matrix-vector multiplication, c := alphe * a * b + beta * c.
template<size_t NA, size_t NB, size_t NC>
void Dger (const double &alpha, const DArray< NA > &a, const DArray< NB > &b, DArray< NC > &c)
DGER: Rank-update / direct product, c := alpha * (a x b)
template<size_t NA, size_t NB, size_t NC>
void Dgemm (const BTAS_TRANSPOSE &TransA, const BTAS_TRANSPOSE &TransB, const double &alpha, const DArray< NA > &a, const DArray< NB > &b, const double &beta, DArray< NC > &c)
DGEMM: Matrix-matrix multiplication, c := alpha * a * b + beta * c.
template<size_t NA, size_t NB>
void Ddimd (DArray< NA > &a, const DArray< NB > &b)
Non-BLAS function: a := a(general matrix) * b(diagonal matrix)
template<size_t NA, size_t NB>
void Ddidm (const DArray< NA > &a, DArray< NB > &b)
Non-BLAS function: b := a(diagonal matrix) * b(general matrix)
template<size_t NA, size_t NB, size_t NC>
void DblasWrapper (const double &alpha, const DArray< NA > &a, const DArray< NB > &b, const double &beta, DArray< NC > &c)
Wrapper function for DBLAS.
template<size_t N>
void Dnormalize (DArray< N > &x)
Normalization.
template<size_t N>
void Dorthogonalize (const DArray< N > &x, DArray< N > &y)
Orthogonalization.
template<size_t NA, size_t NB, size_t K>
void Dcontract (const double &alpha, const DArray< NA > &a, const IVector< K > &a_contract, const DArray< NB > &b, const IVector< K > &b_contract, const double &beta, DArray< NA+NB-K-K > &c)
Convenient contraction function for DArray.
template<size_t NA, size_t NB, size_t NC>
void Dindexed_contract (const double &alpha, const DArray< NA > &a, const IVector< NA > &a_symbols, const DArray< NB > &b, const IVector< NB > &b_symbols, const double &beta, DArray< NC > &c, const IVector< NC > &c_symbols)
Convenient indexed contraction function for DArray.
template<size_t NA, size_t K>
void Ddiagonal (const DArray< NA > &a, const IVector< K > &d_index, DArray< NA-K+1 > &b)
Function to get diagonal elements.
template<size_t M, size_t N>
void Dgetrf (const DArray< M+N-2 > &a, DArray< M > &l, DArray< N > &u, std::vector< int > &ipiv)
LU decomposition for general array.
template<size_t M, size_t N>
void Dgesv (const DArray< M > &a, const DArray< N > &b, DArray< N > &x)
Solve linear equation A*x = b.
template<size_t N>
void Dsyev (const DArray< 2 *N-2 > &a, DArray< 1 > &d, DArray< N > &z)
Solve eigenvalue problem for real symmetric matrix (SEP)
template<size_t N>
void Dgeev (const DArray< 2 *N-2 > &a, DArray< 1 > &wr, DArray< 1 > &wi, DArray< N > &vl, DArray< N > &vr)
Solve eigenvalue problem for real non-symmetric square matrix (NSGEP)
template<size_t N>
void Dsygv (const DArray< 2 *N-2 > &a, const DArray< 2 *N-2 > &b, DArray< 1 > &d, DArray< N > &z)
Solve generalized eigenvalue problem for real symmetric matrix.
template<size_t N>
void Dggev (const DArray< 2 *N-2 > &a, const DArray< 2 *N-2 > &b, DArray< 1 > &alphar, DArray< 1 > &alphai, DArray< 1 > &beta, DArray< N > &vl, DArray< N > &vr)
Solve generalized eigenvalue problem for non-symmetric real matrix pair.
template<size_t NA, size_t NU>
void Dgesvd (const DArray< NA > &a, DArray< 1 > &s, DArray< NU > &u, DArray< NA-NU+2 > &vt, bool calc_full_u=false, bool calc_full_vt=false)
Solve singular value decomposition.
template<size_t N>
void Dpermute (const DArray< N > &x, const IVector< N > &pindx, DArray< N > &y)
Permutation double precision real dense array.
template<size_t N>
void Dindexed_permute (const DArray< N > &x, const IVector< N > &x_symbols, DArray< N > &y, const IVector< N > &y_symbols)
Indexed permutation for double precision real dense array.
template<size_t N>
void Dreindex (const double *x, double *y, const IVector< N > &xstr, const IVector< N > &yshape)
template<>
void Dreindex< 1 > (const double *x, double *y, const IVector< 1 > &xstr, const IVector< 1 > &yshape)
template<>
void Dreindex< 2 > (const double *x, double *y, const IVector< 2 > &xstr, const IVector< 2 > &yshape)
template<>
void Dreindex< 3 > (const double *x, double *y, const IVector< 3 > &xstr, const IVector< 3 > &yshape)
template<>
void Dreindex< 4 > (const double *x, double *y, const IVector< 4 > &xstr, const IVector< 4 > &yshape)
template<>
void Dreindex< 5 > (const double *x, double *y, const IVector< 5 > &xstr, const IVector< 5 > &yshape)
template<>
void Dreindex< 6 > (const double *x, double *y, const IVector< 6 > &xstr, const IVector< 6 > &yshape)
template<>
void Dreindex< 7 > (const double *x, double *y, const IVector< 7 > &xstr, const IVector< 7 > &yshape)
template<>
void Dreindex< 8 > (const double *x, double *y, const IVector< 8 > &xstr, const IVector< 8 > &yshape)
template<>
void Dreindex< 9 > (const double *x, double *y, const IVector< 9 > &xstr, const IVector< 9 > &yshape)
template<>
void Dreindex< 10 > (const double *x, double *y, const IVector< 10 > &xstr, const IVector< 10 > &yshape)
template<>
void Dreindex< 11 > (const double *x, double *y, const IVector< 11 > &xstr, const IVector< 11 > &yshape)
template<>
void Dreindex< 12 > (const double *x, double *y, const IVector< 12 > &xstr, const IVector< 12 > &yshape)
template<>
void _fast_copy< float > (size_t n, const float *x, float *y)
Fast copying for single precision real array (calling cblas_scopy)
template<>
void _fast_scal< float > (size_t n, const float &alpha, float *x)
Fast scaling for single precision real array (calling cblas_sscal)
template<>
void _fast_add< float > (size_t n, const float *x, float *y)
Fast adding for single precision real array (calling cblas_saxpy)
template<>
void _fast_copy< complex< double > > (size_t n, const complex< double > *x, complex< double > *y)
Fast copying for double precision complex array (calling cblas_zcopy)
template<>
void _fast_scal< complex< double > > (size_t n, const complex< double > &alpha, complex< double > *x)
Fast scaling for double precision complex array (calling cblas_zscal)
template<>
void _fast_add< complex< double > > (size_t n, const complex< double > *x, complex< double > *y)
Fast adding for double precision complex array (calling cblas_zaxpy)
template<size_t NA, size_t NB, size_t NC, class Q = Quantum>
void gemv_contract_qshape (const BTAS_TRANSPOSE &TransA, const Q &a_qnum, const TVector< Qshapes< Q >, NA > &a_qshape, const Q &b_qnum, const TVector< Qshapes< Q >, NB > &b_qshape, Q &c_qnum, TVector< Qshapes< Q >, NC > &c_qshape)
template<size_t NA, size_t NB, size_t NC, class Q = Quantum>
void ger_contract_qshape (const Q &a_qnum, const TVector< Qshapes< Q >, NA > &a_qshape, const Q &b_qnum, const TVector< Qshapes< Q >, NB > &b_qshape, Q &c_qnum, TVector< Qshapes< Q >, NC > &c_qshape)
template<size_t NA, size_t NB, size_t NC, class Q = Quantum>
void gemm_contract_qshape (const BTAS_TRANSPOSE &TransA, const BTAS_TRANSPOSE &TransB, const Q &a_qnum, const TVector< Qshapes< Q >, NA > &a_qshape, const Q &b_qnum, const TVector< Qshapes< Q >, NB > &b_qshape, Q &c_qnum, TVector< Qshapes< Q >, NC > &c_qshape)
template<typename T , size_t NA, size_t NB, size_t NC, class Q = Quantum>
double f_indexbase_scale (const function< T(const TVector< Q, NA > &, const TVector< Q, NB > &, const TVector< Q, NC > &)> &f_scale, const TVector< Qshapes< Q >, NA > &a_qshape, const IVector< NA > &a_index, const TVector< Qshapes< Q >, NB > &b_qshape, const IVector< NB > &b_index, const TVector< Qshapes< Q >, NC > &c_qshape, const IVector< NC > &c_index)
Wrapper function to return Clebsch-Gordan coefficient depends on block index.
template<size_t N, class Q = Quantum>
void QSDdsum (const QSDArray< N, Q > &x, const QSDArray< N, Q > &y, QSDArray< N, Q > &z)
template<size_t N, size_t K, class Q = Quantum>
void QSDdsum (const QSDArray< N, Q > &x, const QSDArray< N, Q > &y, const IVector< K > &trace_index, QSDArray< N, Q > &z)
template<size_t N, class Q = Quantum>
void QSDcopy (const QSDArray< N, Q > &x, QSDArray< N, Q > &y)
DCOPY.
template<size_t N, class Q = Quantum>
void QSDscal (const double &alpha, QSDArray< N, Q > &x)
DSCAL.
template<size_t N, class Q = Quantum>
double QSDdotu (const QSDArray< N, Q > &x, const QSDArray< N, Q > &y)
DDOT(U): X^T * Y.
template<size_t N, class Q = Quantum>
double QSDdotc (const QSDArray< N, Q > &x, const QSDArray< N, Q > &y)
template<size_t N, class Q = Quantum>
void QSDaxpy (const double &alpha, const QSDArray< N, Q > &x, QSDArray< N, Q > &y)
DAXPY.
template<size_t NA, size_t NB, size_t NC, class Q = Quantum>
void QSDgemv (const BTAS_TRANSPOSE &TransA, const double &alpha, const QSDArray< NA, Q > &a, const QSDArray< NB, Q > &b, const double &beta, QSDArray< NC, Q > &c)
DGEMV.
template<size_t NA, size_t NB, size_t NC, class Q = Quantum>
void QSDger (const double &alpha, const QSDArray< NA, Q > &a, const QSDArray< NB, Q > &b, QSDArray< NC, Q > &c)
DGER.
template<size_t NA, size_t NB, size_t NC, class Q = Quantum>
void QSDgemm (const BTAS_TRANSPOSE &TransA, const BTAS_TRANSPOSE &TransB, const double &alpha, const QSDArray< NA, Q > &a, const QSDArray< NB, Q > &b, const double &beta, QSDArray< NC, Q > &c)
template<size_t NA, size_t NB, size_t NC, class Q = Quantum>
void QSDgemv (const function< double(const TVector< Q, NA > &, const TVector< Q, NB > &, const TVector< Q, NC > &)> &f_scale, const BTAS_TRANSPOSE &TransA, const double &alpha, const QSDArray< NA > &a, const QSDArray< NB > &b, const double &beta, QSDArray< NC > &c)
template<size_t NA, size_t NB, size_t NC, class Q = Quantum>
void QSDger (const function< double(const TVector< Q, NA > &, const TVector< Q, NB > &, const TVector< Q, NC > &)> &f_scale, const double &alpha, const QSDArray< NA > &a, const QSDArray< NB > &b, QSDArray< NC > &c)
template<size_t NA, size_t NB, size_t NC, class Q = Quantum>
void QSDgemm (const function< double(const TVector< Q, NA > &, const TVector< Q, NB > &, const TVector< Q, NC > &)> &f_scale, const BTAS_TRANSPOSE &TransA, const BTAS_TRANSPOSE &TransB, const double &alpha, const QSDArray< NA > &a, const QSDArray< NB > &b, const double &beta, QSDArray< NC > &c)
template<size_t N, class Q = Quantum>
void QSDnormalize (QSDArray< N, Q > &x)
Normalization.
template<size_t N, class Q = Quantum>
void QSDorthogonalize (const QSDArray< N, Q > &x, QSDArray< N, Q > &y)
Orthogonalization.
template<size_t NA, size_t NB, size_t NC, size_t K, class Q = Quantum>
void QSDcontract (const double &alpha, const QSDArray< NA, Q > &a, const IVector< K > &a_contract, const QSDArray< NB, Q > &b, const IVector< K > &b_contract, const double &beta, QSDArray< NC, Q > &c)
template<size_t NA, size_t NB, size_t NC, class Q = Quantum>
void QSDindexed_contract (const double &alpha, const QSDArray< NA, Q > &a, const IVector< NA > &a_symbols, const QSDArray< NB, Q > &b, const IVector< NB > &b_symbols, const double &beta, QSDArray< NC, Q > &c, const IVector< NC > &c_symbols)
template<size_t NA, size_t NB, size_t NC, class Q = Quantum>
double f_permuted_scale_axb (const TVector< Q, NA > &a_permuted_qindex, const IVector< NA > &a_permute, const TVector< Q, NB > &b_permuted_qindex, const IVector< NB > &b_permute, const TVector< Q, NC > &c_qindex, const function< double(const TVector< Q, NA > &, const TVector< Q, NB > &, const TVector< Q, NC > &)> &f_scale)
template<size_t NA, size_t NB, size_t NC, class Q = Quantum>
double f_permuted_scale_c (const TVector< Q, NA > &a_qindex, const TVector< Q, NB > &b_qindex, const TVector< Q, NC > &c_permuted_qindex, const IVector< NC > &c_permute, const function< double(const TVector< Q, NA > &, const TVector< Q, NB > &, const TVector< Q, NC > &)> &f_scale)
template<size_t NA, size_t NB, size_t NC, size_t K, class Q = Quantum>
void QSDcontract (const function< double(const TVector< Q, NA > &, const TVector< Q, NB > &, const TVector< Q, NC > &)> &f_scale, const double &alpha, const QSDArray< NA, Q > &a, const IVector< K > &a_contract, const QSDArray< NB, Q > &b, const IVector< K > &b_contract, const double &beta, QSDArray< NC, Q > &c)
template<size_t NA, size_t NB, size_t NC, class Q = Quantum>
void QSDindexed_contract (const function< double(const TVector< Q, NA > &, const TVector< Q, NB > &, const TVector< Q, NC > &)> &f_scale, const double &alpha, const QSDArray< NA, Q > &a, const IVector< NA > &a_symbols, const QSDArray< NB, Q > &b, const IVector< NB > &b_symbols, const double &beta, QSDArray< NC, Q > &c, const IVector< NC > &c_symbols)
template<class Q = Quantum>
void thread_QSDgesvd (const BTAS_ARROW_DIRECTION &ArrowDir, const QSDArray< 2, Q > &a, SDArray< 1 > &s, QSDArray< 2, Q > &u, QSDArray< 2, Q > &vt, bool calc_full_u=false, bool calc_full_vt=false)
Calling Dgesvd threaded for each non-zero block Only for matrix form. Suppose matrix A is block-diagonal, i.e. quantum number indices must be merged, which simplifies computation.
template<size_t NA, size_t NU, class Q = Quantum>
double QSDgesvd (const BTAS_ARROW_DIRECTION &ArrowDir, const QSDArray< NA, Q > &a, SDArray< 1 > &s, QSDArray< NU, Q > &u, QSDArray< NA-NU+2, Q > &vt, int Dim=0, double Tol=1.0)
Thin Singular Value Decomposition.
template<size_t NA, size_t NU, class Q = Quantum>
double QSDgesvd (const BTAS_ARROW_DIRECTION &ArrowDir, const QSDArray< NA, Q > &a, SDArray< 1 > &s_nz, SDArray< 1 > &s_rm, bool calc_full_u, QSDArray< NU, Q > &u_nz, QSDArray< NU, Q > &u_rm, bool calc_full_vt, QSDArray< NA-NU+2, Q > &vt_nz, QSDArray< NA-NU+2, Q > &vt_rm, int Dim=0, double Tol=1.0)
Full SVD.
template<size_t MR, size_t N, class Q = Quantum>
void QSDmerge (const QSTmergeInfo< MR, Q > &rows_info, const QSDArray< N, Q > &a, QSDArray< 1+N-MR, Q > &b)
template<size_t N, size_t MC, class Q = Quantum>
void QSDmerge (const QSDArray< N, Q > &a, const QSTmergeInfo< MC, Q > &cols_info, QSDArray< N-MC+1, Q > &b)
template<size_t MR, size_t MC, class Q = Quantum>
void QSDmerge (const QSTmergeInfo< MR, Q > &rows_info, const QSDArray< MR+MC, Q > &a, const QSTmergeInfo< MC, Q > &cols_info, QSDArray< 2, Q > &b)
template<size_t MR, size_t N, class Q = Quantum>
void QSDexpand (const QSTmergeInfo< MR, Q > &rows_info, const QSDArray< 1+N-MR, Q > &a, QSDArray< N, Q > &b)
template<size_t N, size_t MC, class Q = Quantum>
void QSDexpand (const QSDArray< N-MC+1, Q > &a, const QSTmergeInfo< MC, Q > &cols_info, QSDArray< N, Q > &b)
template<size_t MR, size_t MC, class Q = Quantum>
void QSDexpand (const QSTmergeInfo< MR, Q > &rows_info, const QSDArray< 2, Q > &a, const QSTmergeInfo< MC, Q > &cols_info, QSDArray< MR+MC, Q > &b)
template<size_t N, class Q = Quantum>
void QSDpermute (const QSDArray< N, Q > &x, const IVector< N > &pindex, QSDArray< N, Q > &y)
template<size_t N, class Q = Quantum>
void QSDindexed_permute (const QSDArray< N, Q > &x, const IVector< N > &x_symbols, QSDArray< N, Q > &y, const IVector< N > &y_symbols)
template<size_t N, class Q >
Q operator* (const TVector< Qshapes< Q >, N > &vec, const IVector< N > &index)
Indexed product of TVector<Qshapes<Q>, N>
template<size_t N, class Q >
Q operator* (const IVector< N > &index, const TVector< Qshapes< Q >, N > &vec)
Indexed product of TVector<Qshapes<Q>, N>
template<typename T , size_t N, class Q = Quantum>
void QSTdsum (const QSTArray< T, N, Q > &x, const QSTArray< T, N, Q > &y, QSTArray< T, N, Q > &z)
Direct sum of arrays X and Y, adding to Z.
template<typename T , size_t N, size_t K, class Q = Quantum>
void QSTdsum (const QSTArray< T, N, Q > &x, const QSTArray< T, N, Q > &y, const IVector< K > &trace_index, QSTArray< T, N, Q > &z)
Partial direct sum of arrays X and Y, adding to Z.
template<typename T , size_t MR, size_t N, class Q = Quantum>
void QSTmerge (const QSTmergeInfo< MR, Q > &rows_info, const QSTArray< T, N, Q > &a, QSTArray< T, 1+N-MR, Q > &b)
Merging row ranks.
template<typename T , size_t N, size_t MC, class Q = Quantum>
void QSTmerge (const QSTArray< T, N, Q > &a, const QSTmergeInfo< MC, Q > &cols_info, QSTArray< T, N-MC+1, Q > &b)
Merging col ranks.
template<typename T , size_t MR, size_t MC, class Q = Quantum>
void QSTmerge (const QSTmergeInfo< MR, Q > &rows_info, const QSTArray< T, MR+MC, Q > &a, const QSTmergeInfo< MC, Q > &cols_info, QSTArray< T, 2, Q > &b)
Merging row and col ranks to form matrix.
template<typename T , size_t MR, size_t N, class Q = Quantum>
void QSTexpand (const QSTmergeInfo< MR, Q > &rows_info, const QSTArray< T, 1+N-MR, Q > &a, QSTArray< T, N, Q > &b)
Expanding row ranks.
template<typename T , size_t N, size_t MC, class Q = Quantum>
void QSTexpand (const QSTArray< T, N-MC+1, Q > &a, const QSTmergeInfo< MC, Q > &cols_info, QSTArray< T, N, Q > &b)
Expanding col ranks.
template<typename T , size_t MR, size_t MC, class Q = Quantum>
void QSTexpand (const QSTmergeInfo< MR, Q > &rows_info, const QSTArray< T, 2, Q > &a, const QSTmergeInfo< MC, Q > &cols_info, QSTArray< T, MR+MC, Q > &b)
Expanding row and col of matrix.
bool _btas_contract_allowed (const Dshapes &x, const Dshapes &y)
Compare Dshapes ignoring 0-sized index.
template<size_t NA, size_t NB, size_t NC>
void gemv_contract_dshape (const BTAS_TRANSPOSE &TransA, const TVector< Dshapes, NA > &a_dshape, const TVector< Dshapes, NB > &b_dshape, TVector< Dshapes, NC > &c_dshape)
template<size_t NA, size_t NB, size_t NC>
void ger_contract_dshape (const TVector< Dshapes, NA > &a_dshape, const TVector< Dshapes, NB > &b_dshape, TVector< Dshapes, NC > &c_dshape)
template<size_t NA, size_t NB, size_t NC>
void gemm_contract_dshape (const BTAS_TRANSPOSE &TransA, const BTAS_TRANSPOSE &TransB, const TVector< Dshapes, NA > &a_dshape, const TVector< Dshapes, NB > &b_dshape, TVector< Dshapes, NC > &c_dshape)
template<size_t N>
void SDdsum (const SDArray< N > &x, const SDArray< N > &y, SDArray< N > &z)
template<size_t N, size_t K>
void SDdsum (const SDArray< N > &x, const SDArray< N > &y, const IVector< K > &trace_index, SDArray< N > &z)
template<size_t N>
void serial_SDcopy (const SDArray< N > &x, SDArray< N > &y, bool _up_cast=false)
Call Dcopy per every non-zero block.
template<size_t N>
double serial_SDdot (const SDArray< N > &x, const SDArray< N > &y)
Call Ddot per every non-zero block.
template<size_t N>
void serial_SDscal (const double &alpha, SDArray< N > &x)
Call Dscal per every non-zero block.
template<size_t N>
void serial_SDaxpy (const double &alpha, const SDArray< N > &x, SDArray< N > &y)
Call Daxpy per every non-zero block.
template<size_t N>
void thread_SDcopy (const SDArray< N > &x, SDArray< N > &y, bool _up_cast)
Call Dcopy per every non-zero block.
template<size_t N>
void thread_SDscal (const double &alpha, SDArray< N > &x)
Call Dscal per every non-zero block.
template<size_t N>
void thread_SDaxpy (const double &alpha, const SDArray< N > &x, SDArray< N > &y)
Call Daxpy per every non-zero block.
template<size_t NA, size_t NB, size_t NC>
void thread_SDgemv (const BTAS_TRANSPOSE &TransA, const double &alpha, const SDArray< NA > &a, const SDArray< NB > &b, SDArray< NC > &c)
Call Dgemv per every non-zero block.
template<size_t NA, size_t NB, size_t NC>
void thread_SDger (const double &alpha, const SDArray< NA > &a, const SDArray< NB > &b, SDArray< NC > &c)
Call Dger per every non-zero block.
template<size_t NA, size_t NB, size_t NC>
void thread_SDgemm (const BTAS_TRANSPOSE &TransA, const BTAS_TRANSPOSE &TransB, const double &alpha, const SDArray< NA > &a, const SDArray< NB > &b, SDArray< NC > &c)
Call Dgemm per every non-zero block.
template<size_t NA, size_t NB, size_t NC>
void thread_SDgemv (function< double(const IVector< NA > &, const IVector< NB > &, const IVector< NC > &)> f_scale, const BTAS_TRANSPOSE &TransA, const double &alpha, const SDArray< NA > &a, const SDArray< NB > &b, SDArray< NC > &c)
Call Dgemv per every non-zero block.
template<size_t NA, size_t NB, size_t NC>
void thread_SDger (function< double(const IVector< NA > &, const IVector< NB > &, const IVector< NC > &)> f_scale, const double &alpha, const SDArray< NA > &a, const SDArray< NB > &b, SDArray< NC > &c)
Call Dger per every non-zero block.
template<size_t NA, size_t NB, size_t NC>
void thread_SDgemm (function< double(const IVector< NA > &, const IVector< NB > &, const IVector< NC > &)> f_scale, const BTAS_TRANSPOSE &TransA, const BTAS_TRANSPOSE &TransB, const double &alpha, const SDArray< NA > &a, const SDArray< NB > &b, SDArray< NC > &c)
Call Dgemm per every non-zero block.
template<size_t N>
void SDcopy (const SDArray< N > &x, SDArray< N > &y, bool _up_cast=false)
template<size_t N>
void SDscal (const double &alpha, SDArray< N > &x)
template<size_t N>
double SDdot (const SDArray< N > &x, const SDArray< N > &y)
template<size_t N>
void SDaxpy (const double &alpha, const SDArray< N > &x, SDArray< N > &y)
template<size_t NA, size_t NB, size_t NC>
void SDgemv (const BTAS_TRANSPOSE &TransA, const double &alpha, const SDArray< NA > &a, const SDArray< NB > &b, const double &beta, SDArray< NC > &c)
template<size_t NA, size_t NB, size_t NC>
void SDger (const double &alpha, const SDArray< NA > &a, const SDArray< NB > &b, SDArray< NC > &c)
template<size_t NA, size_t NB, size_t NC>
void SDgemm (const BTAS_TRANSPOSE &TransA, const BTAS_TRANSPOSE &TransB, const double &alpha, const SDArray< NA > &a, const SDArray< NB > &b, const double &beta, SDArray< NC > &c)
template<size_t NA, size_t NB>
void SDdimd (SDArray< NA > &a, const SDArray< NB > &b)
Non-BLAS function: (general matrix) * (diagonal matrix)
template<size_t NA, size_t NB>
void SDdidm (const SDArray< NA > &a, SDArray< NB > &b)
Non-BLAS function: (diagonal matrix) * (general matrix)
template<size_t NA, size_t NB, size_t NC>
void SDblasWrapper (const double &alpha, const SDArray< NA > &a, const SDArray< NB > &b, const double &beta, SDArray< NC > &c)
Wrapper function for DBLAS.
template<size_t N>
void SDnormalize (SDArray< N > &x)
Normalization.
template<size_t N>
void SDorthogonalize (const SDArray< N > &x, SDArray< N > &y)
Orthogonalization.
template<size_t NA, size_t NB, size_t K>
void SDcontract (const double &alpha, const SDArray< NA > &a, const IVector< K > &a_contract, const SDArray< NB > &b, const IVector< K > &b_contract, const double &beta, SDArray< NA+NB-K-K > &c)
Convenient sparse-array contraction function.
template<size_t NA, size_t NB, size_t NC>
void SDindexed_contract (const double &alpha, const SDArray< NA > &a, const IVector< NA > &a_symbols, const SDArray< NB > &b, const IVector< NB > &b_symbols, const double &beta, SDArray< NC > &c, const IVector< NC > &c_symbols)
Convenient sparse-array indexed-contraction function.
template<size_t NA, size_t K>
void SDdiagonal (const SDArray< NA > &a, const IVector< K > &d_index, SDArray< NA-K+1 > &b)
Function to get diagonal elements for sparse array.
template<size_t N>
void serial_SDpermute (const SDArray< N > &x, const IVector< N > &pindex, SDArray< N > &y)
Call sparse-array permutation (serial run)
template<size_t N>
void thread_SDpermute (const SDArray< N > &x, const IVector< N > &pindex, SDArray< N > &y)
Call sparse-array permutation (threaded)
template<size_t N>
void SDpermute (const SDArray< N > &x, const IVector< N > &pindex, SDArray< N > &y)
Call sparse-array permutation (wrapper)
template<size_t N>
void SDindexed_permute (const SDArray< N > &x, const IVector< N > &x_symbols, SDArray< N > &y, const IVector< N > &y_symbols)
Call sparse-array indexed-permutation (wrapper)
bool _dsum_check_dshape (const Dshapes &x, const Dshapes &y)
To check dense block shapes.
template<typename T , size_t N>
void STdsum (const STArray< T, N > &x, const STArray< T, N > &y, STArray< T, N > &z)
Direct sum of arrays X and Y, adding to Z.
template<typename T , size_t N, size_t K>
void STdsum (const STArray< T, N > &x, const STArray< T, N > &y, const IVector< K > &trace_index, STArray< T, N > &z)
Partial direct sum of arrays X and Y, adding to Z.
template<class Arglist >
void parallel_call (std::vector< Arglist > &task_list)
template<typename T , size_t N>
TVector< T, N > uniform (const T &value)
Convenient constructor of TVector with const value.
template<typename T >
TVector< T, 1 > make_array (T v01)
Convenient TVector constructor for N = 1.
template<typename T >
TVector< T, 2 > make_array (T v01, T v02)
Convenient TVector constructor for N = 2.
template<typename T >
TVector< T, 3 > make_array (T v01, T v02, T v03)
Convenient TVector constructor for N = 3.
template<typename T >
TVector< T, 4 > make_array (T v01, T v02, T v03, T v04)
Convenient TVector constructor for N = 4.
template<typename T >
TVector< T, 5 > make_array (T v01, T v02, T v03, T v04, T v05)
Convenient TVector constructor for N = 5.
template<typename T >
TVector< T, 6 > make_array (T v01, T v02, T v03, T v04, T v05, T v06)
Convenient TVector constructor for N = 6.
template<typename T >
TVector< T, 7 > make_array (T v01, T v02, T v03, T v04, T v05, T v06, T v07)
Convenient TVector constructor for N = 7.
template<typename T >
TVector< T, 8 > make_array (T v01, T v02, T v03, T v04, T v05, T v06, T v07, T v08)
Convenient TVector constructor for N = 8.
template<typename T >
TVector< T, 9 > make_array (T v01, T v02, T v03, T v04, T v05, T v06, T v07, T v08, T v09)
Convenient TVector constructor for N = 9.
template<typename T >
TVector< T, 10 > make_array (T v01, T v02, T v03, T v04, T v05, T v06, T v07, T v08, T v09, T v10)
Convenient TVector constructor for N = 10.
template<typename T >
TVector< T, 11 > make_array (T v01, T v02, T v03, T v04, T v05, T v06, T v07, T v08, T v09, T v10, T v11)
Convenient TVector constructor for N = 11.
template<typename T >
TVector< T, 12 > make_array (T v01, T v02, T v03, T v04, T v05, T v06, T v07, T v08, T v09, T v10, T v11, T v12)
Convenient TVector constructor for N = 12.
template<typename T , size_t N>
T operator* (const TVector< std::vector< T >, N > &vec, const IVector< N > &index)
Indexed product of TVector<std::vector<T>, N>
template<typename T , size_t N>
T operator* (const IVector< N > &index, const TVector< std::vector< T >, N > &vec)
Indexed product of TVector<std::vector<T>, N>
template<typename T , size_t N>
TVector< T, N > operator& (const TVector< std::vector< T >, N > &vec, const IVector< N > &index)
Abstract TVector<T, N> from TVector<std::vector<T>, N> by index.
template<typename T , size_t N>
TVector< T, N > operator& (const IVector< N > &index, const TVector< std::vector< T >, N > &vec)
Abstract TVector<T, N> from TVector<std::vector<T>, N> by index.
template<size_t N>
int dot (const IVector< N > &v1, const IVector< N > &v2)
Dot product of two integer vectors.
template<>
int dot< 1 > (const IVector< 1 > &v1, const IVector< 1 > &v2)
Dot product with small overhead, specialized for N = 1.
template<>
int dot< 2 > (const IVector< 2 > &v1, const IVector< 2 > &v2)
Dot product with small overhead, specialized for N = 2.
template<>
int dot< 3 > (const IVector< 3 > &v1, const IVector< 3 > &v2)
Dot product with small overhead, specialized for N = 3.
template<>
int dot< 4 > (const IVector< 4 > &v1, const IVector< 4 > &v2)
Dot product with small overhead, specialized for N = 4.
template<>
int dot< 5 > (const IVector< 5 > &v1, const IVector< 5 > &v2)
Dot product with small overhead, specialized for N = 5.
template<>
int dot< 6 > (const IVector< 6 > &v1, const IVector< 6 > &v2)
Dot product with small overhead, specialized for N = 6.
template<>
int dot< 7 > (const IVector< 7 > &v1, const IVector< 7 > &v2)
Dot product with small overhead, specialized for N = 7.
template<>
int dot< 8 > (const IVector< 8 > &v1, const IVector< 8 > &v2)
Dot product with small overhead, specialized for N = 8.
template<>
int dot< 9 > (const IVector< 9 > &v1, const IVector< 9 > &v2)
Dot product with small overhead, specialized for N = 9.
template<>
int dot< 10 > (const IVector< 10 > &v1, const IVector< 10 > &v2)
Dot product with small overhead, specialized for N = 10.
template<>
int dot< 11 > (const IVector< 11 > &v1, const IVector< 11 > &v2)
Dot product with small overhead, specialized for N = 11.
template<>
int dot< 12 > (const IVector< 12 > &v1, const IVector< 12 > &v2)
Dot product with small overhead, specialized for N = 12.
IVector< 1 > shape (int n01)
Convenient IVector constructor for N = 1.
IVector< 2 > shape (int n01, int n02)
Convenient IVector constructor for N = 2.
IVector< 3 > shape (int n01, int n02, int n03)
Convenient IVector constructor for N = 3.
IVector< 4 > shape (int n01, int n02, int n03, int n04)
Convenient IVector constructor for N = 4.
IVector< 5 > shape (int n01, int n02, int n03, int n04, int n05)
Convenient IVector constructor for N = 5.
IVector< 6 > shape (int n01, int n02, int n03, int n04, int n05, int n06)
Convenient IVector constructor for N = 6.
IVector< 7 > shape (int n01, int n02, int n03, int n04, int n05, int n06, int n07)
Convenient IVector constructor for N = 7.
IVector< 8 > shape (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08)
Convenient IVector constructor for N = 8.
IVector< 9 > shape (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09)
Convenient IVector constructor for N = 9.
IVector< 10 > shape (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10)
Convenient IVector constructor for N = 10.
IVector< 11 > shape (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10, int n11)
Convenient IVector constructor for N = 11.
IVector< 12 > shape (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10, int n11, int n12)
Convenient IVector constructor for N = 12.
template<size_t N>
IVector< N > sequence (int first=0, int incl=1)
Convenient IVector constructor to return sequence.
template<typename T , size_t N>
TVector< T, N > transpose (const TVector< T, N > &vec, int K)
Return transposed vector.
template<typename T , size_t N>
TVector< T, N > permute (const TVector< T, N > &vec, const IVector< N > &pindex)
Return permuted vector.
Dshapes operator* (const Dshapes &ds1, const Dshapes &ds2)
Direct product of Dshapes.
template<typename T >
void _fast_copy (size_t n, const T *x, T *y)
Fast copy for general type.
template<typename T >
void _fast_scal (size_t n, const T &alpha, T *x)
Fast scale function for general type (this must be specialized).
template<typename T >
void _fast_add (size_t n, const T *x, T *y)
Fast addition for general type (this must be specialized).
template<typename T >
void fast_copy (const std::vector< T > &v1, std::vector< T > &v2)
Fast copy function for std::vector<T>
template<typename T >
void fast_scal (const T &alpha, std::vector< T > &v)
Fast scale function for std::vector<T>
template<typename T >
void fast_add (const std::vector< T > &v1, std::vector< T > &v2)
Fast copy function for std::vector<T>
template<size_t NA, size_t NB, size_t K>
void contract (const double &alpha, const DArray< NA > &a, const IVector< K > &a_contract, const DArray< NB > &b, const IVector< K > &b_contract, const double &beta, DArray< NA+NB-K-K > &c)
template<size_t NA, size_t NB, size_t NC>
void indexed_contract (const double &alpha, const DArray< NA > &a, const IVector< NA > &a_symbols, const DArray< NB > &b, const IVector< NB > &b_symbols, const double &beta, DArray< NC > &c, const IVector< NC > &c_symbols)
template<size_t NA, size_t NB, size_t K>
void contract (const double &alpha, const SDArray< NA > &a, const IVector< K > &a_contract, const SDArray< NB > &b, const IVector< K > &b_contract, const double &beta, SDArray< NA+NB-K-K > &c)
template<size_t NA, size_t NB, size_t NC>
void indexed_contract (const double &alpha, const SDArray< NA > &a, const IVector< NA > &a_symbols, const SDArray< NB > &b, const IVector< NB > &b_symbols, const double &beta, SDArray< NC > &c, const IVector< NC > &c_symbols)
template<size_t NA, size_t NB, size_t K, class Q = Quantum>
void contract (const double &alpha, const QSDArray< NA, Q > &a, const IVector< K > &a_contract, const QSDArray< NB, Q > &b, const IVector< K > &b_contract, const double &beta, QSDArray< NA+NB-K-K, Q > &c)
template<size_t NA, size_t NB, size_t NC, class Q = Quantum>
void indexed_contract (const double &alpha, const QSDArray< NA, Q > &a, const IVector< NA > &a_symbols, const QSDArray< NB, Q > &b, const IVector< NB > &b_symbols, const double &beta, QSDArray< NC, Q > &c, const IVector< NC > &c_symbols)
template<size_t N, size_t K>
void decompose_shape (const IVector< K > &index, IVector< N > &a_permute)
template<size_t NA, size_t NL>
void indexed_decompose_shape (const IVector< NA > &a_symbols, const IVector< NL > &l_symbols, const IVector< NA-NL+2 > &r_symbols, IVector< NA > &a_permute, IVector< NL > &l_permute, IVector< NA-NL+2 > &r_permute)
template<size_t N>
void _lsv_truncate (const DArray< N > &lsv, DArray< N > &lsv_tr, int D=0)
template<size_t N>
void _rsv_truncate (const DArray< N > &rsv, DArray< N > &rsv_tr, int D=0)
template<size_t NA, size_t K>
double decompose (const DArray< NA > &a, const IVector< K > &index, DArray< NA-K+1 > &l, DArray< K+1 > &r, int D=0)
template<size_t NA, size_t NL>
double indexed_decompose (const DArray< NA > &a, const IVector< NA > &a_symbols, DArray< NL > &l, const IVector< NL > &l_symbols, DArray< NA-NL+2 > &r, const IVector< NA-NL+2 > &r_symbols, int D=0)
template<size_t NA, size_t K, class Q = Quantum>
double decompose (const QSDArray< NA, Q > &a, const IVector< K > &index, QSDArray< NA-K+1, Q > &l, QSDArray< K+1, Q > &r, int D=0)
template<size_t NA, size_t NL, class Q = Quantum>
double indexed_decompose (const QSDArray< NA, Q > &a, const IVector< NA > &a_symbols, QSDArray< NL, Q > &l, const IVector< NL > &l_symbols, QSDArray< NA-NL+2, Q > &r, const IVector< NA-NL+2 > &r_symbols, int D=0)
template<size_t N>
void permute (const DArray< N > &x, const IVector< N > &index, DArray< N > &y)
template<size_t N>
void indexed_permute (const DArray< N > &x, const IVector< N > &x_symbols, DArray< N > &y, const IVector< N > &y_symbols)
template<size_t N>
void permute (const SDArray< N > &x, const IVector< N > &index, SDArray< N > &y)
template<size_t N>
void indexed_permute (const SDArray< N > &x, const IVector< N > &x_symbols, SDArray< N > &y, const IVector< N > &y_symbols)
template<size_t N, class Q = Quantum>
void permute (const QSDArray< N, Q > &x, const IVector< N > &index, QSDArray< N, Q > &y)
template<size_t N, class Q = Quantum>
void indexed_permute (const QSDArray< N, Q > &x, const IVector< N > &x_symbols, QSDArray< N, Q > &y, const IVector< N > &y_symbols)
Typedef Documentation
template<size_t N> using btas::CArray = typedef TArray<complex<float>, N>
Alias to single precision complex array.
Definition at line 23 of file CArray.h.
template<size_t N> using btas::CSubArray = typedef TSubArray<complex<float>, N>
Alias to single precision complex sub-array.
Definition at line 27 of file CArray.h.
template<size_t N> using btas::DArray = typedef TArray<double, N>
Alias to double precision real array.
Definition at line 22 of file DArray.h.
typedef std::vector<int> btas::Dshapes
Alias to dense shape.
Definition at line 28 of file btas.h.
template<size_t N> using btas::DSubArray = typedef TSubArray<double, N>
Alias to double precision real sub-array.
Definition at line 26 of file DArray.h.
template<size_t N> using btas::IVector = typedef std::array<int, N>
Template aliases to std::array<int, N>, for convenience.
Definition at line 53 of file TVector.h.
template<size_t N, class Q = Quantum> using btas::QSDArray = typedef QSTArray<double, N, Q>
Alias to double precision real quatum number-based sparse-array.
Definition at line 14 of file QSDArray.h.
template<size_t N> using btas::SArray = typedef TArray<float, N>
Alias to single precision real array.
Definition at line 22 of file SArray.h.
template<size_t N> using btas::SDArray = typedef STArray<double, N>
alias to double precision real sparse-array
Definition at line 14 of file SDArray.h.
template<size_t N> using btas::SSubArray = typedef TSubArray<float, N>
Alias to single precision real sub-array.
Definition at line 26 of file SArray.h.
template<typename T , size_t N> using btas::TVector = typedef std::array<T, N>
Template aliases to std::array<T, N>, for convenience.
Definition at line 49 of file TVector.h.
typedef unsigned int btas::uint
Definition at line 24 of file btas.h.
typedef unsigned long btas::wint
Definition at line 25 of file btas.h.
template<size_t N> using btas::ZArray = typedef TArray<complex<double>, N>
Alias to double precision complex array.
Definition at line 23 of file ZArray.h.
template<size_t N> using btas::ZSubArray = typedef TSubArray<complex<double>, N>
Alias to double precision complex sub-array.
Definition at line 27 of file ZArray.h.
Enumeration Type Documentation
enum btas::BTAS_ARROW_DIRECTION
Arrow direction of decomposed array Because SVD splits A = U * S * V^T, either U or V has a total quantum number equals to that of A.
LeftArrow:
Defined U has the quantum number of A and V^T has zero quantum number
RightArrow:
Defined V^T has the quantum number of A and U has zero quantum number
Enumerator
LeftArrow
U has the quantum number of A in SVD.
RightArrow
V^T has the quantum number of A in SVD.
Definition at line 25 of file QSDlapack.h.
enum btas::BTAS_CONTRACT_TUNING
Enumerator
JOBMASK_A_PMUTE
JOBMASK_A_TRANS
JOBMASK_B_PMUTE
JOBMASK_B_TRANS
JOBMASK_BLAS_TYPE
Definition at line 84 of file btas_contract_shape.h.
enum btas::BTAS_DIAG
Enumerator
NonUnit
Unit
Definition at line 49 of file blas_cxx_interface.h.
enum btas::BTAS_ORDER
Enumerator
RowMajor
ColMajor
Definition at line 46 of file blas_cxx_interface.h.
enum btas::BTAS_SIDE
Enumerator
Left
Right
Definition at line 50 of file blas_cxx_interface.h.
enum btas::BTAS_TRANSPOSE
Enumerator
NoTrans
Trans
ConjTrans
Definition at line 47 of file blas_cxx_interface.h.
enum btas::BTAS_UPLO
Enumerator
Upper
Lower
Definition at line 48 of file blas_cxx_interface.h.
Function Documentation
bool btas::_btas_contract_allowed (const Dshapes & x, const Dshapes & y) inline
Compare Dshapes ignoring 0-sized index.
Definition at line 16 of file btas_contract_dshape.h.
Referenced by gemm_contract_dshape(), and gemv_contract_dshape().
bool btas::_dsum_check_dshape (const Dshapes & x, const Dshapes & y) inline
To check dense block shapes.
Definition at line 11 of file STdsum.h.
Referenced by STdsum().
template<typename T > void btas::_fast_add (size_t n, const T * x, T * y) inline
Fast addition for general type (this must be specialized).
Definition at line 421 of file TVector.h.
Referenced by fast_add().
template<> void btas::_fast_add< complex< double > > (size_t n, const complex< double > * x, complex< double > * y) inline
Fast adding for double precision complex array (calling cblas_zaxpy)
Definition at line 43 of file ZArray.h.
template<> void btas::_fast_add< complex< float > > (size_t n, const complex< float > * x, complex< float > * y) inline
Fast adding for single precision complex array (calling cblas_caxpy)
Definition at line 43 of file CArray.h.
template<> void btas::_fast_add< double > (size_t n, const double * x, double * y) inline
Fast adding for double precision real array (calling cblas_daxpy)
Definition at line 38 of file DArray.h.
template<> void btas::_fast_add< float > (size_t n, const float * x, float * y) inline
Fast adding for single precision real array (calling cblas_saxpy)
Definition at line 38 of file SArray.h.
template<typename T > void btas::_fast_copy (size_t n, const T * x, T * y) inline
Fast copy for general type.
Definition at line 413 of file TVector.h.
Referenced by btas::TSubArray< T, N >::copy(), btas::TArray< T, N >::copy(), and fast_copy().
template<> void btas::_fast_copy< complex< double > > (size_t n, const complex< double > * x, complex< double > * y) inline
Fast copying for double precision complex array (calling cblas_zcopy)
Definition at line 31 of file ZArray.h.
template<> void btas::_fast_copy< complex< float > > (size_t n, const complex< float > * x, complex< float > * y) inline
Fast copying for single precision complex array (calling cblas_ccopy)
Definition at line 31 of file CArray.h.
template<> void btas::_fast_copy< double > (size_t n, const double * x, double * y) inline
Fast copying for double precision real array (calling cblas_dcopy)
Definition at line 30 of file DArray.h.
template<> void btas::_fast_copy< float > (size_t n, const float * x, float * y) inline
Fast copying for single precision real array (calling cblas_scopy)
Definition at line 30 of file SArray.h.
template<typename T > void btas::_fast_scal (size_t n, const T & alpha, T * x) inline
Fast scale function for general type (this must be specialized).
Definition at line 417 of file TVector.h.
Referenced by fast_scal().
template<> void btas::_fast_scal< complex< double > > (size_t n, const complex< double > & alpha, complex< double > * x) inline
Fast scaling for double precision complex array (calling cblas_zscal)
Definition at line 37 of file ZArray.h.
template<> void btas::_fast_scal< complex< float > > (size_t n, const complex< float > & alpha, complex< float > * x) inline
Fast scaling for single precision complex array (calling cblas_cscal)
Definition at line 37 of file CArray.h.
template<> void btas::_fast_scal< double > (size_t n, const double & alpha, double * x) inline
Fast scaling for double precision real array (calling cblas_dscal)
Definition at line 34 of file DArray.h.
template<> void btas::_fast_scal< float > (size_t n, const float & alpha, float * x) inline
Fast scaling for single precision real array (calling cblas_sscal)
Definition at line 34 of file SArray.h.
template<size_t N> void btas::_lsv_truncate (const DArray< N > & lsv, DArray< N > & lsv_tr, int D = 0)
Definition at line 108 of file decompose.h.
References btas::TArray< T, N >::resize(), and btas::TArray< T, N >::shape().
Referenced by decompose(), and indexed_decompose().
template<size_t N> void btas::_rsv_truncate (const DArray< N > & rsv, DArray< N > & rsv_tr, int D = 0)
Definition at line 122 of file decompose.h.
References btas::TArray< T, N >::resize(), and btas::TArray< T, N >::shape().
Referenced by decompose(), and indexed_decompose().
template<size_t NA, size_t NB, size_t K> void btas::contract (const double & alpha, const DArray< NA > & a, const IVector< K > & a_contract, const DArray< NB > & b, const IVector< K > & b_contract, const double & beta, DArray< NA+NB-K-K > & c) inline
Definition at line 12 of file contract.h.
References Dcontract().
template<size_t NA, size_t NB, size_t K> void btas::contract (const double & alpha, const SDArray< NA > & a, const IVector< K > & a_contract, const SDArray< NB > & b, const IVector< K > & b_contract, const double & beta, SDArray< NA+NB-K-K > & c) inline
Definition at line 30 of file contract.h.
References SDcontract().
template<size_t NA, size_t NB, size_t K, class Q = Quantum> void btas::contract (const double & alpha, const QSDArray< NA, Q > & a, const IVector< K > & a_contract, const QSDArray< NB, Q > & b, const IVector< K > & b_contract, const double & beta, QSDArray< NA+NB-K-K, Q > & c) inline
Definition at line 48 of file contract.h.
References QSDcontract().
template<size_t N> void btas::Daxpy (const double & alpha, const DArray< N > & x, DArray< N > & y)
DAXPY: y := alpha * x + y.
Definition at line 62 of file Dblas.h.
References BTAS_THROW, btas::TArray< T, N >::data(), btas::TArray< T, N >::resize(), btas::TArray< T, N >::shape(), and btas::TArray< T, N >::size().
Referenced by btas::DaxpyArglist< N >::call(), DENSE_TEST(), Dorthogonalize(), and serial_SDaxpy().
template<size_t NA, size_t NB, size_t NC> void btas::DblasWrapper (const double & alpha, const DArray< NA > & a, const DArray< NB > & b, const double & beta, DArray< NC > & c)
Wrapper function for DBLAS.
When calling as vector-matrix multiplication (i.e. call DGEMV with Trans), tranposed array is returned: c = (a * b)^T = b^T * a^T
Definition at line 222 of file Dblas.h.
References Dgemm(), Dgemv(), NoTrans, and Trans.
template<size_t NA, size_t NB, size_t K> void btas::Dcontract (const double & alpha, const DArray< NA > & a, const IVector< K > & a_contract, const DArray< NB > & b, const IVector< K > & b_contract, const double & beta, DArray< NA+NB-K-K > & c)
Convenient contraction function for DArray.
Definition at line 16 of file Dcontract.h.
References BTAS_THROW, Dgemm(), Dgemv(), Dpermute(), get_contract_jobs(), JOBMASK_A_PMUTE, JOBMASK_A_TRANS, JOBMASK_B_PMUTE, JOBMASK_B_TRANS, JOBMASK_BLAS_TYPE, NoTrans, btas::TArray< T, N >::reference(), btas::TArray< T, N >::shape(), and Trans.
Referenced by contract(), DENSE_TEST(), and Dindexed_contract().
template<size_t N> void btas::Dcopy (const DArray< N > & x, DArray< N > & y)
DCOPY: y := x.
Definition at line 26 of file Dblas.h.
References btas::TArray< T, N >::clear(), btas::TArray< T, N >::data(), btas::TArray< T, N >::resize(), btas::TArray< T, N >::shape(), and btas::TArray< T, N >::size().
Referenced by btas::DcopyArglist< N >::call(), DENSE_TEST(), Dgesv(), Dindexed_permute(), Dpermute(), and serial_SDcopy().
template<size_t NX, size_t NY> void btas::DcopyFlatten (const DArray< NX > & x, DArray< NY > & y)
DCOPY as flattened vectors: y := x.
x and y must have the same size ranks of x and y can be varied
Definition at line 40 of file Dblas.h.
References BTAS_THROW, btas::TArray< T, N >::data(), and btas::TArray< T, N >::size().
Referenced by Dgetrf(), Dreshape(), Dsyev(), and Dsygv().
template<size_t NA, size_t K> void btas::Ddiagonal (const DArray< NA > & a, const IVector< K > & d_index, DArray< NA-K+1 > & b)
Function to get diagonal elements.
Note that the order of d_index affects to the index of 'b' a(i,j,k,l) with d_index(j,l) returns b(i,j,k) = a(i,j,k,j) a(i,j,k,l) with d_index(l,j) returns b(i,k,l) = a(i,l,k,l)
Definition at line 20 of file Ddiagonal.h.
References BTAS_THROW, btas::TArray< T, N >::data(), Dreindex(), btas::TArray< T, N >::resize(), btas::TArray< T, N >::shape(), btas::TArray< T, N >::size(), and btas::TArray< T, N >::stride().
Referenced by DENSE_TEST(), and SDdiagonal().
template<size_t NA, size_t NB> void btas::Ddidm (const DArray< NA > & a, DArray< NB > & b)
Non-BLAS function: b := a(diagonal matrix) * b(general matrix)
NA <= NB
Definition at line 203 of file Dblas.h.
References BTAS_THROW, btas::TArray< T, N >::data(), btas::TArray< T, N >::shape(), and btas::TArray< T, N >::size().
Referenced by decompose(), indexed_decompose(), and SDdidm().
template<size_t NA, size_t NB> void btas::Ddimd (DArray< NA > & a, const DArray< NB > & b)
Non-BLAS function: a := a(general matrix) * b(diagonal matrix)
NB <= NA
Definition at line 183 of file Dblas.h.
References BTAS_THROW, btas::TArray< T, N >::data(), btas::TArray< T, N >::shape(), and btas::TArray< T, N >::size().
Referenced by SDdimd().
template<size_t N> double btas::Ddot (const DArray< N > & x, const DArray< N > & y)
DDOT: inner product of x and y.
Definition at line 78 of file Dblas.h.
References BTAS_THROW, btas::TArray< T, N >::data(), btas::TArray< T, N >::shape(), and btas::TArray< T, N >::size().
Referenced by DENSE_TEST(), Dorthogonalize(), and serial_SDdot().
template<size_t NA, size_t K> double btas::decompose (const DArray< NA > & a, const IVector< K > & index, DArray< NA-K+1 > & l, DArray< K+1 > & r, int D = 0)
Definition at line 136 of file decompose.h.
References _lsv_truncate(), _rsv_truncate(), Ddidm(), decompose_shape(), Dgesvd(), Dpermute(), and btas::TArray< T, N >::size().
template<size_t NA, size_t K, class Q = Quantum> double btas::decompose (const QSDArray< NA, Q > & a, const IVector< K > & index, QSDArray< NA-K+1, Q > & l, QSDArray< K+1, Q > & r, int D = 0)
Definition at line 204 of file decompose.h.
References decompose_shape(), QSDgesvd(), QSDpermute(), SDdidm(), and SDdot().
template<size_t N, size_t K> void btas::decompose_shape (const IVector< K > & index, IVector< N > & a_permute)
Definition at line 27 of file decompose.h.
References BTAS_THROW.
Referenced by decompose().
template<size_t N> void btas::Dgeev (const DArray< 2 *N-2 > & a, DArray< 1 > & wr, DArray< 1 > & wi, DArray< N > & vl, DArray< N > & vr)
Solve eigenvalue problem for real non-symmetric square matrix (NSGEP)
[(N-1) x (N-1)] square array 'a' is decomposed into [(N-1) x (1)] left/right eigenvectors and corresponding complex diagonal matrix
i.e. [ A * vr(j) = w(j) * vr(j) ] and [ vl(j)^T * A = w(j) * vl(j)^T ], where [ 'w' = 'wr' + i * 'wi' ]
Parameters
a array to be decomposed
wr real part of eigenvalues
wi imaginary part of eigenvalues
vl left eigenvectors
vr right eigenvectors
Definition at line 178 of file Dlapack.h.
References BTAS_THROW, clapack_dgeev(), ClapackCalcVector, btas::TArray< T, N >::data(), Dpermute(), btas::TArray< T, N >::resize(), btas::TArray< T, N >::shape(), btas::TArray< T, N >::size(), and transpose().
template<size_t NA, size_t NB, size_t NC> void btas::Dgemm (const BTAS_TRANSPOSE & TransA, const BTAS_TRANSPOSE & TransB, const double & alpha, const DArray< NA > & a, const DArray< NB > & b, const double & beta, DArray< NC > & c)
DGEMM: Matrix-matrix multiplication, c := alpha * a * b + beta * c.
Parameters
alpha scalar number
beta scalar number
a array to be contracted, regarded as matrix
b array to be contracted, regarded as matrix
c array to be returned, regarded as matrix
ranks to be contracted
Definition at line 153 of file Dblas.h.
References BTAS_THROW, btas::TArray< T, N >::data(), gemm_contract_shape(), NoTrans, btas::TArray< T, N >::resize(), RowMajor, btas::TArray< T, N >::shape(), and btas::TArray< T, N >::size().
Referenced by btas::DgemmArglist< NA, NB, NC >::call(), DblasWrapper(), Dcontract(), and DENSE_TEST().
template<size_t NA, size_t NB, size_t NC> void btas::Dgemv (const BTAS_TRANSPOSE & TransA, const double & alpha, const DArray< NA > & a, const DArray< NB > & b, const double & beta, DArray< NC > & c)
DGEMV: Matrix-vector multiplication, c := alphe * a * b + beta * c.
Definition at line 96 of file Dblas.h.
References BTAS_THROW, btas::TArray< T, N >::data(), gemv_contract_shape(), NoTrans, btas::TArray< T, N >::resize(), RowMajor, btas::TArray< T, N >::shape(), and btas::TArray< T, N >::size().
Referenced by btas::DgemvArglist< NA, NB, NC >::call(), DblasWrapper(), Dcontract(), and DENSE_TEST().
template<size_t NA, size_t NB, size_t NC> void btas::Dger (const double & alpha, const DArray< NA > & a, const DArray< NB > & b, DArray< NC > & c)
DGER: Rank-update / direct product, c := alpha * (a x b)
Definition at line 121 of file Dblas.h.
References BTAS_THROW, btas::TArray< T, N >::data(), ger_contract_shape(), btas::TArray< T, N >::resize(), RowMajor, btas::TArray< T, N >::shape(), and btas::TArray< T, N >::size().
Referenced by btas::DgerArglist< NA, NB, NC >::call(), and DENSE_TEST().
template<size_t M, size_t N> void btas::Dgesv (const DArray< M > & a, const DArray< N > & b, DArray< N > & x)
Solve linear equation A*x = b.
Parameters
a is [(M-N+1) x (N-1)] array viewed as a square matrix A
b is [(N-1) x (1)] array viewed as a set of input vectors B
x is a set of solutions
Definition at line 79 of file Dlapack.h.
References BTAS_THROW, clapack_dgesv(), btas::TArray< T, N >::data(), Dcopy(), Dpermute(), btas::TArray< T, N >::shape(), btas::TArray< T, N >::size(), and transpose().
template<size_t NA, size_t NU> void btas::Dgesvd (const DArray< NA > & a, DArray< 1 > & s, DArray< NU > & u, DArray< NA-NU+2 > & vt, bool calc_full_u = false, bool calc_full_vt = false)
Solve singular value decomposition.
Definition at line 306 of file Dlapack.h.
References BTAS_THROW, clapack_dgesvd(), ClapackCalcThinVector, btas::TArray< T, N >::data(), btas::TArray< T, N >::resize(), btas::TArray< T, N >::shape(), and btas::TArray< T, N >::size().
Referenced by btas::DgesvdArglist< NA, NU >::call(), decompose(), and indexed_decompose().
template<size_t M, size_t N> void btas::Dgetrf (const DArray< M+N-2 > & a, DArray< M > & l, DArray< N > & u, std::vector< int > & ipiv)
LU decomposition for general array.
i.e. compute fragmentation s.t. A = P * L * U
Parameters
a is an array viewed as a general rectangular matrix A
l is an array viewed as a lower triangular matrix L
u is an array viewed as a upper triangular matrix U
ipiv contains pivot info. corresponding permutation matrix P
Definition at line 34 of file Dlapack.h.
References BTAS_THROW, clapack_dgetrf(), btas::TArray< T, N >::data(), DcopyFlatten(), Dpermute(), btas::TArray< T, N >::resize(), btas::TArray< T, N >::shape(), and transpose().
template<size_t N> void btas::Dggev (const DArray< 2 *N-2 > & a, const DArray< 2 *N-2 > & b, DArray< 1 > & alphar, DArray< 1 > & alphai, DArray< 1 > & beta, DArray< N > & vl, DArray< N > & vr)
Solve generalized eigenvalue problem for non-symmetric real matrix pair.
i.e. [ A * vr(j) = d(j) * B * vr(j) ] and [ vl(j)^T * A = d(j) * vl(j)^T * B ] where [ d(j) = (alphar(j) + i * alphai(j)) / beta(j) ], and [ d(j+1) = (alphar(j) - i * alphai(j)) / beta(j) ] if alphai(j) is not zero
Definition at line 259 of file Dlapack.h.
References BTAS_THROW, clapack_dggev(), ClapackCalcVector, btas::TArray< T, N >::data(), Dpermute(), btas::TArray< T, N >::resize(), btas::TArray< T, N >::shape(), btas::TArray< T, N >::size(), and transpose().
template<size_t NA, size_t NB, size_t NC> void btas::Dindexed_contract (const double & alpha, const DArray< NA > & a, const IVector< NA > & a_symbols, const DArray< NB > & b, const IVector< NB > & b_symbols, const double & beta, DArray< NC > & c, const IVector< NC > & c_symbols)
Convenient indexed contraction function for DArray.
Definition at line 60 of file Dcontract.h.
References Dcontract(), Dindexed_permute(), indexed_contract_shape(), and btas::TArray< T, N >::size().
Referenced by DENSE_TEST(), and indexed_contract().
template<size_t N> void btas::Dindexed_permute (const DArray< N > & x, const IVector< N > & x_symbols, DArray< N > & y, const IVector< N > & y_symbols)
Indexed permutation for double precision real dense array.
Definition at line 44 of file Dpermute.h.
References Dcopy(), Dpermute(), and indexed_permute_shape().
Referenced by Dindexed_contract(), and indexed_permute().
template<size_t N> void btas::Dnormalize (DArray< N > & x)
Normalization.
Definition at line 240 of file Dblas.h.
References Dnrm2(), Dscal(), and mps::nrm2().
template<size_t N> double btas::Dnrm2 (const DArray< N > & x)
DNRM2: returns euclidean norm of x.
Definition at line 86 of file Dblas.h.
References btas::TArray< T, N >::data(), and btas::TArray< T, N >::size().
Referenced by Dnormalize().
template<size_t N> void btas::Dorthogonalize (const DArray< N > & x, DArray< N > & y)
Orthogonalization.
Definition at line 247 of file Dblas.h.
References Daxpy(), and Ddot().
template<size_t N> int btas::dot (const IVector< N > & v1, const IVector< N > & v2) inline
Dot product of two integer vectors.
Definition at line 200 of file TVector.h.
Referenced by btas::TArray< T, N >::at(), btas::TSubArray< T, N >::copy(), btas::TArray< T, N >::copy(), mps::dist(), mps::nrm2(), btas::TArray< T, N >::operator()(), btas::STArray< T, N >::permuted_view(), and btas::STArray< T, N >::tag().
template<> int btas::dot< 1 > (const IVector< 1 > & v1, const IVector< 1 > & v2) inline
Dot product with small overhead, specialized for N = 1.
Definition at line 208 of file TVector.h.
template<> int btas::dot< 10 > (const IVector< 10 > & v1, const IVector< 10 > & v2) inline
Dot product with small overhead, specialized for N = 10.
Definition at line 262 of file TVector.h.
template<> int btas::dot< 11 > (const IVector< 11 > & v1, const IVector< 11 > & v2) inline
Dot product with small overhead, specialized for N = 11.
Definition at line 268 of file TVector.h.
template<> int btas::dot< 12 > (const IVector< 12 > & v1, const IVector< 12 > & v2) inline
Dot product with small overhead, specialized for N = 12.
Definition at line 274 of file TVector.h.
template<> int btas::dot< 2 > (const IVector< 2 > & v1, const IVector< 2 > & v2) inline
Dot product with small overhead, specialized for N = 2.
Definition at line 214 of file TVector.h.
template<> int btas::dot< 3 > (const IVector< 3 > & v1, const IVector< 3 > & v2) inline
Dot product with small overhead, specialized for N = 3.
Definition at line 220 of file TVector.h.
template<> int btas::dot< 4 > (const IVector< 4 > & v1, const IVector< 4 > & v2) inline
Dot product with small overhead, specialized for N = 4.
Definition at line 226 of file TVector.h.
template<> int btas::dot< 5 > (const IVector< 5 > & v1, const IVector< 5 > & v2) inline
Dot product with small overhead, specialized for N = 5.
Definition at line 232 of file TVector.h.
template<> int btas::dot< 6 > (const IVector< 6 > & v1, const IVector< 6 > & v2) inline
Dot product with small overhead, specialized for N = 6.
Definition at line 238 of file TVector.h.
template<> int btas::dot< 7 > (const IVector< 7 > & v1, const IVector< 7 > & v2) inline
Dot product with small overhead, specialized for N = 7.
Definition at line 244 of file TVector.h.
template<> int btas::dot< 8 > (const IVector< 8 > & v1, const IVector< 8 > & v2) inline
Dot product with small overhead, specialized for N = 8.
Definition at line 250 of file TVector.h.
template<> int btas::dot< 9 > (const IVector< 9 > & v1, const IVector< 9 > & v2) inline
Dot product with small overhead, specialized for N = 9.
Definition at line 256 of file TVector.h.
template<size_t N> void btas::Dpermute (const DArray< N > & x, const IVector< N > & pindx, DArray< N > & y)
Permutation double precision real dense array.
Definition at line 17 of file Dpermute.h.
References BTAS_THROW, btas::TArray< T, N >::data(), Dcopy(), Dreindex(), permute_shape(), btas::TArray< T, N >::resize(), btas::TArray< T, N >::shape(), and btas::TArray< T, N >::size().
Referenced by btas::DpermuteArglist< N >::call(), Dcontract(), decompose(), DENSE_TEST(), Dgeev(), Dgesv(), Dgetrf(), Dggev(), Dindexed_permute(), Dsyev(), Dsygv(), indexed_decompose(), permute(), and serial_SDpermute().
template<size_t N> void btas::Dreindex (const double * x, double * y, const IVector< N > & xstr, const IVector< N > & yshape)
Definition at line 10 of file Dreindex.h.
References BTAS_THROW.
Referenced by Ddiagonal(), and Dpermute().
template<> void btas::Dreindex< 1 > (const double * x, double * y, const IVector< 1 > & xstr, const IVector< 1 > & yshape)
Definition at line 4 of file Dreindex.C.
template<> void btas::Dreindex< 10 > (const double * x, double * y, const IVector< 10 > & xstr, const IVector< 10 > & yshape)
Definition at line 193 of file Dreindex.C.
template<> void btas::Dreindex< 11 > (const double * x, double * y, const IVector< 11 > & xstr, const IVector< 11 > & yshape)
Definition at line 229 of file Dreindex.C.
template<> void btas::Dreindex< 12 > (const double * x, double * y, const IVector< 12 > & xstr, const IVector< 12 > & yshape)
Definition at line 268 of file Dreindex.C.
template<> void btas::Dreindex< 2 > (const double * x, double * y, const IVector< 2 > & xstr, const IVector< 2 > & yshape)
Definition at line 13 of file Dreindex.C.
template<> void btas::Dreindex< 3 > (const double * x, double * y, const IVector< 3 > & xstr, const IVector< 3 > & yshape)
Definition at line 25 of file Dreindex.C.
template<> void btas::Dreindex< 4 > (const double * x, double * y, const IVector< 4 > & xstr, const IVector< 4 > & yshape)
Definition at line 40 of file Dreindex.C.
template<> void btas::Dreindex< 5 > (const double * x, double * y, const IVector< 5 > & xstr, const IVector< 5 > & yshape)
Definition at line 58 of file Dreindex.C.
template<> void btas::Dreindex< 6 > (const double * x, double * y, const IVector< 6 > & xstr, const IVector< 6 > & yshape)
Definition at line 79 of file Dreindex.C.
template<> void btas::Dreindex< 7 > (const double * x, double * y, const IVector< 7 > & xstr, const IVector< 7 > & yshape)
Definition at line 103 of file Dreindex.C.
template<> void btas::Dreindex< 8 > (const double * x, double * y, const IVector< 8 > & xstr, const IVector< 8 > & yshape)
Definition at line 130 of file Dreindex.C.
template<> void btas::Dreindex< 9 > (const double * x, double * y, const IVector< 9 > & xstr, const IVector< 9 > & yshape)
Definition at line 160 of file Dreindex.C.
template<size_t NX, size_t NY> void btas::Dreshape (const DArray< NX > & x, const IVector< NY > & y_shape, DArray< NY > & y)
reshape rank of array
Definition at line 48 of file Dblas.h.
References DcopyFlatten(), and btas::TArray< T, N >::resize().
template<size_t N> void btas::Dscal (const double & alpha, DArray< N > & x)
DSCAL: x := alpha * x.
Definition at line 55 of file Dblas.h.
References btas::TArray< T, N >::data(), and btas::TArray< T, N >::size().
Referenced by btas::DscalArglist< N >::call(), DENSE_TEST(), Dnormalize(), and serial_SDscal().
template<size_t N> void btas::Dsyev (const DArray< 2 *N-2 > & a, DArray< 1 > & d, DArray< N > & z)
Solve eigenvalue problem for real symmetric matrix (SEP)
i.e. compute A = Z * D * Z^T
Parameters
a is [(N-1) x (N-1)] symmetric array A
d is diagonal matrix D containing eigenvalues
z is [(N-1) x (1)] unitary array Z containing eigenvectors
Definition at line 136 of file Dlapack.h.
References BTAS_THROW, clapack_dsyev(), ClapackCalcVector, ClapackUpper, btas::TArray< T, N >::data(), DcopyFlatten(), Dpermute(), btas::TArray< T, N >::resize(), btas::TArray< T, N >::shape(), btas::TArray< T, N >::size(), and transpose().
template<size_t N> void btas::Dsygv (const DArray< 2 *N-2 > & a, const DArray< 2 *N-2 > & b, DArray< 1 > & d, DArray< N > & z)
Solve generalized eigenvalue problem for real symmetric matrix.
i.e. [ A * z(j) = d(j) * B * z(j) ]
Definition at line 214 of file Dlapack.h.
References BTAS_THROW, clapack_dsygv(), ClapackCalcVector, ClapackUpper, btas::TArray< T, N >::data(), DcopyFlatten(), Dpermute(), btas::TArray< T, N >::resize(), btas::TArray< T, N >::shape(), btas::TArray< T, N >::size(), and transpose().
template<typename T , size_t NA, size_t NB, size_t NC, class Q = Quantum> double btas::f_indexbase_scale (const function< T(const TVector< Q, NA > &, const TVector< Q, NB > &, const TVector< Q, NC > &)> & f_scale, const TVector< Qshapes< Q >, NA > & a_qshape, const IVector< NA > & a_index, const TVector< Qshapes< Q >, NB > & b_qshape, const IVector< NB > & b_index, const TVector< Qshapes< Q >, NC > & c_qshape, const IVector< NC > & c_index)
Wrapper function to return Clebsch-Gordan coefficient depends on block index.
Definition at line 117 of file btas_contract_qshape.h.
template<size_t NA, size_t NB, size_t NC, class Q = Quantum> double btas::f_permuted_scale_axb (const TVector< Q, NA > & a_permuted_qindex, const IVector< NA > & a_permute, const TVector< Q, NB > & b_permuted_qindex, const IVector< NB > & b_permute, const TVector< Q, NC > & c_qindex, const function< double(const TVector< Q, NA > &, const TVector< Q, NB > &, const TVector< Q, NC > &)> & f_scale)
Definition at line 92 of file QSDcontract.h.
template<size_t NA, size_t NB, size_t NC, class Q = Quantum> double btas::f_permuted_scale_c (const TVector< Q, NA > & a_qindex, const TVector< Q, NB > & b_qindex, const TVector< Q, NC > & c_permuted_qindex, const IVector< NC > & c_permute, const function< double(const TVector< Q, NA > &, const TVector< Q, NB > &, const TVector< Q, NC > &)> & f_scale)
Definition at line 109 of file QSDcontract.h.
template<typename T > void btas::fast_add (const std::vector< T > & v1, std::vector< T > & v2)
Fast copy function for std::vector<T>
Definition at line 441 of file TVector.h.
References _fast_add().
Referenced by btas::TArray< T, N >::add().
template<typename T > void btas::fast_copy (const std::vector< T > & v1, std::vector< T > & v2)
Fast copy function for std::vector<T>
Definition at line 425 of file TVector.h.
References _fast_copy().
Referenced by btas::TArray< T, N >::copy().
template<typename T > void btas::fast_scal (const T & alpha, std::vector< T > & v)
Fast scale function for std::vector<T>
Definition at line 433 of file TVector.h.
References _fast_scal().
Referenced by btas::TArray< T, N >::scale().
template<size_t NA, size_t NB, size_t NC> void btas::gemm_contract_dshape (const BTAS_TRANSPOSE & TransA, const BTAS_TRANSPOSE & TransB, const TVector< Dshapes, NA > & a_dshape, const TVector< Dshapes, NB > & b_dshape, TVector< Dshapes, NC > & c_dshape)
Definition at line 54 of file btas_contract_dshape.h.
References _btas_contract_allowed(), BTAS_THROW, and NoTrans.
Referenced by QSDgemm(), and SDgemm().
template<size_t NA, size_t NB, size_t NC, class Q = Quantum> void btas::gemm_contract_qshape (const BTAS_TRANSPOSE & TransA, const BTAS_TRANSPOSE & TransB, const Q & a_qnum, const TVector< Qshapes< Q >, NA > & a_qshape, const Q & b_qnum, const TVector< Qshapes< Q >, NB > & b_qshape, Q & c_qnum, TVector< Qshapes< Q >, NC > & c_qshape)
Definition at line 61 of file btas_contract_qshape.h.
References BTAS_THROW, ConjTrans, and NoTrans.
Referenced by QSDgemm().
template<size_t NA, size_t NB, size_t NC, size_t K> void btas::gemm_contract_shape (const BTAS_TRANSPOSE & TransA, const BTAS_TRANSPOSE & TransB, const IVector< NA > & a_shape, const IVector< NB > & b_shape, IVector< K > & contracts, IVector< NC > & c_shape) inline
Definition at line 48 of file btas_contract_shape.h.
References BTAS_THROW, and NoTrans.
Referenced by Dgemm().
template<size_t NA, size_t NB, size_t NC> void btas::gemv_contract_dshape (const BTAS_TRANSPOSE & TransA, const TVector< Dshapes, NA > & a_dshape, const TVector< Dshapes, NB > & b_dshape, TVector< Dshapes, NC > & c_dshape)
Definition at line 25 of file btas_contract_dshape.h.
References _btas_contract_allowed(), BTAS_THROW, and NoTrans.
Referenced by QSDgemv(), and SDgemv().
template<size_t NA, size_t NB, size_t NC, class Q = Quantum> void btas::gemv_contract_qshape (const BTAS_TRANSPOSE & TransA, const Q & a_qnum, const TVector< Qshapes< Q >, NA > & a_qshape, const Q & b_qnum, const TVector< Qshapes< Q >, NB > & b_qshape, Q & c_qnum, TVector< Qshapes< Q >, NC > & c_qshape)
Definition at line 19 of file btas_contract_qshape.h.
References BTAS_THROW, ConjTrans, and NoTrans.
Referenced by QSDgemv().
template<size_t NA, size_t NB, size_t NC> void btas::gemv_contract_shape (const BTAS_TRANSPOSE & TransA, const IVector< NA > & a_shape, const IVector< NB > & b_shape, IVector< NC > & c_shape) inline
Definition at line 17 of file btas_contract_shape.h.
References BTAS_THROW, and NoTrans.
Referenced by Dgemv().
template<size_t NA, size_t NB, size_t NC> void btas::ger_contract_dshape (const TVector< Dshapes, NA > & a_dshape, const TVector< Dshapes, NB > & b_dshape, TVector< Dshapes, NC > & c_dshape)
Definition at line 44 of file btas_contract_dshape.h.
Referenced by QSDger(), and SDger().
template<size_t NA, size_t NB, size_t NC, class Q = Quantum> void btas::ger_contract_qshape (const Q & a_qnum, const TVector< Qshapes< Q >, NA > & a_qshape, const Q & b_qnum, const TVector< Qshapes< Q >, NB > & b_qshape, Q & c_qnum, TVector< Qshapes< Q >, NC > & c_qshape)
Definition at line 50 of file btas_contract_qshape.h.
Referenced by QSDger().
template<size_t NA, size_t NB, size_t NC> void btas::ger_contract_shape (const IVector< NA > & a_shape, const IVector< NB > & b_shape, IVector< NC > & c_shape) inline
Definition at line 37 of file btas_contract_shape.h.
References BTAS_THROW.
Referenced by Dger().
template<size_t NA, size_t NB, size_t K> unsigned int btas::get_contract_jobs (const IVector< NA > & a_shape, const IVector< K > & a_contract, IVector< NA > & a_permute, const IVector< NB > & b_shape, const IVector< K > & b_contract, IVector< NB > & b_permute)
job_type = 2 calls GEMM by default
job_type = 1 calls GEMV(Trans, B, A, C)
Definition at line 98 of file btas_contract_shape.h.
References JOBMASK_A_PMUTE, JOBMASK_B_PMUTE, and JOBMASK_B_TRANS.
Referenced by Dcontract(), QSDcontract(), and SDcontract().
template<size_t NA, size_t NB, size_t NC> void btas::indexed_contract (const double & alpha, const DArray< NA > & a, const IVector< NA > & a_symbols, const DArray< NB > & b, const IVector< NB > & b_symbols, const double & beta, DArray< NC > & c, const IVector< NC > & c_symbols) inline
Definition at line 21 of file contract.h.
References Dindexed_contract().
template<size_t NA, size_t NB, size_t NC> void btas::indexed_contract (const double & alpha, const SDArray< NA > & a, const IVector< NA > & a_symbols, const SDArray< NB > & b, const IVector< NB > & b_symbols, const double & beta, SDArray< NC > & c, const IVector< NC > & c_symbols) inline
Definition at line 39 of file contract.h.
References SDindexed_contract().
template<size_t NA, size_t NB, size_t NC, class Q = Quantum> void btas::indexed_contract (const double & alpha, const QSDArray< NA, Q > & a, const IVector< NA > & a_symbols, const QSDArray< NB, Q > & b, const IVector< NB > & b_symbols, const double & beta, QSDArray< NC, Q > & c, const IVector< NC > & c_symbols) inline
Definition at line 57 of file contract.h.
References QSDindexed_contract().
template<size_t NA, size_t NB, size_t K> void btas::indexed_contract_shape (const IVector< NA > & a_symbols, IVector< K > & a_contract, const IVector< NB > & b_symbols, IVector< K > & b_contract, IVector< NA+NB-K-K > & axb_symbols)
Definition at line 142 of file btas_contract_shape.h.
References BTAS_THROW.
Referenced by Dindexed_contract(), QSDindexed_contract(), and SDindexed_contract().
template<size_t NA, size_t NL> double btas::indexed_decompose (const DArray< NA > & a, const IVector< NA > & a_symbols, DArray< NL > & l, const IVector< NL > & l_symbols, DArray< NA-NL+2 > & r, const IVector< NA-NL+2 > & r_symbols, int D = 0)
Definition at line 166 of file decompose.h.
References _lsv_truncate(), _rsv_truncate(), Ddidm(), Dgesvd(), Dpermute(), indexed_decompose_shape(), and btas::TArray< T, N >::size().
template<size_t NA, size_t NL, class Q = Quantum> double btas::indexed_decompose (const QSDArray< NA, Q > & a, const IVector< NA > & a_symbols, QSDArray< NL, Q > & l, const IVector< NL > & l_symbols, QSDArray< NA-NL+2, Q > & r, const IVector< NA-NL+2 > & r_symbols, int D = 0)
Definition at line 226 of file decompose.h.
References indexed_decompose_shape(), QSDgesvd(), QSDpermute(), SDdidm(), and SDdot().
template<size_t NA, size_t NL> void btas::indexed_decompose_shape (const IVector< NA > & a_symbols, const IVector< NL > & l_symbols, const IVector< NA-NL+2 > & r_symbols, IVector< NA > & a_permute, IVector< NL > & l_permute, IVector< NA-NL+2 > & r_permute)
Definition at line 44 of file decompose.h.
References BTAS_THROW.
Referenced by indexed_decompose().
template<size_t N> void btas::indexed_permute (const DArray< N > & x, const IVector< N > & x_symbols, DArray< N > & y, const IVector< N > & y_symbols) inline
Definition at line 19 of file permute.h.
References Dindexed_permute().
template<size_t N> void btas::indexed_permute (const SDArray< N > & x, const IVector< N > & x_symbols, SDArray< N > & y, const IVector< N > & y_symbols) inline
Definition at line 34 of file permute.h.
References SDindexed_permute().
template<size_t N, class Q = Quantum> void btas::indexed_permute (const QSDArray< N, Q > & x, const IVector< N > & x_symbols, QSDArray< N, Q > & y, const IVector< N > & y_symbols) inline
Definition at line 49 of file permute.h.
References QSDindexed_permute().
template<size_t N> void btas::indexed_permute_shape (const IVector< N > & x_symbols, const IVector< N > & y_symbols, IVector< N > & pindex)
Definition at line 33 of file btas_permute_shape.h.
References BTAS_THROW.
Referenced by Dindexed_permute(), QSDindexed_contract(), QSDindexed_permute(), and SDindexed_permute().
template<typename T > TVector<T, 1> btas::make_array (T v01) inline
Convenient TVector constructor for N = 1.
Definition at line 68 of file TVector.h.
Referenced by mps::create(), mps::product_state(), QSDgesvd(), and QSPARSE_TEST().
template<typename T > TVector<T, 2> btas::make_array (T v01, T v02) inline
Convenient TVector constructor for N = 2.
Definition at line 75 of file TVector.h.
template<typename T > TVector<T, 3> btas::make_array (T v01, T v02, T v03) inline
Convenient TVector constructor for N = 3.
Definition at line 82 of file TVector.h.
template<typename T > TVector<T, 4> btas::make_array (T v01, T v02, T v03, T v04) inline
Convenient TVector constructor for N = 4.
Definition at line 89 of file TVector.h.
template<typename T > TVector<T, 5> btas::make_array (T v01, T v02, T v03, T v04, T v05) inline
Convenient TVector constructor for N = 5.
Definition at line 96 of file TVector.h.
template<typename T > TVector<T, 6> btas::make_array (T v01, T v02, T v03, T v04, T v05, T v06) inline
Convenient TVector constructor for N = 6.
Definition at line 103 of file TVector.h.
template<typename T > TVector<T, 7> btas::make_array (T v01, T v02, T v03, T v04, T v05, T v06, T v07) inline
Convenient TVector constructor for N = 7.
Definition at line 110 of file TVector.h.
template<typename T > TVector<T, 8> btas::make_array (T v01, T v02, T v03, T v04, T v05, T v06, T v07, T v08) inline
Convenient TVector constructor for N = 8.
Definition at line 117 of file TVector.h.
template<typename T > TVector<T, 9> btas::make_array (T v01, T v02, T v03, T v04, T v05, T v06, T v07, T v08, T v09) inline
Convenient TVector constructor for N = 9.
Definition at line 124 of file TVector.h.
template<typename T > TVector<T,10> btas::make_array (T v01, T v02, T v03, T v04, T v05, T v06, T v07, T v08, T v09, T v10) inline
Convenient TVector constructor for N = 10.
Definition at line 131 of file TVector.h.
template<typename T > TVector<T,11> btas::make_array (T v01, T v02, T v03, T v04, T v05, T v06, T v07, T v08, T v09, T v10, T v11) inline
Convenient TVector constructor for N = 11.
Definition at line 138 of file TVector.h.
template<typename T > TVector<T,12> btas::make_array (T v01, T v02, T v03, T v04, T v05, T v06, T v07, T v08, T v09, T v10, T v11, T v12) inline
Convenient TVector constructor for N = 12.
Definition at line 145 of file TVector.h.
template<typename T , size_t N> TVector<T, N> btas::operator& (const TVector< std::vector< T >, N > & vec, const IVector< N > & index) inline
Abstract TVector<T, N> from TVector<std::vector<T>, N> by index.
e.g. index = { i, j, k, l } return { vec[0][i], vec[1][j], vec[2][k], vec[3][l] }
Definition at line 178 of file TVector.h.
template<typename T , size_t N> TVector<T, N> btas::operator& (const IVector< N > & index, const TVector< std::vector< T >, N > & vec) inline
Abstract TVector<T, N> from TVector<std::vector<T>, N> by index.
e.g. index = { i, j, k, l } return { vec[0][i], vec[1][j], vec[2][k], vec[3][l] }
Definition at line 188 of file TVector.h.
template<size_t N, class Q > Q btas::operator* (const TVector< Qshapes< Q >, N > & vec, const IVector< N > & index) inline
Indexed product of TVector<Qshapes<Q>, N>
e.g. index = { i, j, k, l } return vec[0][i] * vec[1][j] * vec[2][k] * vec[3][l]
Definition at line 109 of file Qshapes.h.
template<size_t N, class Q > Q btas::operator* (const IVector< N > & index, const TVector< Qshapes< Q >, N > & vec) inline
Indexed product of TVector<Qshapes<Q>, N>
e.g. index = { i, j, k, l } return vec[0][i] * vec[1][j] * vec[2][k] * vec[3][l]
Definition at line 119 of file Qshapes.h.
template<typename T , size_t N> T btas::operator* (const TVector< std::vector< T >, N > & vec, const IVector< N > & index) inline
Indexed product of TVector<std::vector<T>, N>
e.g. index = { i, j, k, l } return vec[0][i] * vec[1][j] * vec[2][k] * vec[3][l]
Definition at line 158 of file TVector.h.
template<typename T , size_t N> T btas::operator* (const IVector< N > & index, const TVector< std::vector< T >, N > & vec) inline
Indexed product of TVector<std::vector<T>, N>
e.g. index = { i, j, k, l } return vec[0][i] * vec[1][j] * vec[2][k] * vec[3][l]
Definition at line 168 of file TVector.h.
Dshapes btas::operator* (const Dshapes & ds1, const Dshapes & ds2) inline
Direct product of Dshapes.
Definition at line 399 of file TVector.h.
template<class Arglist > void btas::parallel_call (std::vector< Arglist > & task_list)
Definition at line 246 of file Targlist.h.
Referenced by thread_QSDgesvd(), thread_SDaxpy(), thread_SDcopy(), thread_SDgemm(), thread_SDgemv(), thread_SDger(), thread_SDpermute(), and thread_SDscal().
template<size_t N> void btas::permute (const DArray< N > & x, const IVector< N > & index, DArray< N > & y) inline
Definition at line 12 of file permute.h.
References Dpermute().
template<size_t N> void btas::permute (const SDArray< N > & x, const IVector< N > & index, SDArray< N > & y) inline
Definition at line 27 of file permute.h.
References SDpermute().
template<size_t N, class Q = Quantum> void btas::permute (const QSDArray< N, Q > & x, const IVector< N > & index, QSDArray< N, Q > & y) inline
Definition at line 42 of file permute.h.
References QSDpermute().
template<typename T , size_t N> TVector<T, N> btas::permute (const TVector< T, N > & vec, const IVector< N > & pindex)
Return permuted vector.
Definition at line 388 of file TVector.h.
Referenced by permute_shape(), btas::STArray< T, N >::permuted_view(), QSDpermute(), SDpermute(), serial_SDpermute(), and thread_SDpermute().
template<size_t N> void btas::permute_shape (const IVector< N > & pindex, const IVector< N > & xshape, IVector< N > & xstrides, IVector< N > & yshape)
pindex (j, k, i) means, to compute y(I, J, K) := x(j, k, i) respected to MATLAB format
Definition at line 17 of file btas_permute_shape.h.
References permute().
Referenced by Dpermute().
template<size_t N, class Q = Quantum> void btas::QSDaxpy (const double & alpha, const QSDArray< N, Q > & x, QSDArray< N, Q > & y)
DAXPY.
Definition at line 73 of file QSDblas.h.
References BTAS_THROW, btas::STArray< T, N >::dshape(), btas::QSTArray< T, N, Q >::q(), btas::QSTArray< T, N, Q >::qshape(), btas::QSTArray< T, N, Q >::resize(), serial_SDaxpy(), btas::STArray< T, N >::size(), and thread_SDaxpy().
Referenced by QSDorthogonalize().
template<size_t NA, size_t NB, size_t NC, size_t K, class Q = Quantum> void btas::QSDcontract (const double & alpha, const QSDArray< NA, Q > & a, const IVector< K > & a_contract, const QSDArray< NB, Q > & b, const IVector< K > & b_contract, const double & beta, QSDArray< NC, Q > & c)
Definition at line 20 of file QSDcontract.h.
References BTAS_THROW, get_contract_jobs(), JOBMASK_A_PMUTE, JOBMASK_A_TRANS, JOBMASK_B_PMUTE, JOBMASK_B_TRANS, JOBMASK_BLAS_TYPE, NoTrans, QSDgemm(), QSDgemv(), QSDpermute(), btas::QSTArray< T, N, Q >::reference(), btas::STArray< T, N >::shape(), and Trans.
Referenced by mps::compress(), contract(), mps::dot(), QSDindexed_contract(), and QSPARSE_TEST().
template<size_t NA, size_t NB, size_t NC, size_t K, class Q = Quantum> void btas::QSDcontract (const function< double(const TVector< Q, NA > &, const TVector< Q, NB > &, const TVector< Q, NC > &)> & f_scale, const double & alpha, const QSDArray< NA, Q > & a, const IVector< K > & a_contract, const QSDArray< NB, Q > & b, const IVector< K > & b_contract, const double & beta, QSDArray< NC, Q > & c)
Definition at line 123 of file QSDcontract.h.
References BTAS_THROW, get_contract_jobs(), JOBMASK_A_PMUTE, JOBMASK_A_TRANS, JOBMASK_B_PMUTE, JOBMASK_B_TRANS, JOBMASK_BLAS_TYPE, NoTrans, QSDgemm(), QSDgemv(), QSDpermute(), btas::QSTArray< T, N, Q >::reference(), btas::STArray< T, N >::shape(), and Trans.
template<size_t N, class Q = Quantum> void btas::QSDcopy (const QSDArray< N, Q > & x, QSDArray< N, Q > & y)
DCOPY.
Definition at line 27 of file QSDblas.h.
References btas::STArray< T, N >::dshape(), btas::QSTArray< T, N, Q >::q(), btas::QSTArray< T, N, Q >::qshape(), btas::QSTArray< T, N, Q >::resize(), serial_SDcopy(), and thread_SDcopy().
Referenced by mps::compress(), QSDindexed_permute(), and QSDpermute().
template<size_t N, class Q = Quantum> double btas::QSDdotc (const QSDArray< N, Q > & x, const QSDArray< N, Q > & y)
DDOT(C): X^H * Y Taking hermitian conjugate of x upon contraction (checking quantum number process only differs from QSDdotu)
Definition at line 61 of file QSDblas.h.
References BTAS_THROW, btas::QSTArray< T, N, Q >::q(), btas::QSTArray< T, N, Q >::qshape(), and serial_SDdot().
Referenced by mps::compress(), QSDnormalize(), QSDorthogonalize(), and QSPARSE_TEST().
template<size_t N, class Q = Quantum> double btas::QSDdotu (const QSDArray< N, Q > & x, const QSDArray< N, Q > & y)
DDOT(U): X^T * Y.
Definition at line 48 of file QSDblas.h.
References BTAS_THROW, btas::QSTArray< T, N, Q >::q(), btas::QSTArray< T, N, Q >::qshape(), and serial_SDdot().
template<size_t N, class Q = Quantum> void btas::QSDdsum (const QSDArray< N, Q > & x, const QSDArray< N, Q > & y, QSDArray< N, Q > & z) inline
Definition at line 18 of file QSDArray.h.
References QSTdsum().
Referenced by mps::add().
template<size_t N, size_t K, class Q = Quantum> void btas::QSDdsum (const QSDArray< N, Q > & x, const QSDArray< N, Q > & y, const IVector< K > & trace_index, QSDArray< N, Q > & z) inline
Definition at line 22 of file QSDArray.h.
References QSTdsum().
template<size_t MR, size_t N, class Q = Quantum> void btas::QSDexpand (const QSTmergeInfo< MR, Q > & rows_info, const QSDArray< 1+N-MR, Q > & a, QSDArray< N, Q > & b) inline
Definition at line 38 of file QSDmerge.h.
Referenced by QSDgesvd().
template<size_t N, size_t MC, class Q = Quantum> void btas::QSDexpand (const QSDArray< N-MC+1, Q > & a, const QSTmergeInfo< MC, Q > & cols_info, QSDArray< N, Q > & b) inline
Definition at line 45 of file QSDmerge.h.
template<size_t MR, size_t MC, class Q = Quantum> void btas::QSDexpand (const QSTmergeInfo< MR, Q > & rows_info, const QSDArray< 2, Q > & a, const QSTmergeInfo< MC, Q > & cols_info, QSDArray< MR+MC, Q > & b) inline
Definition at line 52 of file QSDmerge.h.
template<size_t NA, size_t NB, size_t NC, class Q = Quantum> void btas::QSDgemm (const BTAS_TRANSPOSE & TransA, const BTAS_TRANSPOSE & TransB, const double & alpha, const QSDArray< NA, Q > & a, const QSDArray< NB, Q > & b, const double & beta, QSDArray< NC, Q > & c)
Definition at line 163 of file QSDblas.h.
References BTAS_THROW, btas::STArray< T, N >::dshape(), gemm_contract_dshape(), gemm_contract_qshape(), NoTrans, btas::QSTArray< T, N, Q >::q(), btas::QSTArray< T, N, Q >::qshape(), btas::QSTArray< T, N, Q >::resize(), SDscal(), btas::STArray< T, N >::size(), thread_SDgemm(), and btas::STArray< T, N >::transposed_view().
Referenced by QSDcontract(), and QSPARSE_TEST().
template<size_t NA, size_t NB, size_t NC, class Q = Quantum> void btas::QSDgemm (const function< double(const TVector< Q, NA > &, const TVector< Q, NB > &, const TVector< Q, NC > &)> & f_scale, const BTAS_TRANSPOSE & TransA, const BTAS_TRANSPOSE & TransB, const double & alpha, const QSDArray< NA > & a, const QSDArray< NB > & b, const double & beta, QSDArray< NC > & c)
Definition at line 288 of file QSDblas.h.
References BTAS_THROW, btas::STArray< T, N >::dshape(), gemm_contract_dshape(), gemm_contract_qshape(), NoTrans, btas::QSTArray< T, N, Q >::q(), btas::QSTArray< T, N, Q >::qshape(), btas::QSTArray< T, N, Q >::resize(), SDscal(), btas::STArray< T, N >::size(), thread_SDgemm(), transpose(), and btas::STArray< T, N >::transposed_view().
template<size_t NA, size_t NB, size_t NC, class Q = Quantum> void btas::QSDgemv (const BTAS_TRANSPOSE & TransA, const double & alpha, const QSDArray< NA, Q > & a, const QSDArray< NB, Q > & b, const double & beta, QSDArray< NC, Q > & c)
DGEMV.
Definition at line 100 of file QSDblas.h.
References BTAS_THROW, btas::STArray< T, N >::dshape(), gemv_contract_dshape(), gemv_contract_qshape(), NoTrans, btas::QSTArray< T, N, Q >::q(), btas::QSTArray< T, N, Q >::qshape(), btas::QSTArray< T, N, Q >::resize(), SDscal(), btas::STArray< T, N >::size(), thread_SDgemv(), and btas::STArray< T, N >::transposed_view().
Referenced by QSDcontract(), and QSPARSE_TEST().
template<size_t NA, size_t NB, size_t NC, class Q = Quantum> void btas::QSDgemv (const function< double(const TVector< Q, NA > &, const TVector< Q, NB > &, const TVector< Q, NC > &)> & f_scale, const BTAS_TRANSPOSE & TransA, const double & alpha, const QSDArray< NA > & a, const QSDArray< NB > & b, const double & beta, QSDArray< NC > & c)
Definition at line 211 of file QSDblas.h.
References BTAS_THROW, btas::STArray< T, N >::dshape(), gemv_contract_dshape(), gemv_contract_qshape(), NoTrans, btas::QSTArray< T, N, Q >::q(), btas::QSTArray< T, N, Q >::qshape(), btas::QSTArray< T, N, Q >::resize(), SDscal(), btas::STArray< T, N >::size(), thread_SDgemv(), transpose(), and btas::STArray< T, N >::transposed_view().
template<size_t NA, size_t NB, size_t NC, class Q = Quantum> void btas::QSDger (const double & alpha, const QSDArray< NA, Q > & a, const QSDArray< NB, Q > & b, QSDArray< NC, Q > & c)
DGER.
Definition at line 133 of file QSDblas.h.
References BTAS_THROW, btas::STArray< T, N >::dshape(), ger_contract_dshape(), ger_contract_qshape(), btas::QSTArray< T, N, Q >::q(), btas::QSTArray< T, N, Q >::qshape(), btas::QSTArray< T, N, Q >::resize(), btas::STArray< T, N >::size(), and thread_SDger().
Referenced by QSPARSE_TEST().
template<size_t NA, size_t NB, size_t NC, class Q = Quantum> void btas::QSDger (const function< double(const TVector< Q, NA > &, const TVector< Q, NB > &, const TVector< Q, NC > &)> & f_scale, const double & alpha, const QSDArray< NA > & a, const QSDArray< NB > & b, QSDArray< NC > & c)
Definition at line 253 of file QSDblas.h.
References BTAS_THROW, btas::STArray< T, N >::dshape(), ger_contract_dshape(), ger_contract_qshape(), btas::QSTArray< T, N, Q >::q(), btas::QSTArray< T, N, Q >::qshape(), btas::QSTArray< T, N, Q >::resize(), btas::STArray< T, N >::size(), and thread_SDger().
template<size_t NA, size_t NU, class Q = Quantum> double btas::QSDgesvd (const BTAS_ARROW_DIRECTION & ArrowDir, const QSDArray< NA, Q > & a, SDArray< 1 > & s, QSDArray< NU, Q > & u, QSDArray< NA-NU+2, Q > & vt, int Dim = 0, double Tol = 1.0)
Thin Singular Value Decomposition.
If Dim = 0, all non-zero singular values (>= 1.0e-16) are kept If Dim > 0, only Dim number of singular values are kept If Dim < 0, discards singular values less than Tol x 10^(Dim)
Returns total discarded norm (or density weights): sum_{i > Dim} S(i)^2
Definition at line 83 of file QSDlapack.h.
References btas::STArray< T, N >::begin(), btas::STArray< T, N >::check_dshape(), btas::QSTArray< T, N, Q >::clear(), btas::STArray< T, N >::clear(), btas::STArray< T, N >::dshape(), btas::TArray< T, N >::end(), btas::STArray< T, N >::end(), btas::STArray< T, N >::find(), LeftArrow, make_array(), btas::QSTArray< T, N, Q >::q(), QSDexpand(), QSDmerge(), btas::QSTArray< T, N, Q >::qshape(), btas::QSTmergeInfo< N, Q >::qshape_merged(), btas::STArray< T, N >::reserve(), btas::QSTArray< T, N, Q >::resize(), btas::STArray< T, N >::resize(), SDcopy(), shape(), btas::QSTArray< T, N, Q >::subarray(), btas::STArray< T, N >::subarray(), and thread_QSDgesvd().
Referenced by mps::compress(), decompose(), indexed_decompose(), and QSPARSE_TEST().
template<size_t NA, size_t NU, class Q = Quantum> double btas::QSDgesvd (const BTAS_ARROW_DIRECTION & ArrowDir, const QSDArray< NA, Q > & a, SDArray< 1 > & s_nz, SDArray< 1 > & s_rm, bool calc_full_u, QSDArray< NU, Q > & u_nz, QSDArray< NU, Q > & u_rm, bool calc_full_vt, QSDArray< NA-NU+2, Q > & vt_nz, QSDArray< NA-NU+2, Q > & vt_rm, int Dim = 0, double Tol = 1.0)
Full SVD.
Parameters
s_rm removed singular values
u_rm null space of left singular vectors
vt_rm null space of right singular vectors
Definition at line 235 of file QSDlapack.h.
References btas::STArray< T, N >::begin(), btas::STArray< T, N >::check_dshape(), btas::QSTArray< T, N, Q >::clear(), btas::STArray< T, N >::clear(), btas::STArray< T, N >::dshape(), btas::TArray< T, N >::end(), btas::STArray< T, N >::end(), btas::STArray< T, N >::find(), LeftArrow, make_array(), btas::QSTArray< T, N, Q >::q(), QSDexpand(), QSDmerge(), btas::QSTArray< T, N, Q >::qshape(), btas::QSTmergeInfo< N, Q >::qshape_merged(), btas::STArray< T, N >::reserve(), btas::QSTArray< T, N, Q >::resize(), btas::STArray< T, N >::resize(), SDcopy(), SDdot(), shape(), btas::STArray< T, N >::shape(), btas::QSTArray< T, N, Q >::subarray(), btas::STArray< T, N >::subarray(), and thread_QSDgesvd().
template<size_t NA, size_t NB, size_t NC, class Q = Quantum> void btas::QSDindexed_contract (const double & alpha, const QSDArray< NA, Q > & a, const IVector< NA > & a_symbols, const QSDArray< NB, Q > & b, const IVector< NB > & b_symbols, const double & beta, QSDArray< NC, Q > & c, const IVector< NC > & c_symbols)
Definition at line 62 of file QSDcontract.h.
References indexed_contract_shape(), QSDcontract(), QSDindexed_permute(), and btas::STArray< T, N >::size().
Referenced by mps::dot(), mps::gemm(), mps::gemv(), indexed_contract(), and mps::inprod().
template<size_t NA, size_t NB, size_t NC, class Q = Quantum> void btas::QSDindexed_contract (const function< double(const TVector< Q, NA > &, const TVector< Q, NB > &, const TVector< Q, NC > &)> & f_scale, const double & alpha, const QSDArray< NA, Q > & a, const IVector< NA > & a_symbols, const QSDArray< NB, Q > & b, const IVector< NB > & b_symbols, const double & beta, QSDArray< NC, Q > & c, const IVector< NC > & c_symbols)
Definition at line 173 of file QSDcontract.h.
References indexed_contract_shape(), indexed_permute_shape(), QSDcontract(), QSDindexed_permute(), QSDpermute(), and btas::STArray< T, N >::size().
template<size_t N, class Q = Quantum> void btas::QSDindexed_permute (const QSDArray< N, Q > & x, const IVector< N > & x_symbols, QSDArray< N, Q > & y, const IVector< N > & y_symbols)
Definition at line 42 of file QSDpermute.h.
References indexed_permute_shape(), QSDcopy(), and QSDpermute().
Referenced by indexed_permute(), and QSDindexed_contract().
template<size_t MR, size_t N, class Q = Quantum> void btas::QSDmerge (const QSTmergeInfo< MR, Q > & rows_info, const QSDArray< N, Q > & a, QSDArray< 1+N-MR, Q > & b) inline
Definition at line 17 of file QSDmerge.h.
Referenced by QSDgesvd(), and QSPARSE_TEST().
template<size_t N, size_t MC, class Q = Quantum> void btas::QSDmerge (const QSDArray< N, Q > & a, const QSTmergeInfo< MC, Q > & cols_info, QSDArray< N-MC+1, Q > & b) inline
Definition at line 24 of file QSDmerge.h.
template<size_t MR, size_t MC, class Q = Quantum> void btas::QSDmerge (const QSTmergeInfo< MR, Q > & rows_info, const QSDArray< MR+MC, Q > & a, const QSTmergeInfo< MC, Q > & cols_info, QSDArray< 2, Q > & b) inline
Definition at line 31 of file QSDmerge.h.
template<size_t N, class Q = Quantum> void btas::QSDnormalize (QSDArray< N, Q > & x)
Normalization.
Definition at line 349 of file QSDblas.h.
References QSDdotc(), and QSDscal().
template<size_t N, class Q = Quantum> void btas::QSDorthogonalize (const QSDArray< N, Q > & x, QSDArray< N, Q > & y)
Orthogonalization.
Definition at line 356 of file QSDblas.h.
References QSDaxpy(), and QSDdotc().
template<size_t N, class Q = Quantum> void btas::QSDpermute (const QSDArray< N, Q > & x, const IVector< N > & pindex, QSDArray< N, Q > & y)
Definition at line 21 of file QSDpermute.h.
References BTAS_THROW, btas::STArray< T, N >::dshape(), permute(), btas::QSTArray< T, N, Q >::q(), QSDcopy(), btas::QSTArray< T, N, Q >::qshape(), btas::QSTArray< T, N, Q >::resize(), serial_SDpermute(), and thread_SDpermute().
Referenced by decompose(), indexed_decompose(), permute(), QSDcontract(), QSDindexed_contract(), and QSDindexed_permute().
template<size_t N, class Q = Quantum> void btas::QSDscal (const double & alpha, QSDArray< N, Q > & x)
DSCAL.
Definition at line 40 of file QSDblas.h.
References SDscal().
Referenced by mps::compress(), QSDnormalize(), QSPARSE_TEST(), and mps::scal().
template<typename T , size_t N, class Q = Quantum> void btas::QSTdsum (const QSTArray< T, N, Q > & x, const QSTArray< T, N, Q > & y, QSTArray< T, N, Q > & z)
Direct sum of arrays X and Y, adding to Z.
E.g.) Z = X (+) Y : N = 2 | x x | | x x 0 0 0 | | x x | (+) = | x x 0 0 0 | | y y y | | 0 0 y y y |
Definition at line 18 of file QSTdsum.h.
References BTAS_THROW, btas::STArray< T, N >::dshape(), btas::QSTArray< T, N, Q >::q(), btas::QSTArray< T, N, Q >::qshape(), btas::QSTArray< T, N, Q >::resize(), and btas::STArray< T, N >::size().
Referenced by QSDdsum(), and QSPARSE_TEST().
template<typename T , size_t N, size_t K, class Q = Quantum> void btas::QSTdsum (const QSTArray< T, N, Q > & x, const QSTArray< T, N, Q > & y, const IVector< K > & trace_index, QSTArray< T, N, Q > & z)
Partial direct sum of arrays X and Y, adding to Z.
E.g.) Z = X (+) Y with trace index = { 0 } : N = 2, K = 1 | x x | | y y y | | x x y y y | | x x | (+) | y y y | = | x x y y y | | x x | | y y y | | x x y y y |
Note that sizes of trace indices must be the same between two arrays
Definition at line 51 of file QSTdsum.h.
References BTAS_THROW, btas::STArray< T, N >::dshape(), btas::QSTArray< T, N, Q >::q(), btas::QSTArray< T, N, Q >::qshape(), btas::QSTArray< T, N, Q >::resize(), and btas::STArray< T, N >::size().
template<typename T , size_t MR, size_t N, class Q = Quantum> void btas::QSTexpand (const QSTmergeInfo< MR, Q > & rows_info, const QSTArray< T, 1+N-MR, Q > & a, QSTArray< T, N, Q > & b)
Expanding row ranks.
Row-expand: { Rows-info(i,j <-> r), A(r,k,l) } -> B(i,j,k,l)
Definition at line 219 of file QSTmerge.h.
References btas::STArray< T, N >::begin(), btas::QSTmergeInfo< N, Q >::dshape(), btas::STArray< T, N >::dshape(), btas::QSTmergeInfo< N, Q >::dshape_packed(), btas::STArray< T, N >::end(), btas::QSTmergeInfo< N, Q >::equal_range(), btas::QSTArray< T, N, Q >::q(), btas::QSTmergeInfo< N, Q >::qshape(), btas::QSTArray< T, N, Q >::qshape(), btas::STArray< T, N >::reserve(), btas::QSTArray< T, N, Q >::resize(), btas::TArray< T, N >::shape(), btas::STArray< T, N >::stride(), and btas::TArray< T, N >::subarray().
template<typename T , size_t N, size_t MC, class Q = Quantum> void btas::QSTexpand (const QSTArray< T, N-MC+1, Q > & a, const QSTmergeInfo< MC, Q > & cols_info, QSTArray< T, N, Q > & b)
Expanding col ranks.
Column-expand: { A(i,j,c), Cols-info(k,l <-> c) } -> B(i,j,k,l)
Definition at line 267 of file QSTmerge.h.
References btas::STArray< T, N >::begin(), btas::QSTmergeInfo< N, Q >::dshape(), btas::STArray< T, N >::dshape(), btas::QSTmergeInfo< N, Q >::dshape_packed(), btas::STArray< T, N >::end(), btas::QSTmergeInfo< N, Q >::equal_range(), btas::QSTArray< T, N, Q >::q(), btas::QSTmergeInfo< N, Q >::qshape(), btas::QSTArray< T, N, Q >::qshape(), btas::STArray< T, N >::reserve(), btas::QSTArray< T, N, Q >::resize(), btas::TArray< T, N >::shape(), btas::STArray< T, N >::stride(), and btas::TArray< T, N >::subarray().
template<typename T , size_t MR, size_t MC, class Q = Quantum> void btas::QSTexpand (const QSTmergeInfo< MR, Q > & rows_info, const QSTArray< T, 2, Q > & a, const QSTmergeInfo< MC, Q > & cols_info, QSTArray< T, MR+MC, Q > & b)
Expanding row and col of matrix.
Row/Column-expand: { Rows-info(i,j <-> r), A(r,c), Cols-info(k,l <-> c) } -> B(i,j,k,l)
Definition at line 315 of file QSTmerge.h.
References btas::STArray< T, N >::begin(), btas::QSTmergeInfo< N, Q >::dshape(), btas::QSTmergeInfo< N, Q >::dshape_packed(), btas::STArray< T, N >::end(), btas::QSTmergeInfo< N, Q >::equal_range(), btas::QSTArray< T, N, Q >::q(), btas::QSTmergeInfo< N, Q >::qshape(), btas::STArray< T, N >::reserve(), btas::QSTArray< T, N, Q >::resize(), btas::STArray< T, N >::stride(), and btas::TArray< T, N >::subarray().
template<typename T , size_t MR, size_t N, class Q = Quantum> void btas::QSTmerge (const QSTmergeInfo< MR, Q > & rows_info, const QSTArray< T, N, Q > & a, QSTArray< T, 1+N-MR, Q > & b)
Merging row ranks.
Row-merge: { Rows-info(i,j <-> r), A(i,j,k,l) } -> B(r,k,l)
Definition at line 33 of file QSTmerge.h.
References btas::STArray< T, N >::allowed(), btas::STArray< T, N >::dshape(), btas::QSTmergeInfo< N, Q >::dshape_merged(), btas::QSTmergeInfo< N, Q >::dshape_packed(), btas::STArray< T, N >::end(), btas::QSTmergeInfo< N, Q >::equal_range(), btas::TArray< T, N >::fill(), btas::STArray< T, N >::find(), btas::STArray< T, N >::index(), btas::STArray< T, N >::insert(), btas::QSTArray< T, N, Q >::q(), btas::QSTArray< T, N, Q >::qshape(), btas::QSTmergeInfo< N, Q >::qshape_merged(), btas::QSTArray< T, N, Q >::resize(), btas::STArray< T, N >::shape(), and btas::STArray< T, N >::stride().
Referenced by mps::add(), mps::gemm(), mps::gemv(), and mps::inprod().
template<typename T , size_t N, size_t MC, class Q = Quantum> void btas::QSTmerge (const QSTArray< T, N, Q > & a, const QSTmergeInfo< MC, Q > & cols_info, QSTArray< T, N-MC+1, Q > & b)
Merging col ranks.
Column-merge: { A(i,j,k,l), Cols-info(k,l <-> c) } -> B(i,j,c)
Definition at line 94 of file QSTmerge.h.
References btas::STArray< T, N >::allowed(), btas::STArray< T, N >::dshape(), btas::QSTmergeInfo< N, Q >::dshape_merged(), btas::QSTmergeInfo< N, Q >::dshape_packed(), btas::STArray< T, N >::end(), btas::QSTmergeInfo< N, Q >::equal_range(), btas::TArray< T, N >::fill(), btas::STArray< T, N >::find(), btas::STArray< T, N >::index(), btas::STArray< T, N >::insert(), btas::QSTArray< T, N, Q >::q(), btas::QSTArray< T, N, Q >::qshape(), btas::QSTmergeInfo< N, Q >::qshape_merged(), btas::QSTArray< T, N, Q >::resize(), btas::STArray< T, N >::size(), and btas::STArray< T, N >::stride().
template<typename T , size_t MR, size_t MC, class Q = Quantum> void btas::QSTmerge (const QSTmergeInfo< MR, Q > & rows_info, const QSTArray< T, MR+MC, Q > & a, const QSTmergeInfo< MC, Q > & cols_info, QSTArray< T, 2, Q > & b)
Merging row and col ranks to form matrix.
Row/Column-merge: { Rows-info(i,j <-> r), A(i,j,k,l), Cols-info(k,l -> c) } -> B(r,c)
Definition at line 155 of file QSTmerge.h.
References btas::STArray< T, N >::allowed(), btas::STArray< T, N >::dshape(), btas::QSTmergeInfo< N, Q >::dshape_merged(), btas::QSTmergeInfo< N, Q >::dshape_packed(), btas::STArray< T, N >::end(), btas::QSTmergeInfo< N, Q >::equal_range(), btas::TArray< T, N >::fill(), btas::STArray< T, N >::find(), btas::STArray< T, N >::insert(), btas::QSTArray< T, N, Q >::q(), btas::QSTmergeInfo< N, Q >::qshape_merged(), btas::QSTArray< T, N, Q >::resize(), shape(), btas::STArray< T, N >::shape(), and btas::STArray< T, N >::stride().
template<size_t N> void btas::SDaxpy (const double & alpha, const SDArray< N > & x, SDArray< N > & y)
Definition at line 468 of file SDblas.h.
References BTAS_THROW, btas::STArray< T, N >::dshape(), btas::STArray< T, N >::resize(), serial_SDaxpy(), btas::STArray< T, N >::size(), and thread_SDaxpy().
Referenced by SDorthogonalize().
template<size_t NA, size_t NB, size_t NC> void btas::SDblasWrapper (const double & alpha, const SDArray< NA > & a, const SDArray< NB > & b, const double & beta, SDArray< NC > & c)
Wrapper function for DBLAS.
Definition at line 595 of file SDblas.h.
References NoTrans, SDgemm(), SDgemv(), and Trans.
template<size_t NA, size_t NB, size_t K> void btas::SDcontract (const double & alpha, const SDArray< NA > & a, const IVector< K > & a_contract, const SDArray< NB > & b, const IVector< K > & b_contract, const double & beta, SDArray< NA+NB-K-K > & c)
Convenient sparse-array contraction function.
Definition at line 16 of file SDcontract.h.
References BTAS_THROW, get_contract_jobs(), JOBMASK_A_PMUTE, JOBMASK_A_TRANS, JOBMASK_B_PMUTE, JOBMASK_B_TRANS, JOBMASK_BLAS_TYPE, NoTrans, btas::STArray< T, N >::reference(), SDgemm(), SDgemv(), SDpermute(), btas::STArray< T, N >::shape(), and Trans.
Referenced by contract(), and SDindexed_contract().
template<size_t N> void btas::SDcopy (const SDArray< N > & x, SDArray< N > & y, bool _up_cast = false)
Definition at line 429 of file SDblas.h.
References BTAS_THROW, btas::STArray< T, N >::dshape(), btas::STArray< T, N >::resize(), serial_SDcopy(), btas::STArray< T, N >::shape(), and thread_SDcopy().
Referenced by QSDgesvd(), SDindexed_permute(), and SDpermute().
template<size_t NA, size_t K> void btas::SDdiagonal (const SDArray< NA > & a, const IVector< K > & d_index, SDArray< NA-K+1 > & b)
Function to get diagonal elements for sparse array.
Note that the order of d_index affects to the index of 'b' a(i,j,k,l) with d_index(j,l) returns b(i,j,k) = a(i,j,k,j) a(i,j,k,l) with d_index(l,j) returns b(i,k,l) = a(i,l,k,l)
Definition at line 22 of file SDdiagonal.h.
References btas::STArray< T, N >::begin(), BTAS_THROW, Ddiagonal(), btas::STArray< T, N >::dshape(), btas::STArray< T, N >::end(), btas::STArray< T, N >::index(), btas::STArray< T, N >::reserve(), btas::STArray< T, N >::resize(), and btas::STArray< T, N >::size().
template<size_t NA, size_t NB> void btas::SDdidm (const SDArray< NA > & a, SDArray< NB > & b)
Non-BLAS function: (diagonal matrix) * (general matrix)
Definition at line 582 of file SDblas.h.
References btas::STArray< T, N >::begin(), Ddidm(), btas::STArray< T, N >::end(), btas::STArray< T, N >::find(), and btas::STArray< T, N >::shape().
Referenced by mps::compress(), decompose(), and indexed_decompose().
template<size_t NA, size_t NB> void btas::SDdimd (SDArray< NA > & a, const SDArray< NB > & b)
Non-BLAS function: (general matrix) * (diagonal matrix)
Definition at line 570 of file SDblas.h.
References btas::STArray< T, N >::begin(), Ddimd(), btas::STArray< T, N >::end(), btas::STArray< T, N >::find(), and btas::STArray< T, N >::size().
Referenced by mps::compress().
template<size_t N> double btas::SDdot (const SDArray< N > & x, const SDArray< N > & y)
Definition at line 459 of file SDblas.h.
References BTAS_THROW, serial_SDdot(), and btas::STArray< T, N >::shape().
Referenced by decompose(), indexed_decompose(), QSDgesvd(), SDnormalize(), and SDorthogonalize().
template<size_t N> void btas::SDdsum (const SDArray< N > & x, const SDArray< N > & y, SDArray< N > & z) inline
Definition at line 18 of file SDArray.h.
References STdsum().
template<size_t N, size_t K> void btas::SDdsum (const SDArray< N > & x, const SDArray< N > & y, const IVector< K > & trace_index, SDArray< N > & z) inline
Definition at line 22 of file SDArray.h.
References STdsum().
template<size_t NA, size_t NB, size_t NC> void btas::SDgemm (const BTAS_TRANSPOSE & TransA, const BTAS_TRANSPOSE & TransB, const double & alpha, const SDArray< NA > & a, const SDArray< NB > & b, const double & beta, SDArray< NC > & c)
call threaded sparse-dgemm
since c(i, j) = sum_{k} a(i, k) * b(k, j), it's advantageous to store 'b' as b(j, k) order so that summation over k has less memory-miss when searching non-zero element
Definition at line 535 of file SDblas.h.
References BTAS_THROW, btas::STArray< T, N >::dshape(), gemm_contract_dshape(), NoTrans, btas::STArray< T, N >::resize(), SDscal(), btas::STArray< T, N >::size(), thread_SDgemm(), and btas::STArray< T, N >::transposed_view().
Referenced by SDblasWrapper(), and SDcontract().
template<size_t NA, size_t NB, size_t NC> void btas::SDgemv (const BTAS_TRANSPOSE & TransA, const double & alpha, const SDArray< NA > & a, const SDArray< NB > & b, const double & beta, SDArray< NC > & c)
Definition at line 490 of file SDblas.h.
References BTAS_THROW, btas::STArray< T, N >::dshape(), gemv_contract_dshape(), NoTrans, btas::STArray< T, N >::resize(), SDscal(), btas::STArray< T, N >::size(), thread_SDgemv(), and btas::STArray< T, N >::transposed_view().
Referenced by SDblasWrapper(), and SDcontract().
template<size_t NA, size_t NB, size_t NC> void btas::SDger (const double & alpha, const SDArray< NA > & a, const SDArray< NB > & b, SDArray< NC > & c)
Definition at line 513 of file SDblas.h.
References BTAS_THROW, btas::STArray< T, N >::dshape(), ger_contract_dshape(), btas::STArray< T, N >::resize(), btas::STArray< T, N >::size(), and thread_SDger().
template<size_t NA, size_t NB, size_t NC> void btas::SDindexed_contract (const double & alpha, const SDArray< NA > & a, const IVector< NA > & a_symbols, const SDArray< NB > & b, const IVector< NB > & b_symbols, const double & beta, SDArray< NC > & c, const IVector< NC > & c_symbols)
Convenient sparse-array indexed-contraction function.
Definition at line 60 of file SDcontract.h.
References indexed_contract_shape(), SDcontract(), SDindexed_permute(), and btas::STArray< T, N >::size().
Referenced by indexed_contract().
template<size_t N> void btas::SDindexed_permute (const SDArray< N > & x, const IVector< N > & x_symbols, SDArray< N > & y, const IVector< N > & y_symbols)
Call sparse-array indexed-permutation (wrapper)
Definition at line 73 of file SDpermute.h.
References indexed_permute_shape(), SDcopy(), and SDpermute().
Referenced by indexed_permute(), and SDindexed_contract().
template<size_t N> void btas::SDnormalize (SDArray< N > & x)
Normalization.
Definition at line 614 of file SDblas.h.
References SDdot(), and SDscal().
template<size_t N> void btas::SDorthogonalize (const SDArray< N > & x, SDArray< N > & y)
Orthogonalization.
Definition at line 621 of file SDblas.h.
References SDaxpy(), and SDdot().
template<size_t N> void btas::SDpermute (const SDArray< N > & x, const IVector< N > & pindex, SDArray< N > & y)
Call sparse-array permutation (wrapper)
Definition at line 51 of file SDpermute.h.
References BTAS_THROW, btas::STArray< T, N >::dshape(), permute(), btas::STArray< T, N >::resize(), SDcopy(), serial_SDpermute(), and thread_SDpermute().
Referenced by permute(), SDcontract(), and SDindexed_permute().
template<size_t N> void btas::SDscal (const double & alpha, SDArray< N > & x)
Definition at line 448 of file SDblas.h.
References serial_SDscal(), and thread_SDscal().
Referenced by QSDgemm(), QSDgemv(), QSDscal(), SDgemm(), SDgemv(), and SDnormalize().
template<size_t N> IVector<N> btas::sequence (int first = 0, int incl = 1)
Convenient IVector constructor to return sequence.
e.g. sequence<5>(0, 1) returns { 0, 1, 2, 3, 4 }
Parameters
first starting value of sequence
incl increments of sequence
Definition at line 359 of file TVector.h.
template<size_t N> void btas::serial_SDaxpy (const double & alpha, const SDArray< N > & x, SDArray< N > & y)
Call Daxpy per every non-zero block.
Definition at line 74 of file SDblas.h.
References btas::STArray< T, N >::begin(), BTAS_THROW, Daxpy(), btas::STArray< T, N >::end(), and btas::STArray< T, N >::reserve().
Referenced by QSDaxpy(), and SDaxpy().
template<size_t N> void btas::serial_SDcopy (const SDArray< N > & x, SDArray< N > & y, bool _up_cast = false)
Call Dcopy per every non-zero block.
if _up_cast is on, only blocks in 'x' that allowed in 'y' are copied in other words, e.g. doing up-cast from SDArray(x) to QSDArray(y)
if _up_cast is off, it's aborted when block in 'x' that is not allowed in 'y' is found
Definition at line 37 of file SDblas.h.
References btas::STArray< T, N >::begin(), BTAS_THROW, Dcopy(), btas::STArray< T, N >::end(), and btas::STArray< T, N >::reserve().
Referenced by QSDcopy(), and SDcopy().
template<size_t N> double btas::serial_SDdot (const SDArray< N > & x, const SDArray< N > & y)
Call Ddot per every non-zero block.
Definition at line 51 of file SDblas.h.
References btas::STArray< T, N >::begin(), Ddot(), btas::STArray< T, N >::end(), and btas::STArray< T, N >::find().
Referenced by QSDdotc(), QSDdotu(), and SDdot().
template<size_t N> void btas::serial_SDpermute (const SDArray< N > & x, const IVector< N > & pindex, SDArray< N > & y)
Call sparse-array permutation (serial run)
Definition at line 22 of file SDpermute.h.
References btas::STArray< T, N >::begin(), Dpermute(), btas::STArray< T, N >::end(), btas::STArray< T, N >::index(), permute(), and btas::STArray< T, N >::reserve().
Referenced by QSDpermute(), and SDpermute().
template<size_t N> void btas::serial_SDscal (const double & alpha, SDArray< N > & x)
Call Dscal per every non-zero block.
Definition at line 65 of file SDblas.h.
References btas::STArray< T, N >::begin(), Dscal(), and btas::STArray< T, N >::end().
Referenced by SDscal().
IVector< 1> btas::shape (int n01) inline
Convenient IVector constructor for N = 1.
Definition at line 283 of file TVector.h.
Referenced by mps::compress(), DENSE_TEST(), mps::dot(), mps::gemm(), mps::gemv(), mps::inprod(), QSDgesvd(), QSPARSE_TEST(), and QSTmerge().
IVector< 2> btas::shape (int n01, int n02) inline
Convenient IVector constructor for N = 2.
Definition at line 289 of file TVector.h.
IVector< 3> btas::shape (int n01, int n02, int n03) inline
Convenient IVector constructor for N = 3.
Definition at line 295 of file TVector.h.
IVector< 4> btas::shape (int n01, int n02, int n03, int n04) inline
Convenient IVector constructor for N = 4.
Definition at line 301 of file TVector.h.
IVector< 5> btas::shape (int n01, int n02, int n03, int n04, int n05) inline
Convenient IVector constructor for N = 5.
Definition at line 307 of file TVector.h.
IVector< 6> btas::shape (int n01, int n02, int n03, int n04, int n05, int n06) inline
Convenient IVector constructor for N = 6.
Definition at line 313 of file TVector.h.
IVector< 7> btas::shape (int n01, int n02, int n03, int n04, int n05, int n06, int n07) inline
Convenient IVector constructor for N = 7.
Definition at line 319 of file TVector.h.
IVector< 8> btas::shape (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08) inline
Convenient IVector constructor for N = 8.
Definition at line 325 of file TVector.h.
IVector< 9> btas::shape (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09) inline
Convenient IVector constructor for N = 9.
Definition at line 331 of file TVector.h.
IVector<10> btas::shape (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10) inline
Convenient IVector constructor for N = 10.
Definition at line 337 of file TVector.h.
IVector<11> btas::shape (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10, int n11) inline
Convenient IVector constructor for N = 11.
Definition at line 343 of file TVector.h.
IVector<12> btas::shape (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10, int n11, int n12) inline
Convenient IVector constructor for N = 12.
Definition at line 349 of file TVector.h.
template<typename T , size_t N> void btas::STdsum (const STArray< T, N > & x, const STArray< T, N > & y, STArray< T, N > & z)
Direct sum of arrays X and Y, adding to Z.
E.g.) Z = X (+) Y : N = 2 | x x | | x x 0 0 0 | | x x | (+) = | x x 0 0 0 | | y y y | | 0 0 y y y |
Definition at line 27 of file STdsum.h.
References _dsum_check_dshape(), btas::STArray< T, N >::begin(), BTAS_THROW, btas::STArray< T, N >::dshape(), btas::STArray< T, N >::end(), btas::STArray< T, N >::index(), btas::STArray< T, N >::insert(), btas::STArray< T, N >::resize(), btas::STArray< T, N >::shape(), and btas::STArray< T, N >::size().
Referenced by SDdsum().
template<typename T , size_t N, size_t K> void btas::STdsum (const STArray< T, N > & x, const STArray< T, N > & y, const IVector< K > & trace_index, STArray< T, N > & z)
Partial direct sum of arrays X and Y, adding to Z.
E.g.) Z = X (+) Y with trace index = { 0 } : N = 2, K = 1 | x x | | y y y | | x x y y y | | x x | (+) | y y y | = | x x y y y | | x x | | y y y | | x x y y y |
Note that sizes of trace indices must be the same between two arrays
Definition at line 63 of file STdsum.h.
References _dsum_check_dshape(), btas::STArray< T, N >::begin(), BTAS_THROW, btas::STArray< T, N >::dshape(), btas::STArray< T, N >::end(), btas::STArray< T, N >::index(), btas::STArray< T, N >::insert(), btas::STArray< T, N >::resize(), btas::STArray< T, N >::shape(), and btas::STArray< T, N >::size().
template<class Q = Quantum> void btas::thread_QSDgesvd (const BTAS_ARROW_DIRECTION & ArrowDir, const QSDArray< 2, Q > & a, SDArray< 1 > & s, QSDArray< 2, Q > & u, QSDArray< 2, Q > & vt, bool calc_full_u = false, bool calc_full_vt = false)
Calling Dgesvd threaded for each non-zero block Only for matrix form. Suppose matrix A is block-diagonal, i.e. quantum number indices must be merged, which simplifies computation.
QSDgesvd subroutine merges array A to pass it here.
Definition at line 38 of file QSDlapack.h.
References btas::STArray< T, N >::begin(), btas::STArray< T, N >::end(), LeftArrow, parallel_call(), btas::STArray< T, N >::reserve(), btas::STArray< T, N >::shape(), and btas::STArray< T, N >::size().
Referenced by QSDgesvd().
template<size_t N> void btas::thread_SDaxpy (const double & alpha, const SDArray< N > & x, SDArray< N > & y)
Call Daxpy per every non-zero block.
Definition at line 125 of file SDblas.h.
References btas::STArray< T, N >::begin(), BTAS_THROW, btas::STArray< T, N >::end(), btas::STArray< T, N >::nnz(), parallel_call(), and btas::STArray< T, N >::reserve().
Referenced by QSDaxpy(), and SDaxpy().
template<size_t N> void btas::thread_SDcopy (const SDArray< N > & x, SDArray< N > & y, bool _up_cast)
Call Dcopy per every non-zero block.
if _up_cast is on, only blocks in 'x' that allowed in 'y' are copied in other words, e.g. doing up-cast from SDArray(x) to QSDArray(y)
if _up_cast is off, it's aborted when block in 'x' that is not allowed in 'y' is found
Definition at line 96 of file SDblas.h.
References btas::STArray< T, N >::begin(), BTAS_THROW, btas::STArray< T, N >::end(), btas::STArray< T, N >::nnz(), parallel_call(), and btas::STArray< T, N >::reserve().
Referenced by QSDcopy(), and SDcopy().
template<size_t NA, size_t NB, size_t NC> void btas::thread_SDgemm (const BTAS_TRANSPOSE & TransA, const BTAS_TRANSPOSE & TransB, const double & alpha, const SDArray< NA > & a, const SDArray< NB > & b, SDArray< NC > & c)
Call Dgemm per every non-zero block.
before calling thread_SDgemv
'c' is scaled by beta
sparse-block of 'a' is transposed if TransA = Trans
sparse-block of 'b' is transposed if TransB = NoTrans since c(i, j) = sum_{k} a(i, k) * b(k, j), it's advantageous to store 'b' as b(j, k) order so that summation over k has less memory-miss when searching non-zero element
note that dense-arrays have not yet been transposed
approximately
Definition at line 223 of file SDblas.h.
References btas::DgemmArglist< NA, NB, NC >::add(), btas::STArray< T, N >::allowed(), BTAS_THROW, btas::STArray< T, N >::end(), btas::STArray< T, N >::lower_bound(), btas::STArray< T, N >::nnz(), parallel_call(), btas::STArray< T, N >::reserve(), btas::DgemmArglist< NA, NB, NC >::reset(), btas::STArray< T, N >::shape(), btas::C_arglist_triple< double, NA, NB, NC >::size(), and btas::STArray< T, N >::upper_bound().
Referenced by QSDgemm(), and SDgemm().
template<size_t NA, size_t NB, size_t NC> void btas::thread_SDgemm (function< double(const IVector< NA > &, const IVector< NB > &, const IVector< NC > &)> f_scale, const BTAS_TRANSPOSE & TransA, const BTAS_TRANSPOSE & TransB, const double & alpha, const SDArray< NA > & a, const SDArray< NB > & b, SDArray< NC > & c)
Call Dgemm per every non-zero block.
before calling thread_SDgemv
'c' is scaled by beta
sparse-block of 'a' is transposed if TransA = Trans
sparse-block of 'b' is transposed if TransB = NoTrans since c(i, j) = sum_{k} a(i, k) * b(k, j), it's advantageous to store 'b' as b(j, k) order so that summation over k has less memory-miss when searching non-zero element
note that dense-arrays have not yet been transposed
approximately
Definition at line 366 of file SDblas.h.
References btas::DgemmArglist< NA, NB, NC >::add(), btas::STArray< T, N >::allowed(), BTAS_THROW, btas::STArray< T, N >::end(), btas::STArray< T, N >::index(), btas::STArray< T, N >::lower_bound(), btas::STArray< T, N >::nnz(), parallel_call(), btas::STArray< T, N >::reserve(), btas::DgemmArglist< NA, NB, NC >::reset(), btas::STArray< T, N >::shape(), btas::C_arglist_triple< double, NA, NB, NC >::size(), and btas::STArray< T, N >::upper_bound().
template<size_t NA, size_t NB, size_t NC> void btas::thread_SDgemv (const BTAS_TRANSPOSE & TransA, const double & alpha, const SDArray< NA > & a, const SDArray< NB > & b, SDArray< NC > & c)
Call Dgemv per every non-zero block.
before calling thread_SDgemv
'c' is scaled by beta
sparse-block of 'a' is transposed if TransA = Trans, note that dense-arrays have not yet been transposed
Definition at line 146 of file SDblas.h.
References btas::DgemvArglist< NA, NB, NC >::add(), btas::STArray< T, N >::allowed(), BTAS_THROW, btas::STArray< T, N >::end(), btas::STArray< T, N >::find(), btas::STArray< T, N >::lower_bound(), btas::STArray< T, N >::nnz(), parallel_call(), btas::STArray< T, N >::reserve(), btas::DgemvArglist< NA, NB, NC >::reset(), btas::STArray< T, N >::shape(), btas::C_arglist_triple< double, NA, NB, NC >::size(), and btas::STArray< T, N >::upper_bound().
Referenced by QSDgemv(), and SDgemv().
template<size_t NA, size_t NB, size_t NC> void btas::thread_SDgemv (function< double(const IVector< NA > &, const IVector< NB > &, const IVector< NC > &)> f_scale, const BTAS_TRANSPOSE & TransA, const double & alpha, const SDArray< NA > & a, const SDArray< NB > & b, SDArray< NC > & c)
Call Dgemv per every non-zero block.
before calling thread_SDgemv
'c' is scaled by beta
sparse-block of 'a' is transposed if TransA = Trans, note that dense-arrays have not yet been transposed
Definition at line 285 of file SDblas.h.
References btas::DgemvArglist< NA, NB, NC >::add(), btas::STArray< T, N >::allowed(), BTAS_THROW, btas::STArray< T, N >::end(), btas::STArray< T, N >::find(), btas::STArray< T, N >::index(), btas::STArray< T, N >::lower_bound(), btas::STArray< T, N >::nnz(), parallel_call(), btas::STArray< T, N >::reserve(), btas::DgemvArglist< NA, NB, NC >::reset(), btas::STArray< T, N >::shape(), btas::C_arglist_triple< double, NA, NB, NC >::size(), and btas::STArray< T, N >::upper_bound().
template<size_t NA, size_t NB, size_t NC> void btas::thread_SDger (const double & alpha, const SDArray< NA > & a, const SDArray< NB > & b, SDArray< NC > & c)
Call Dger per every non-zero block.
approximately
Definition at line 186 of file SDblas.h.
References btas::DgerArglist< NA, NB, NC >::add(), btas::STArray< T, N >::allowed(), btas::STArray< T, N >::begin(), BTAS_THROW, btas::STArray< T, N >::end(), btas::STArray< T, N >::nnz(), parallel_call(), btas::STArray< T, N >::reserve(), and btas::STArray< T, N >::shape().
Referenced by QSDger(), and SDger().
template<size_t NA, size_t NB, size_t NC> void btas::thread_SDger (function< double(const IVector< NA > &, const IVector< NB > &, const IVector< NC > &)> f_scale, const double & alpha, const SDArray< NA > & a, const SDArray< NB > & b, SDArray< NC > & c)
Call Dger per every non-zero block.
approximately
Definition at line 327 of file SDblas.h.
References btas::DgerArglist< NA, NB, NC >::add(), btas::STArray< T, N >::allowed(), btas::STArray< T, N >::begin(), BTAS_THROW, btas::STArray< T, N >::end(), btas::STArray< T, N >::index(), btas::STArray< T, N >::nnz(), parallel_call(), btas::STArray< T, N >::reserve(), and btas::STArray< T, N >::shape().
template<size_t N> void btas::thread_SDpermute (const SDArray< N > & x, const IVector< N > & pindex, SDArray< N > & y)
Call sparse-array permutation (threaded)
Definition at line 35 of file SDpermute.h.
References btas::STArray< T, N >::begin(), btas::STArray< T, N >::end(), btas::STArray< T, N >::index(), btas::STArray< T, N >::nnz(), parallel_call(), permute(), and btas::STArray< T, N >::reserve().
Referenced by QSDpermute(), and SDpermute().
template<size_t N> void btas::thread_SDscal (const double & alpha, SDArray< N > & x)
Call Dscal per every non-zero block.
Definition at line 113 of file SDblas.h.
References btas::STArray< T, N >::begin(), btas::STArray< T, N >::end(), btas::STArray< T, N >::nnz(), and parallel_call().
Referenced by SDscal().
template<typename T , size_t N> TVector<T, N> btas::transpose (const TVector< T, N > & vec, int K)
Return transposed vector.
e.g. N = 6, K = 4 [i,j,k,l,m,n] -> [m,n,i,j,k,l] |1 2 3 4|5 6| |5 6|1 2 3 4|
Definition at line 378 of file TVector.h.
Referenced by Dgeev(), Dgesv(), Dgetrf(), Dggev(), Dsyev(), Dsygv(), QSDgemm(), QSDgemv(), and btas::STArray< T, N >::transposed_view().
template<typename T , size_t N> TVector<T, N> btas::uniform (const T & value)
Convenient constructor of TVector with const value.
Definition at line 57 of file TVector.h.