Basic Tensor Algebra Subprograms (BTAS): btas::DgerArglist< NA, NB, NC > Class Template Reference
btas::DgerArglist< NA, NB, NC > Class Template Reference
#include <Darglist.h>
Public Member Functions
DgerArglist ()
Default constructor.
DgerArglist (const shared_ptr< DArray< NC >> &c_ptr, const double &alpha=1.0)
void reset (const shared_ptr< DArray< NC >> &c_ptr, const double &alpha=1.0)
Reset arglist.
void clear ()
Clear argments.
void add (const shared_ptr< DArray< NA >> &a_ptr, const shared_ptr< DArray< NB >> &b_ptr, double scale=1.0)
Add arglist.
void call () const
Call Dger.
Public Member Functions inherited from btas::C_arglist_triple< double, NA, NB, NC >
C_arglist_triple ()
Default constructor.
C_arglist_triple (const shared_ptr< TArray< double, N3 >> &arg3_ptr)
Initializer.
virtual ~C_arglist_triple ()
Destructor.
void reset (const shared_ptr< TArray< double, N3 >> &arg3_ptr)
Reset argment 3.
void add (const shared_ptr< TArray< double, N1 >> &arg1_ptr, const shared_ptr< TArray< double, N2 >> &arg2_ptr)
Add argment list.
size_t size () const
Return number of argment list.
Public Member Functions inherited from btas::T_arglist_base
T_arglist_base (size_t flops=0)
Default constructor.
virtual ~T_arglist_base ()
Destructor.
bool operator== (const T_arglist_base &other) const
Boolian operator== for compare FLOPS count.
bool operator!= (const T_arglist_base &other) const
Boolian operator!= for compare FLOPS count.
bool operator< (const T_arglist_base &other) const
Boolian operator< for sorting FLOPS count.
bool operator> (const T_arglist_base &other) const
Boolian operator> for sorting FLOPS count.
Private Member Functions
size_t mf_flops_count (const shared_ptr< DArray< NA >> &a_ptr, const shared_ptr< DArray< NB >> &b_ptr)
return FLOPS count
Private Attributes
std::vector< double > m_scale
this contains index-dependent scaling s.t. parity, Clebsch-Gordan coeff., etc.
double m_alpha
Additional Inherited Members
Protected Member Functions inherited from btas::C_arglist_triple< double, NA, NB, NC >
virtual size_t mf_flops_count (const shared_ptr< TArray< double, N1 >> &arg1_ptr, const shared_ptr< TArray< double, N2 >> &arg2_ptr)
Function to compute FLOPS count.
Protected Attributes inherited from btas::C_arglist_triple< double, NA, NB, NC >
std::vector< shared_ptr
< TArray< double, N1 > > > m_argment_1
array list of a
std::vector< shared_ptr
< TArray< double, N2 > > > m_argment_2
array list of b
shared_ptr< TArray< double, N3 > > m_argment_3
Detailed Description
template<size_t NA, size_t NB, size_t NC>
class btas::DgerArglist< NA, NB, NC >
Definition at line 181 of file Darglist.h.
Constructor & Destructor Documentation
template<size_t NA, size_t NB, size_t NC> btas::DgerArglist< NA, NB, NC >::DgerArglist () inline
Default constructor.
Definition at line 194 of file Darglist.h.
template<size_t NA, size_t NB, size_t NC> btas::DgerArglist< NA, NB, NC >::DgerArglist (const shared_ptr< DArray< NC >> & c_ptr, const double & alpha = 1.0) inline
Definition at line 196 of file Darglist.h.
Member Function Documentation
template<size_t NA, size_t NB, size_t NC> void btas::DgerArglist< NA, NB, NC >::add (const shared_ptr< DArray< NA >> & a_ptr, const shared_ptr< DArray< NB >> & b_ptr, double scale = 1.0) inline
Add arglist.
Definition at line 215 of file Darglist.h.
References btas::C_arglist_triple< T, N1, N2, N3 >::add(), and btas::DgerArglist< NA, NB, NC >::m_scale.
Referenced by btas::thread_SDger().
template<size_t NA, size_t NB, size_t NC> void btas::DgerArglist< NA, NB, NC >::call () const inline
Call Dger.
Definition at line 221 of file Darglist.h.
References btas::Dger(), btas::DgerArglist< NA, NB, NC >::m_alpha, btas::DgerArglist< NA, NB, NC >::m_scale, and btas::C_arglist_triple< double, NA, NB, NC >::size().
template<size_t NA, size_t NB, size_t NC> void btas::DgerArglist< NA, NB, NC >::clear () inline virtual
Clear argments.
Reimplemented from btas::C_arglist_triple< double, NA, NB, NC >.
Definition at line 208 of file Darglist.h.
References btas::C_arglist_triple< T, N1, N2, N3 >::clear(), btas::DgerArglist< NA, NB, NC >::m_alpha, and btas::DgerArglist< NA, NB, NC >::m_scale.
template<size_t NA, size_t NB, size_t NC> size_t btas::DgerArglist< NA, NB, NC >::mf_flops_count (const shared_ptr< DArray< NA >> & a_ptr, const shared_ptr< DArray< NB >> & b_ptr) inline private
return FLOPS count
Definition at line 190 of file Darglist.h.
template<size_t NA, size_t NB, size_t NC> void btas::DgerArglist< NA, NB, NC >::reset (const shared_ptr< DArray< NC >> & c_ptr, const double & alpha = 1.0) inline
Reset arglist.
Definition at line 202 of file Darglist.h.
References btas::DgerArglist< NA, NB, NC >::m_alpha, and btas::C_arglist_triple< T, N1, N2, N3 >::reset().
Field Documentation
template<size_t NA, size_t NB, size_t NC> double btas::DgerArglist< NA, NB, NC >::m_alpha private
Definition at line 187 of file Darglist.h.
Referenced by btas::DgerArglist< NA, NB, NC >::call(), btas::DgerArglist< NA, NB, NC >::clear(), and btas::DgerArglist< NA, NB, NC >::reset().
template<size_t NA, size_t NB, size_t NC> std::vector<double> btas::DgerArglist< NA, NB, NC >::m_scale private
this contains index-dependent scaling s.t. parity, Clebsch-Gordan coeff., etc.
Definition at line 185 of file Darglist.h.
Referenced by btas::DgerArglist< NA, NB, NC >::add(), btas::DgerArglist< NA, NB, NC >::call(), and btas::DgerArglist< NA, NB, NC >::clear().
The documentation for this class was generated from the following file:
include/btas/DENSE/Darglist.h