Basic Tensor Algebra Subprograms (BTAS): lib/tests.C File Reference
tests.C File Reference
#include <iostream>
#include <iomanip>
#include <fstream>
#include <cmath>
#include <cstdlib>
#include <boost/archive/text_oarchive.hpp>
#include <boost/archive/text_iarchive.hpp>
#include <btas/TVector.h>
#include <btas/DENSE/DArray.h>
#include <btas/QSPARSE/QSDArray.h>
#include <time_stamp.h>
Macros
#define _DEFAULT_QUANTUM 1
Functions
double rgen ()
int DENSE_TEST (int iprint=0)
int QSPARSE_TEST (int iprint=0)
int SERIALIZE_TEST (int iprint=0)
int main ()
Macro Definition Documentation
#define _DEFAULT_QUANTUM 1
Definition at line 12 of file tests.C.
Function Documentation
int DENSE_TEST (int iprint = 0)
Definition at line 23 of file tests.C.
References btas::Daxpy(), btas::Dcontract(), btas::Dcopy(), btas::Ddiagonal(), btas::Ddot(), btas::Dgemm(), btas::Dgemv(), btas::Dger(), btas::Dindexed_contract(), btas::Dpermute(), btas::Dscal(), btas::TArray< T, N >::generate(), btas::NoTrans, rgen(), btas::shape(), and btas::Trans.
Referenced by main().
int main ()
Definition at line 372 of file tests.C.
References DENSE_TEST(), time_stamp::elapsed(), QSPARSE_TEST(), SERIALIZE_TEST(), and time_stamp::start().
int QSPARSE_TEST (int iprint = 0)
Definition at line 136 of file tests.C.
References btas::QSTArray< T, N, Q >::conjugate(), btas::STArray< T, N >::dshape(), btas::QSTArray< T, N, Q >::erase(), btas::STArray< T, N >::generate(), btas::LeftArrow, btas::make_array(), btas::NoTrans, btas::QSDcontract(), btas::QSDdotc(), btas::QSDgemm(), btas::QSDgemv(), btas::QSDger(), btas::QSDgesvd(), btas::QSDmerge(), btas::QSDscal(), btas::QSTArray< T, N, Q >::qshape(), btas::QSTdsum(), rgen(), btas::shape(), and btas::QSTArray< T, N, Q >::subarray().
Referenced by main().
double rgen ()
Definition at line 7 of file tests.C.
Referenced by DENSE_TEST(), QSPARSE_TEST(), and SERIALIZE_TEST().
int SERIALIZE_TEST (int iprint = 0)
Definition at line 327 of file tests.C.
References btas::QSTArray< T, N, Q >::clear(), btas::STArray< T, N >::generate(), and rgen().
Referenced by main().