Basic Tensor Algebra Subprograms (BTAS): btas::QSTArray< T, N, Q > Class Template Reference
btas::QSTArray< T, N, Q > Class Template Reference
Quantum number-based block sparse array.
#include <QSTArray.h>
Public Types
typedef STArray< T, N >
::const_iterator const_iterator
typedef STArray< T, N >::iterator iterator
Public Types inherited from btas::STArray< T, N >
typedef DataType::const_iterator const_iterator
typedef DataType::iterator iterator
Public Member Functions
QSTArray ()
Default constructor.
~QSTArray ()
Destructor.
QSTArray (const Q &q_total, const TVector< Qshapes< Q >, N > &q_shape)
Construct from quantum number indices.
QSTArray (const Q &q_total, const TVector< Qshapes< Q >, N > &q_shape, const TVector< Dshapes, N > &d_shape, bool _allocate=true)
Construct from quantum number indices and their dense shapes.
QSTArray (const Q &q_total, const TVector< Qshapes< Q >, N > &q_shape, const TVector< Dshapes, N > &d_shape, const T &value)
Construct from quantum number indices and their dense shapes and initialized by constant value.
template<class Generator >
QSTArray (const Q &q_total, const TVector< Qshapes< Q >, N > &q_shape, const TVector< Dshapes, N > &d_shape, Generator gen)
Construct from quantum number indices and their dense shapes and initialized by gen()
QSTArray (const QSTArray &other)
Copy constructor.
QSTArray & operator= (const QSTArray &other)
Copy assignment operator.
QSTArray (QSTArray &&other)
Move constructor.
QSTArray & operator= (QSTArray &&other)
Move assignment operator.
void reference (const QSTArray &other)
make reference to other
QSTArray subarray (const TVector< Dshapes, N > &_indxs) const
Make subarray reference.
void resize (const Q &q_total, const TVector< Qshapes< Q >, N > &q_shape)
Construct from quantum number indices.
void resize (const Q &q_total, const TVector< Qshapes< Q >, N > &q_shape, const TVector< Dshapes, N > &d_shape, bool _allocate=true)
Resize from quantum number indices and their dense shapes.
void resize (const Q &q_total, const TVector< Qshapes< Q >, N > &q_shape, const TVector< Dshapes, N > &d_shape, const T &value)
Resize from quantum number indices and their dense shapes and initialized by constant value.
template<class Generator >
void resize (const Q &q_total, const TVector< Qshapes< Q >, N > &q_shape, const TVector< Dshapes, N > &d_shape, Generator gen)
Resize from quantum number indices and their dense shapes and initialized by gen()
void operator= (const T &value)
void clear ()
Deallocation.
void erase (int _rank, int _index)
Erase blocks of which have certain index.
const Q & q () const
const TVector< Qshapes< Q >, N > & qshape () const
const Qshapes< Q > & qshape (int i) const
TVector< Q, N > qindex (const IVector< N > &block_index) const
Returns quantum numbers corresponding to block-index.
void parity (const std::vector< int > &p1)
Inplaced parity operation.
void parity (const std::vector< int > &p1, const std::vector< int > &p2)
Inplaced parity operation.
QSTArray conjugate () const
Returns conjugated referece.
void conjugate_self ()
Self conjugation.
Public Member Functions inherited from btas::STArray< T, N >
STArray ()
Default constructor.
virtual ~STArray ()
Destructor.
STArray (const IVector< N > &_shape)
Construct by sparse-block shape.
STArray (const TVector< Dshapes, N > &_dn_shape, bool _allocate=true)
Construct by dense-block shapes.
STArray (const TVector< Dshapes, N > &_dn_shape, const T &value)
Construct by dense-block shapes and fill elements by value.
template<class Generator >
STArray (const TVector< Dshapes, N > &_dn_shape, Generator gen)
Construct by dense-block shapes and fill elements by gen()
STArray (const STArray &other)
Copy constructor.
STArray & operator= (const STArray &other)
Copy assignment operator.
void copy (const STArray &other)
Take deep copy of other.
STArray (STArray &&other)
Move constructor.
STArray & operator= (STArray &&other)
Move assignment operator.
void reference (const STArray &other)
make reference to other
STArray subarray (const TVector< Dshapes, N > &_indxs) const
Make subarray reference.
void resize (const IVector< N > &_shape)
Resize by sparse-block shape.
void resize (const TVector< Dshapes, N > &_dn_shape, bool _allocate=true)
Resize by dense-block shapes using this->mf_check_allowed(index)
void allocate ()
Allocate all allowed blocks (existed blocks are collapsed)
void resize (const TVector< Dshapes, N > &_dn_shape, const T &value)
Resize by dense-block shapes and fill all elements by value.
template<class Generator >
void resize (const TVector< Dshapes, N > &_dn_shape, Generator gen)
Resize by dense-block shapes and fill all elements by gen()
void fill (const T &value)
fills all elements by value
void operator= (const T &value)
fills all elements by value
template<class Generator >
void generate (Generator gen)
generates all elements by gen()
iterator erase (const IVector< N > &_index)
Erase certain block by index.
iterator erase (const int &_tag)
Erase certain block by tag.
IVector< N > index (int _tag) const
convert tag to index
int tag (const IVector< N > &_index) const
convert index to tag
const IVector< N > & shape () const
Returns sparse-block shape.
const int & shape (int i) const
Returns sparse-block shape for rank i.
const IVector< N > & stride () const
Returns sparse-block stride.
const int & stride (int i) const
Returns sparse-block stride for rank i.
size_t nnz () const
Returns number of non-zero sparse-blocks.
size_t size () const
Returns total number of sparse-blocks (includes zero blocks)
const TVector< Dshapes, N > & dshape () const
Returns dense-block shapes.
const Dshapes & dshape (int i) const
Returns dense-block shapes for rank i.
const TVector< Dshapes, N > & check_dshape ()
Check and update dense-block shapes.
TVector< Dshapes, N > check_net_dshape () const
Calc. and return net dense-block shapes.
const_iterator begin () const
iterator begin ()
const_iterator end () const
iterator end ()
const_iterator find (const IVector< N > &_index) const
iterator find (const IVector< N > &_index)
const_iterator lower_bound (const IVector< N > &_index) const
iterator lower_bound (const IVector< N > &_index)
const_iterator upper_bound (const IVector< N > &_index) const
iterator upper_bound (const IVector< N > &_index)
const_iterator find (const int &_tag) const
iterator find (const int &_tag)
const_iterator lower_bound (const int &_tag) const
iterator lower_bound (const int &_tag)
const_iterator upper_bound (const int &_tag) const
iterator upper_bound (const int &_tag)
bool allowed (const int &_tag) const
return true if the requested block is non-zero, called by block tag
bool allowed (const IVector< N > &_index) const
return true if the requested block is non-zero, called by block index
iterator reserve (const int &_tag)
reserve non-zero block and return its iterator, by block tag
iterator reserve (const IVector< N > &_index)
reserve non-zero block and return its iterator, by block index
iterator insert (const int &_tag, const TArray< T, N > &block)
insert dense-array block and return its iterator, by block tag
iterator insert (const IVector< N > &_index, const TArray< T, N > &block)
insert dense-array block and return its iterator, by block index
STArray transposed_view (int K) const
return reference in which the sparse-blocks are transposed
STArray permuted_view (const IVector< N > &pindex) const
return reference in which the sparse-blocks are permuted by pindex
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Boost serialization.
bool mf_check_allowed (const IVector< N > &block_index) const
Checking non-zero block.
Private Attributes
Q m_q_total
Total quantum number of array.
TVector< Qshapes< Q >, N > m_q_shape
Quantum number indices.
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from btas::STArray< T, N >
void mf_check_dshape (const IVector< N > &_index, const IVector< N > &_shape)
Protected Attributes inherited from btas::STArray< T, N >
IVector< N > m_shape
sparse-block shape
TVector< Dshapes, N > m_dn_shape
dense-block shapes
IVector< N > m_stride
stride for sparse-block
DataType m_store
non-zero data array mapped by tag
Detailed Description
template<typename T, size_t N, class Q = Quantum>
class btas::QSTArray< T, N, Q >
Quantum number-based block sparse array.
Definition at line 17 of file QSTArray.h.
Member Typedef Documentation
template<typename T, size_t N, class Q = Quantum> typedef STArray<T, N>::const_iterator btas::QSTArray< T, N, Q >::const_iterator
Definition at line 19 of file QSTArray.h.
template<typename T, size_t N, class Q = Quantum> typedef STArray<T, N>::iterator btas::QSTArray< T, N, Q >::iterator
Definition at line 20 of file QSTArray.h.
Constructor & Destructor Documentation
template<typename T, size_t N, class Q = Quantum> btas::QSTArray< T, N, Q >::QSTArray () inline
Default constructor.
Definition at line 44 of file QSTArray.h.
template<typename T, size_t N, class Q = Quantum> btas::QSTArray< T, N, Q >::~QSTArray () inline
Destructor.
Definition at line 47 of file QSTArray.h.
template<typename T, size_t N, class Q = Quantum> btas::QSTArray< T, N, Q >::QSTArray (const Q & q_total, const TVector< Qshapes< Q >, N > & q_shape) inline
Construct from quantum number indices.
Definition at line 51 of file QSTArray.h.
References btas::QSTArray< T, N, Q >::resize().
template<typename T, size_t N, class Q = Quantum> btas::QSTArray< T, N, Q >::QSTArray (const Q & q_total, const TVector< Qshapes< Q >, N > & q_shape, const TVector< Dshapes, N > & d_shape, bool _allocate = true) inline
Construct from quantum number indices and their dense shapes.
Definition at line 56 of file QSTArray.h.
References btas::QSTArray< T, N, Q >::resize().
template<typename T, size_t N, class Q = Quantum> btas::QSTArray< T, N, Q >::QSTArray (const Q & q_total, const TVector< Qshapes< Q >, N > & q_shape, const TVector< Dshapes, N > & d_shape, const T & value) inline
Construct from quantum number indices and their dense shapes and initialized by constant value.
Definition at line 61 of file QSTArray.h.
References btas::QSTArray< T, N, Q >::resize().
template<typename T, size_t N, class Q = Quantum> template<class Generator > btas::QSTArray< T, N, Q >::QSTArray (const Q & q_total, const TVector< Qshapes< Q >, N > & q_shape, const TVector< Dshapes, N > & d_shape, Generator gen) inline
Construct from quantum number indices and their dense shapes and initialized by gen()
Definition at line 67 of file QSTArray.h.
References btas::QSTArray< T, N, Q >::resize().
template<typename T, size_t N, class Q = Quantum> btas::QSTArray< T, N, Q >::QSTArray (const QSTArray< T, N, Q > & other) inline
Copy constructor.
Definition at line 76 of file QSTArray.h.
References btas::QSTArray< T, N, Q >::m_q_shape, and btas::QSTArray< T, N, Q >::m_q_total.
template<typename T, size_t N, class Q = Quantum> btas::QSTArray< T, N, Q >::QSTArray (QSTArray< T, N, Q > && other) inline
Move constructor.
Definition at line 94 of file QSTArray.h.
References btas::QSTArray< T, N, Q >::m_q_shape, and btas::QSTArray< T, N, Q >::m_q_total.
Member Function Documentation
template<typename T, size_t N, class Q = Quantum> void btas::QSTArray< T, N, Q >::clear () inline virtual
Deallocation.
Reimplemented from btas::STArray< T, N >.
Definition at line 205 of file QSTArray.h.
References btas::STArray< T, N >::clear(), btas::QSTArray< T, N, Q >::m_q_shape, and btas::QSTArray< T, N, Q >::m_q_total.
Referenced by mps::add(), mps::compress(), mps::dot(), mps::gemm(), mps::gemv(), mps::inprod(), btas::QSDgesvd(), and SERIALIZE_TEST().
template<typename T, size_t N, class Q = Quantum> QSTArray btas::QSTArray< T, N, Q >::conjugate () const inline
Returns conjugated referece.
Conjugation means flipping direction of quantum indices.
Definition at line 288 of file QSTArray.h.
References btas::QSTArray< T, N, Q >::m_q_shape, and btas::QSTArray< T, N, Q >::m_q_total.
Referenced by QSPARSE_TEST().
template<typename T, size_t N, class Q = Quantum> void btas::QSTArray< T, N, Q >::conjugate_self () inline
Self conjugation.
Definition at line 298 of file QSTArray.h.
References btas::QSTArray< T, N, Q >::m_q_shape, and btas::QSTArray< T, N, Q >::m_q_total.
template<typename T, size_t N, class Q = Quantum> void btas::QSTArray< T, N, Q >::erase (int _rank, int _index) inline virtual
Erase blocks of which have certain index.
Not good design, since it can't check quantum numbers
Parameters
_rank rank in which index is associated
_index index to be removed
Reimplemented from btas::STArray< T, N >.
Definition at line 216 of file QSTArray.h.
References btas::STArray< T, N >::begin(), btas::STArray< T, N >::erase(), and btas::QSTArray< T, N, Q >::m_q_shape.
Referenced by QSPARSE_TEST().
template<typename T, size_t N, class Q = Quantum> bool btas::QSTArray< T, N, Q >::mf_check_allowed (const IVector< N > & block_index) const inline private virtual
Checking non-zero block.
STArray<T, N>::mf_check_allowed is overridden here
Reimplemented from btas::STArray< T, N >.
Definition at line 33 of file QSTArray.h.
References btas::QSTArray< T, N, Q >::m_q_shape, and btas::QSTArray< T, N, Q >::m_q_total.
template<typename T, size_t N, class Q = Quantum> QSTArray& btas::QSTArray< T, N, Q >::operator= (const QSTArray< T, N, Q > & other) inline
Copy assignment operator.
Definition at line 82 of file QSTArray.h.
References btas::STArray< T, N >::copy(), btas::QSTArray< T, N, Q >::m_q_shape, and btas::QSTArray< T, N, Q >::m_q_total.
template<typename T, size_t N, class Q = Quantum> QSTArray& btas::QSTArray< T, N, Q >::operator= (QSTArray< T, N, Q > && other) inline
Move assignment operator.
Definition at line 100 of file QSTArray.h.
References btas::QSTArray< T, N, Q >::m_q_shape, btas::QSTArray< T, N, Q >::m_q_total, and btas::STArray< T, N >::operator=().
template<typename T, size_t N, class Q = Quantum> void btas::QSTArray< T, N, Q >::operator= (const T & value) inline
Definition at line 195 of file QSTArray.h.
References btas::STArray< T, N >::operator=().
template<typename T, size_t N, class Q = Quantum> void btas::QSTArray< T, N, Q >::parity (const std::vector< int > & p1) inline
Inplaced parity operation.
For each non-zero block, if q = sum_{i} m_q_shape[p1[i]] has odd particle number, scale -1
Definition at line 258 of file QSTArray.h.
References btas::STArray< T, N >::begin(), btas::STArray< T, N >::end(), btas::STArray< T, N >::index(), and btas::QSTArray< T, N, Q >::m_q_shape.
Referenced by btas::QSTArray< T, N, Q >::parity().
template<typename T, size_t N, class Q = Quantum> void btas::QSTArray< T, N, Q >::parity (const std::vector< int > & p1, const std::vector< int > & p2) inline
Inplaced parity operation.
For each non-zero block, scale by sign = prod_{i} (-1 : both m_q_shape[p1[i]] and m_q_shape[p2[i]] have odd particle number)
Definition at line 273 of file QSTArray.h.
References btas::STArray< T, N >::begin(), btas::STArray< T, N >::end(), btas::STArray< T, N >::index(), btas::QSTArray< T, N, Q >::m_q_shape, and btas::QSTArray< T, N, Q >::parity().
template<typename T, size_t N, class Q = Quantum> const Q& btas::QSTArray< T, N, Q >::q () const inline
! Erase blocks of which have certain set of indices *!
Definition at line 243 of file QSTArray.h.
References btas::QSTArray< T, N, Q >::m_q_total.
Referenced by btas::QSDaxpy(), btas::QSDcopy(), btas::QSDdotc(), btas::QSDdotu(), btas::QSDgemm(), btas::QSDgemv(), btas::QSDger(), btas::QSDgesvd(), btas::QSDpermute(), btas::QSTdsum(), btas::QSTexpand(), and btas::QSTmerge().
template<typename T, size_t N, class Q = Quantum> TVector<Q, N> btas::QSTArray< T, N, Q >::qindex (const IVector< N > & block_index) const inline
Returns quantum numbers corresponding to block-index.
Definition at line 248 of file QSTArray.h.
References btas::QSTArray< T, N, Q >::m_q_shape.
template<typename T, size_t N, class Q = Quantum> const TVector<Qshapes<Q>, N>& btas::QSTArray< T, N, Q >::qshape () const inline
Definition at line 244 of file QSTArray.h.
References btas::QSTArray< T, N, Q >::m_q_shape.
Referenced by mps::add(), mps::gemm(), mps::gemv(), mps::inprod(), btas::QSDaxpy(), btas::QSDcopy(), btas::QSDdotc(), btas::QSDdotu(), btas::QSDgemm(), btas::QSDgemv(), btas::QSDger(), btas::QSDgesvd(), btas::QSDpermute(), QSPARSE_TEST(), btas::QSTdsum(), btas::QSTexpand(), and btas::QSTmerge().
template<typename T, size_t N, class Q = Quantum> const Qshapes<Q>& btas::QSTArray< T, N, Q >::qshape (int i) const inline
Definition at line 245 of file QSTArray.h.
References btas::QSTArray< T, N, Q >::m_q_shape.
template<typename T, size_t N, class Q = Quantum> void btas::QSTArray< T, N, Q >::reference (const QSTArray< T, N, Q > & other) inline
make reference to other
not complete reference, since elements in m_store are only shared. so, even if m_shape or m_stride is changed, it won't be affected.
Definition at line 111 of file QSTArray.h.
References btas::QSTArray< T, N, Q >::m_q_shape, btas::QSTArray< T, N, Q >::m_q_total, and btas::STArray< T, N >::reference().
Referenced by btas::QSDcontract().
template<typename T, size_t N, class Q = Quantum> void btas::QSTArray< T, N, Q >::resize (const Q & q_total, const TVector< Qshapes< Q >, N > & q_shape) inline
Construct from quantum number indices.
Definition at line 155 of file QSTArray.h.
References btas::QSTArray< T, N, Q >::m_q_shape, btas::QSTArray< T, N, Q >::m_q_total, btas::STArray< T, N >::resize(), and btas::STArray< T, N >::size().
Referenced by btas::QSDaxpy(), btas::QSDcopy(), btas::QSDgemm(), btas::QSDgemv(), btas::QSDger(), btas::QSDgesvd(), btas::QSDpermute(), btas::QSTArray< T, N, Q >::QSTArray(), btas::QSTdsum(), btas::QSTexpand(), and btas::QSTmerge().
template<typename T, size_t N, class Q = Quantum> void btas::QSTArray< T, N, Q >::resize (const Q & q_total, const TVector< Qshapes< Q >, N > & q_shape, const TVector< Dshapes, N > & d_shape, bool _allocate = true) inline
Resize from quantum number indices and their dense shapes.
Definition at line 165 of file QSTArray.h.
References btas::QSTArray< T, N, Q >::m_q_shape, btas::QSTArray< T, N, Q >::m_q_total, btas::STArray< T, N >::resize(), and btas::STArray< T, N >::size().
template<typename T, size_t N, class Q = Quantum> void btas::QSTArray< T, N, Q >::resize (const Q & q_total, const TVector< Qshapes< Q >, N > & q_shape, const TVector< Dshapes, N > & d_shape, const T & value) inline
Resize from quantum number indices and their dense shapes and initialized by constant value.
Definition at line 174 of file QSTArray.h.
References btas::QSTArray< T, N, Q >::m_q_shape, btas::QSTArray< T, N, Q >::m_q_total, btas::STArray< T, N >::resize(), and btas::STArray< T, N >::size().
template<typename T, size_t N, class Q = Quantum> template<class Generator > void btas::QSTArray< T, N, Q >::resize (const Q & q_total, const TVector< Qshapes< Q >, N > & q_shape, const TVector< Dshapes, N > & d_shape, Generator gen) inline
Resize from quantum number indices and their dense shapes and initialized by gen()
Definition at line 184 of file QSTArray.h.
References btas::QSTArray< T, N, Q >::m_q_shape, btas::QSTArray< T, N, Q >::m_q_total, btas::STArray< T, N >::resize(), and btas::STArray< T, N >::size().
template<typename T, size_t N, class Q = Quantum> template<class Archive > void btas::QSTArray< T, N, Q >::serialize (Archive & ar, const unsigned int version) inline private
Boost serialization.
Definition at line 26 of file QSTArray.h.
References btas::QSTArray< T, N, Q >::m_q_shape, and btas::QSTArray< T, N, Q >::m_q_total.
template<typename T, size_t N, class Q = Quantum> QSTArray btas::QSTArray< T, N, Q >::subarray (const TVector< Dshapes, N > & _indxs) const inline
Make subarray reference.
Parameters
_indxs contains subarray indices e.g. sparse shape = { 4, 4 } _indxs = { { 1, 3 }, { 0, 2, 3} }
0 1 2 3 0 2 3 +–+–+–+–+ +–+–+–+ 0 | | | | | -> 1 |**|**|**| +–+–+–+–+ +–+–+–+ 1 |**| |**|**| 3 |**|**|**| +–+–+–+–+ +–+–+–+ 2 | | | | | +–+–+–+–+ 3 |**| |**|**| +–+–+–+–+
** blocks are only kept to make subarray
Definition at line 136 of file QSTArray.h.
References btas::QSTArray< T, N, Q >::m_q_shape, and btas::QSTArray< T, N, Q >::m_q_total.
Referenced by btas::QSDgesvd(), and QSPARSE_TEST().
Friends And Related Function Documentation
template<typename T, size_t N, class Q = Quantum> friend class boost::serialization::access friend
Definition at line 23 of file QSTArray.h.
Field Documentation
template<typename T, size_t N, class Q = Quantum> TVector<Qshapes<Q>, N> btas::QSTArray< T, N, Q >::m_q_shape private
Quantum number indices.
m_q_shape[0] = { q[0][0], q[0][1], ... } (for the first rank) m_q_shape[1] = { q[1][0], q[1][1], ... } (for the second rank) ...
e.g. for sparse block A(i, j, k), if (m_q_total == m_q_shape[0][i] + m_q_shape[1][j] + m_q_shape[2][k]) then A(i, j, k) is non-zero
Definition at line 321 of file QSTArray.h.
Referenced by btas::QSTArray< T, N, Q >::clear(), btas::QSTArray< T, N, Q >::conjugate(), btas::QSTArray< T, N, Q >::conjugate_self(), btas::QSTArray< T, N, Q >::erase(), btas::QSTArray< T, N, Q >::mf_check_allowed(), btas::QSTArray< T, N, Q >::operator=(), btas::QSTArray< T, N, Q >::parity(), btas::QSTArray< T, N, Q >::qindex(), btas::QSTArray< T, N, Q >::qshape(), btas::QSTArray< T, N, Q >::QSTArray(), btas::QSTArray< T, N, Q >::reference(), btas::QSTArray< T, N, Q >::resize(), btas::QSTArray< T, N, Q >::serialize(), and btas::QSTArray< T, N, Q >::subarray().
template<typename T, size_t N, class Q = Quantum> Q btas::QSTArray< T, N, Q >::m_q_total private
Total quantum number of array.
Definition at line 311 of file QSTArray.h.
Referenced by btas::QSTArray< T, N, Q >::clear(), btas::QSTArray< T, N, Q >::conjugate(), btas::QSTArray< T, N, Q >::conjugate_self(), btas::QSTArray< T, N, Q >::mf_check_allowed(), btas::QSTArray< T, N, Q >::operator=(), btas::QSTArray< T, N, Q >::q(), btas::QSTArray< T, N, Q >::QSTArray(), btas::QSTArray< T, N, Q >::reference(), btas::QSTArray< T, N, Q >::resize(), btas::QSTArray< T, N, Q >::serialize(), and btas::QSTArray< T, N, Q >::subarray().
The documentation for this class was generated from the following file:
include/btas/QSPARSE/QSTArray.h