Basic Tensor Algebra Subprograms (BTAS): btas::DgemvArglist< NA, NB, NC > Class Template Reference
btas::DgemvArglist< NA, NB, NC > Class Template Reference
#include <Darglist.h>
Public Member Functions
DgemvArglist ()
Default constructor.
DgemvArglist (const shared_ptr< DArray< NC >> &c_ptr, const BTAS_TRANSPOSE &transa=NoTrans, const double &alpha=1.0, const double &beta=1.0)
Initializer.
void reset (const shared_ptr< DArray< NC >> &c_ptr, const BTAS_TRANSPOSE &transa=NoTrans, const double &alpha=1.0, const double &beta=1.0)
Reset arglist.
void clear ()
Clear argments.
void add (const shared_ptr< DArray< NA >> &a_ptr, const shared_ptr< DArray< NB >> &b_ptr, double scale=1.0)
Add arglist.
void call () const
Call Dgemv.
Public Member Functions inherited from btas::C_arglist_triple< double, NA, NB, NC >
C_arglist_triple ()
Default constructor.
C_arglist_triple (const shared_ptr< TArray< double, N3 >> &arg3_ptr)
Initializer.
virtual ~C_arglist_triple ()
Destructor.
void reset (const shared_ptr< TArray< double, N3 >> &arg3_ptr)
Reset argment 3.
void add (const shared_ptr< TArray< double, N1 >> &arg1_ptr, const shared_ptr< TArray< double, N2 >> &arg2_ptr)
Add argment list.
size_t size () const
Return number of argment list.
Public Member Functions inherited from btas::T_arglist_base
T_arglist_base (size_t flops=0)
Default constructor.
virtual ~T_arglist_base ()
Destructor.
bool operator== (const T_arglist_base &other) const
Boolian operator== for compare FLOPS count.
bool operator!= (const T_arglist_base &other) const
Boolian operator!= for compare FLOPS count.
bool operator< (const T_arglist_base &other) const
Boolian operator< for sorting FLOPS count.
bool operator> (const T_arglist_base &other) const
Boolian operator> for sorting FLOPS count.
Private Member Functions
size_t mf_flops_count (const shared_ptr< DArray< NA >> &a_ptr, const shared_ptr< DArray< NB >> &b_ptr)
return FLOPS count
Private Attributes
std::vector< double > m_scale
this contains index-dependent scaling s.t. parity, Clebsch-Gordan coeff., etc.
BTAS_TRANSPOSE m_transa
double m_alpha
double m_beta
Additional Inherited Members
Protected Member Functions inherited from btas::C_arglist_triple< double, NA, NB, NC >
virtual size_t mf_flops_count (const shared_ptr< TArray< double, N1 >> &arg1_ptr, const shared_ptr< TArray< double, N2 >> &arg2_ptr)
Function to compute FLOPS count.
Protected Attributes inherited from btas::C_arglist_triple< double, NA, NB, NC >
std::vector< shared_ptr
< TArray< double, N1 > > > m_argment_1
array list of a
std::vector< shared_ptr
< TArray< double, N2 > > > m_argment_2
array list of b
shared_ptr< TArray< double, N3 > > m_argment_3
Detailed Description
template<size_t NA, size_t NB, size_t NC>
class btas::DgemvArglist< NA, NB, NC >
Definition at line 118 of file Darglist.h.
Constructor & Destructor Documentation
template<size_t NA, size_t NB, size_t NC> btas::DgemvArglist< NA, NB, NC >::DgemvArglist () inline
Default constructor.
Definition at line 135 of file Darglist.h.
template<size_t NA, size_t NB, size_t NC> btas::DgemvArglist< NA, NB, NC >::DgemvArglist (const shared_ptr< DArray< NC >> & c_ptr, const BTAS_TRANSPOSE & transa = NoTrans, const double & alpha = 1.0, const double & beta = 1.0) inline
Initializer.
Definition at line 138 of file Darglist.h.
Member Function Documentation
template<size_t NA, size_t NB, size_t NC> void btas::DgemvArglist< NA, NB, NC >::add (const shared_ptr< DArray< NA >> & a_ptr, const shared_ptr< DArray< NB >> & b_ptr, double scale = 1.0) inline
Add arglist.
Definition at line 165 of file Darglist.h.
References btas::C_arglist_triple< T, N1, N2, N3 >::add(), and btas::DgemvArglist< NA, NB, NC >::m_scale.
Referenced by btas::thread_SDgemv().
template<size_t NA, size_t NB, size_t NC> void btas::DgemvArglist< NA, NB, NC >::call () const inline
Call Dgemv.
Definition at line 171 of file Darglist.h.
References btas::Dgemv(), btas::DgemvArglist< NA, NB, NC >::m_alpha, btas::DgemvArglist< NA, NB, NC >::m_beta, btas::DgemvArglist< NA, NB, NC >::m_scale, btas::DgemvArglist< NA, NB, NC >::m_transa, and btas::C_arglist_triple< double, NA, NB, NC >::size().
template<size_t NA, size_t NB, size_t NC> void btas::DgemvArglist< NA, NB, NC >::clear () inline virtual
Clear argments.
Reimplemented from btas::C_arglist_triple< double, NA, NB, NC >.
Definition at line 156 of file Darglist.h.
References btas::C_arglist_triple< T, N1, N2, N3 >::clear(), btas::DgemvArglist< NA, NB, NC >::m_alpha, btas::DgemvArglist< NA, NB, NC >::m_beta, btas::DgemvArglist< NA, NB, NC >::m_scale, btas::DgemvArglist< NA, NB, NC >::m_transa, and btas::NoTrans.
template<size_t NA, size_t NB, size_t NC> size_t btas::DgemvArglist< NA, NB, NC >::mf_flops_count (const shared_ptr< DArray< NA >> & a_ptr, const shared_ptr< DArray< NB >> & b_ptr) inline private
return FLOPS count
Definition at line 131 of file Darglist.h.
template<size_t NA, size_t NB, size_t NC> void btas::DgemvArglist< NA, NB, NC >::reset (const shared_ptr< DArray< NC >> & c_ptr, const BTAS_TRANSPOSE & transa = NoTrans, const double & alpha = 1.0, const double & beta = 1.0) inline
Reset arglist.
Definition at line 146 of file Darglist.h.
References btas::DgemvArglist< NA, NB, NC >::m_alpha, btas::DgemvArglist< NA, NB, NC >::m_beta, btas::DgemvArglist< NA, NB, NC >::m_transa, and btas::C_arglist_triple< T, N1, N2, N3 >::reset().
Referenced by btas::thread_SDgemv().
Field Documentation
template<size_t NA, size_t NB, size_t NC> double btas::DgemvArglist< NA, NB, NC >::m_alpha private
Definition at line 126 of file Darglist.h.
Referenced by btas::DgemvArglist< NA, NB, NC >::call(), btas::DgemvArglist< NA, NB, NC >::clear(), and btas::DgemvArglist< NA, NB, NC >::reset().
template<size_t NA, size_t NB, size_t NC> double btas::DgemvArglist< NA, NB, NC >::m_beta private
Definition at line 128 of file Darglist.h.
Referenced by btas::DgemvArglist< NA, NB, NC >::call(), btas::DgemvArglist< NA, NB, NC >::clear(), and btas::DgemvArglist< NA, NB, NC >::reset().
template<size_t NA, size_t NB, size_t NC> std::vector<double> btas::DgemvArglist< NA, NB, NC >::m_scale private
this contains index-dependent scaling s.t. parity, Clebsch-Gordan coeff., etc.
Definition at line 122 of file Darglist.h.
Referenced by btas::DgemvArglist< NA, NB, NC >::add(), btas::DgemvArglist< NA, NB, NC >::call(), and btas::DgemvArglist< NA, NB, NC >::clear().
template<size_t NA, size_t NB, size_t NC> BTAS_TRANSPOSE btas::DgemvArglist< NA, NB, NC >::m_transa private
Definition at line 124 of file Darglist.h.
Referenced by btas::DgemvArglist< NA, NB, NC >::call(), btas::DgemvArglist< NA, NB, NC >::clear(), and btas::DgemvArglist< NA, NB, NC >::reset().
The documentation for this class was generated from the following file:
include/btas/DENSE/Darglist.h