Basic Tensor Algebra Subprograms (BTAS): btas::STArray< T, N > Class Template Reference
btas::STArray< T, N > Class Template Reference
Block-sparse array class.
#include <STArray.h>
Public Types
typedef DataType::const_iterator const_iterator
typedef DataType::iterator iterator
Public Member Functions
STArray ()
Default constructor.
virtual ~STArray ()
Destructor.
STArray (const IVector< N > &_shape)
Construct by sparse-block shape.
STArray (const TVector< Dshapes, N > &_dn_shape, bool _allocate=true)
Construct by dense-block shapes.
STArray (const TVector< Dshapes, N > &_dn_shape, const T &value)
Construct by dense-block shapes and fill elements by value.
template<class Generator >
STArray (const TVector< Dshapes, N > &_dn_shape, Generator gen)
Construct by dense-block shapes and fill elements by gen()
STArray (const STArray &other)
Copy constructor.
STArray & operator= (const STArray &other)
Copy assignment operator.
void copy (const STArray &other)
Take deep copy of other.
STArray (STArray &&other)
Move constructor.
STArray & operator= (STArray &&other)
Move assignment operator.
void reference (const STArray &other)
make reference to other
STArray subarray (const TVector< Dshapes, N > &_indxs) const
Make subarray reference.
void resize (const IVector< N > &_shape)
Resize by sparse-block shape.
void resize (const TVector< Dshapes, N > &_dn_shape, bool _allocate=true)
Resize by dense-block shapes using this->mf_check_allowed(index)
void allocate ()
Allocate all allowed blocks (existed blocks are collapsed)
void resize (const TVector< Dshapes, N > &_dn_shape, const T &value)
Resize by dense-block shapes and fill all elements by value.
template<class Generator >
void resize (const TVector< Dshapes, N > &_dn_shape, Generator gen)
Resize by dense-block shapes and fill all elements by gen()
void fill (const T &value)
fills all elements by value
void operator= (const T &value)
fills all elements by value
template<class Generator >
void generate (Generator gen)
generates all elements by gen()
iterator erase (const IVector< N > &_index)
Erase certain block by index.
iterator erase (const int &_tag)
Erase certain block by tag.
virtual void clear ()
Deallocation.
virtual void erase (int _rank, int _index_erase)
Erase blocks of which have certain index.
IVector< N > index (int _tag) const
convert tag to index
int tag (const IVector< N > &_index) const
convert index to tag
const IVector< N > & shape () const
Returns sparse-block shape.
const int & shape (int i) const
Returns sparse-block shape for rank i.
const IVector< N > & stride () const
Returns sparse-block stride.
const int & stride (int i) const
Returns sparse-block stride for rank i.
size_t nnz () const
Returns number of non-zero sparse-blocks.
size_t size () const
Returns total number of sparse-blocks (includes zero blocks)
const TVector< Dshapes, N > & dshape () const
Returns dense-block shapes.
const Dshapes & dshape (int i) const
Returns dense-block shapes for rank i.
const TVector< Dshapes, N > & check_dshape ()
Check and update dense-block shapes.
TVector< Dshapes, N > check_net_dshape () const
Calc. and return net dense-block shapes.
const_iterator begin () const
iterator begin ()
const_iterator end () const
iterator end ()
const_iterator find (const IVector< N > &_index) const
iterator find (const IVector< N > &_index)
const_iterator lower_bound (const IVector< N > &_index) const
iterator lower_bound (const IVector< N > &_index)
const_iterator upper_bound (const IVector< N > &_index) const
iterator upper_bound (const IVector< N > &_index)
const_iterator find (const int &_tag) const
iterator find (const int &_tag)
const_iterator lower_bound (const int &_tag) const
iterator lower_bound (const int &_tag)
const_iterator upper_bound (const int &_tag) const
iterator upper_bound (const int &_tag)
bool allowed (const int &_tag) const
return true if the requested block is non-zero, called by block tag
bool allowed (const IVector< N > &_index) const
return true if the requested block is non-zero, called by block index
iterator reserve (const int &_tag)
reserve non-zero block and return its iterator, by block tag
iterator reserve (const IVector< N > &_index)
reserve non-zero block and return its iterator, by block index
iterator insert (const int &_tag, const TArray< T, N > &block)
insert dense-array block and return its iterator, by block tag
iterator insert (const IVector< N > &_index, const TArray< T, N > &block)
insert dense-array block and return its iterator, by block index
STArray transposed_view (int K) const
return reference in which the sparse-blocks are transposed
STArray permuted_view (const IVector< N > &pindex) const
return reference in which the sparse-blocks are permuted by pindex
Protected Member Functions
virtual bool mf_check_allowed (const IVector< N > &_index) const
Checking non-zero block.
void mf_check_dshape (const IVector< N > &_index, const IVector< N > &_shape)
Protected Attributes
IVector< N > m_shape
sparse-block shape
TVector< Dshapes, N > m_dn_shape
dense-block shapes
IVector< N > m_stride
stride for sparse-block
DataType m_store
non-zero data array mapped by tag
Private Types
typedef std::map< int,
shared_ptr< TArray< T, N > > > DataType
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<typename T, size_t N>
class btas::STArray< T, N >
Block-sparse array class.
explain here for more detail
Definition at line 26 of file STArray.h.
Member Typedef Documentation
template<typename T, size_t N> typedef DataType::const_iterator btas::STArray< T, N >::const_iterator
Definition at line 33 of file STArray.h.
template<typename T, size_t N> typedef std::map<int, shared_ptr<TArray<T, N> > > btas::STArray< T, N >::DataType private
Definition at line 29 of file STArray.h.
template<typename T, size_t N> typedef DataType::iterator btas::STArray< T, N >::iterator
Definition at line 34 of file STArray.h.
Constructor & Destructor Documentation
template<typename T, size_t N> btas::STArray< T, N >::STArray () inline
Default constructor.
Definition at line 65 of file STArray.h.
References btas::STArray< T, N >::m_shape, and btas::STArray< T, N >::m_stride.
template<typename T, size_t N> virtual btas::STArray< T, N >::~STArray () inline virtual
Destructor.
Definition at line 68 of file STArray.h.
template<typename T, size_t N> btas::STArray< T, N >::STArray (const IVector< N > & _shape) inline
Construct by sparse-block shape.
Definition at line 71 of file STArray.h.
References btas::STArray< T, N >::resize().
template<typename T, size_t N> btas::STArray< T, N >::STArray (const TVector< Dshapes, N > & _dn_shape, bool _allocate = true) inline
Construct by dense-block shapes.
Definition at line 74 of file STArray.h.
References btas::STArray< T, N >::resize().
template<typename T, size_t N> btas::STArray< T, N >::STArray (const TVector< Dshapes, N > & _dn_shape, const T & value) inline
Construct by dense-block shapes and fill elements by value.
Definition at line 77 of file STArray.h.
References btas::STArray< T, N >::resize().
template<typename T, size_t N> template<class Generator > btas::STArray< T, N >::STArray (const TVector< Dshapes, N > & _dn_shape, Generator gen) inline
Construct by dense-block shapes and fill elements by gen()
Definition at line 81 of file STArray.h.
References btas::STArray< T, N >::resize().
template<typename T, size_t N> btas::STArray< T, N >::STArray (const STArray< T, N > & other) inline
Copy constructor.
Definition at line 88 of file STArray.h.
References btas::STArray< T, N >::copy().
template<typename T, size_t N> btas::STArray< T, N >::STArray (STArray< T, N > && other) inline
Move constructor.
Definition at line 111 of file STArray.h.
References btas::STArray< T, N >::m_dn_shape, btas::STArray< T, N >::m_shape, btas::STArray< T, N >::m_store, and btas::STArray< T, N >::m_stride.
Member Function Documentation
template<typename T, size_t N> void btas::STArray< T, N >::allocate () inline
Allocate all allowed blocks (existed blocks are collapsed)
Definition at line 214 of file STArray.h.
References btas::STArray< T, N >::m_dn_shape, btas::STArray< T, N >::m_shape, btas::STArray< T, N >::m_store, btas::STArray< T, N >::mf_check_allowed(), and btas::STArray< T, N >::size().
Referenced by btas::STArray< T, N >::resize().
template<typename T, size_t N> bool btas::STArray< T, N >::allowed (const int & _tag) const inline
return true if the requested block is non-zero, called by block tag
Definition at line 432 of file STArray.h.
References btas::STArray< T, N >::index(), and btas::STArray< T, N >::mf_check_allowed().
Referenced by btas::QSTmerge(), btas::thread_SDgemm(), btas::thread_SDgemv(), and btas::thread_SDger().
template<typename T, size_t N> bool btas::STArray< T, N >::allowed (const IVector< N > & _index) const inline
return true if the requested block is non-zero, called by block index
Definition at line 434 of file STArray.h.
References btas::STArray< T, N >::mf_check_allowed().
template<typename T, size_t N> const_iterator btas::STArray< T, N >::begin () const inline
Definition at line 403 of file STArray.h.
References btas::STArray< T, N >::m_store.
Referenced by mps::dot(), btas::QSTArray< T, N, Q >::erase(), mps::inprod(), btas::QSTArray< T, N, Q >::parity(), btas::QSDgesvd(), btas::QSTexpand(), btas::SDdiagonal(), btas::SDdidm(), btas::SDdimd(), btas::serial_SDaxpy(), btas::serial_SDcopy(), btas::serial_SDdot(), btas::serial_SDpermute(), btas::serial_SDscal(), btas::STdsum(), btas::thread_QSDgesvd(), btas::thread_SDaxpy(), btas::thread_SDcopy(), btas::thread_SDger(), btas::thread_SDpermute(), and btas::thread_SDscal().
template<typename T, size_t N> iterator btas::STArray< T, N >::begin () inline
Definition at line 404 of file STArray.h.
References btas::STArray< T, N >::m_store.
template<typename T, size_t N> const TVector<Dshapes, N>& btas::STArray< T, N >::check_dshape () inline
Check and update dense-block shapes.
Definition at line 375 of file STArray.h.
References btas::STArray< T, N >::index(), btas::STArray< T, N >::m_dn_shape, btas::STArray< T, N >::m_store, and btas::STArray< T, N >::mf_check_dshape().
Referenced by btas::QSDgesvd().
template<typename T, size_t N> TVector<Dshapes, N> btas::STArray< T, N >::check_net_dshape () const inline
Calc. and return net dense-block shapes.
Definition at line 382 of file STArray.h.
References BTAS_THROW, btas::STArray< T, N >::index(), btas::STArray< T, N >::m_shape, btas::STArray< T, N >::m_store, and btas::STArray< T, N >::resize().
template<typename T, size_t N> virtual void btas::STArray< T, N >::clear () inline virtual
Deallocation.
Reimplemented in btas::QSTArray< T, N, Q >.
Definition at line 274 of file STArray.h.
References btas::STArray< T, N >::m_dn_shape, btas::STArray< T, N >::m_shape, btas::STArray< T, N >::m_store, and btas::STArray< T, N >::m_stride.
Referenced by btas::QSTArray< T, N, Q >::clear(), and btas::QSDgesvd().
template<typename T, size_t N> void btas::STArray< T, N >::copy (const STArray< T, N > & other) inline
Take deep copy of other.
Definition at line 94 of file STArray.h.
References btas::STArray< T, N >::m_dn_shape, btas::STArray< T, N >::m_shape, btas::STArray< T, N >::m_store, and btas::STArray< T, N >::m_stride.
Referenced by btas::QSTArray< T, N, Q >::operator=(), btas::STArray< T, N >::operator=(), and btas::STArray< T, N >::STArray().
template<typename T, size_t N> const TVector<Dshapes, N>& btas::STArray< T, N >::dshape () const inline
Returns dense-block shapes.
Definition at line 369 of file STArray.h.
References btas::STArray< T, N >::m_dn_shape.
Referenced by mps::add(), mps::gemm(), mps::gemv(), mps::inprod(), btas::QSDaxpy(), btas::QSDcopy(), btas::QSDgemm(), btas::QSDgemv(), btas::QSDger(), btas::QSDgesvd(), btas::QSDpermute(), QSPARSE_TEST(), btas::QSTdsum(), btas::QSTexpand(), btas::QSTmerge(), btas::SDaxpy(), btas::SDcopy(), btas::SDdiagonal(), btas::SDgemm(), btas::SDgemv(), btas::SDger(), btas::SDpermute(), and btas::STdsum().
template<typename T, size_t N> const Dshapes& btas::STArray< T, N >::dshape (int i) const inline
Returns dense-block shapes for rank i.
Definition at line 372 of file STArray.h.
References btas::STArray< T, N >::m_dn_shape.
template<typename T, size_t N> const_iterator btas::STArray< T, N >::end () const inline
Definition at line 406 of file STArray.h.
References btas::STArray< T, N >::m_store.
Referenced by mps::dot(), mps::inprod(), btas::STArray< T, N >::insert(), btas::QSTArray< T, N, Q >::parity(), btas::QSDgesvd(), btas::QSTexpand(), btas::QSTmerge(), btas::STArray< T, N >::reserve(), btas::SDdiagonal(), btas::SDdidm(), btas::SDdimd(), btas::serial_SDaxpy(), btas::serial_SDcopy(), btas::serial_SDdot(), btas::serial_SDpermute(), btas::serial_SDscal(), btas::STdsum(), btas::thread_QSDgesvd(), btas::thread_SDaxpy(), btas::thread_SDcopy(), btas::thread_SDgemm(), btas::thread_SDgemv(), btas::thread_SDger(), btas::thread_SDpermute(), and btas::thread_SDscal().
template<typename T, size_t N> iterator btas::STArray< T, N >::end () inline
Definition at line 407 of file STArray.h.
References btas::STArray< T, N >::m_store.
template<typename T, size_t N> iterator btas::STArray< T, N >::erase (const IVector< N > & _index) inline
Erase certain block by index.
Definition at line 268 of file STArray.h.
References btas::STArray< T, N >::m_store, and btas::STArray< T, N >::tag().
Referenced by btas::QSTArray< T, N, Q >::erase().
template<typename T, size_t N> iterator btas::STArray< T, N >::erase (const int & _tag) inline
Erase certain block by tag.
Definition at line 271 of file STArray.h.
References btas::STArray< T, N >::m_store.
template<typename T, size_t N> virtual void btas::STArray< T, N >::erase (int _rank, int _index_erase) inline virtual
Erase blocks of which have certain index.
Parameters
_rank rank in which index is associated
_index index to be removed
Reimplemented in btas::QSTArray< T, N, Q >.
Definition at line 287 of file STArray.h.
References btas::STArray< T, N >::index(), btas::STArray< T, N >::m_shape, btas::STArray< T, N >::m_store, and btas::STArray< T, N >::tag().
template<typename T, size_t N> void btas::STArray< T, N >::fill (const T & value) inline
fills all elements by value
Definition at line 246 of file STArray.h.
References btas::STArray< T, N >::m_store.
Referenced by btas::STArray< T, N >::operator=(), and btas::STArray< T, N >::resize().
template<typename T, size_t N> const_iterator btas::STArray< T, N >::find (const IVector< N > & _index) const inline
Definition at line 409 of file STArray.h.
References btas::STArray< T, N >::m_store, and btas::STArray< T, N >::tag().
Referenced by mps::dot(), mps::inprod(), btas::STArray< T, N >::insert(), btas::QSDgesvd(), btas::QSTmerge(), btas::STArray< T, N >::reserve(), btas::SDdidm(), btas::SDdimd(), btas::serial_SDdot(), and btas::thread_SDgemv().
template<typename T, size_t N> iterator btas::STArray< T, N >::find (const IVector< N > & _index) inline
Definition at line 410 of file STArray.h.
References btas::STArray< T, N >::m_store, and btas::STArray< T, N >::tag().
template<typename T, size_t N> const_iterator btas::STArray< T, N >::find (const int & _tag) const inline
Definition at line 418 of file STArray.h.
References btas::STArray< T, N >::m_store.
template<typename T, size_t N> iterator btas::STArray< T, N >::find (const int & _tag) inline
Definition at line 419 of file STArray.h.
References btas::STArray< T, N >::m_store.
template<typename T, size_t N> template<class Generator > void btas::STArray< T, N >::generate (Generator gen) inline
generates all elements by gen()
Definition at line 255 of file STArray.h.
References btas::STArray< T, N >::m_store.
Referenced by QSPARSE_TEST(), btas::STArray< T, N >::resize(), and SERIALIZE_TEST().
template<typename T, size_t N> IVector<N> btas::STArray< T, N >::index (int _tag) const inline
convert tag to index
! Erase blocks of which have certain set of indices *!
Definition at line 334 of file STArray.h.
References btas::STArray< T, N >::m_stride.
Referenced by btas::STArray< T, N >::allowed(), btas::STArray< T, N >::check_dshape(), btas::STArray< T, N >::check_net_dshape(), btas::STArray< T, N >::erase(), btas::STArray< T, N >::insert(), btas::QSTArray< T, N, Q >::parity(), btas::STArray< T, N >::permuted_view(), btas::QSTmerge(), btas::STArray< T, N >::reserve(), btas::SDdiagonal(), btas::serial_SDpermute(), btas::STdsum(), btas::STArray< T, N >::subarray(), btas::thread_SDgemm(), btas::thread_SDgemv(), btas::thread_SDger(), and btas::thread_SDpermute().
template<typename T, size_t N> iterator btas::STArray< T, N >::insert (const int & _tag, const TArray< T, N > & block) inline
insert dense-array block and return its iterator, by block tag
if the requested block already exists:
add array to it, return its iterator if the requested block hasn't allocated
insert dense-array block and return its iterator
or, return last iterator if it's not allowed, with warning message (optional)
Definition at line 502 of file STArray.h.
References BTAS_DEBUG, btas::STArray< T, N >::end(), btas::STArray< T, N >::find(), btas::STArray< T, N >::index(), btas::STArray< T, N >::m_store, btas::STArray< T, N >::mf_check_allowed(), btas::STArray< T, N >::mf_check_dshape(), and btas::TArray< T, N >::shape().
Referenced by btas::QSTmerge(), and btas::STdsum().
template<typename T, size_t N> iterator btas::STArray< T, N >::insert (const IVector< N > & _index, const TArray< T, N > & block) inline
insert dense-array block and return its iterator, by block index
Definition at line 523 of file STArray.h.
References BTAS_DEBUG, btas::STArray< T, N >::end(), btas::STArray< T, N >::find(), btas::STArray< T, N >::m_store, btas::STArray< T, N >::mf_check_allowed(), btas::STArray< T, N >::mf_check_dshape(), btas::TArray< T, N >::shape(), and btas::STArray< T, N >::tag().
template<typename T, size_t N> const_iterator btas::STArray< T, N >::lower_bound (const IVector< N > & _index) const inline
Definition at line 412 of file STArray.h.
References btas::STArray< T, N >::m_store, and btas::STArray< T, N >::tag().
Referenced by btas::thread_SDgemm(), and btas::thread_SDgemv().
template<typename T, size_t N> iterator btas::STArray< T, N >::lower_bound (const IVector< N > & _index) inline
Definition at line 413 of file STArray.h.
References btas::STArray< T, N >::m_store, and btas::STArray< T, N >::tag().
template<typename T, size_t N> const_iterator btas::STArray< T, N >::lower_bound (const int & _tag) const inline
Definition at line 421 of file STArray.h.
References btas::STArray< T, N >::m_store.
template<typename T, size_t N> iterator btas::STArray< T, N >::lower_bound (const int & _tag) inline
Definition at line 422 of file STArray.h.
References btas::STArray< T, N >::m_store.
template<typename T, size_t N> virtual bool btas::STArray< T, N >::mf_check_allowed (const IVector< N > & _index) const inline protected virtual
Checking non-zero block.
This should be overridden so that non-zero block can be determined from STArray class
Reimplemented in btas::QSTArray< T, N, Q >.
Definition at line 45 of file STArray.h.
Referenced by btas::STArray< T, N >::allocate(), btas::STArray< T, N >::allowed(), btas::STArray< T, N >::insert(), and btas::STArray< T, N >::reserve().
template<typename T, size_t N> void btas::STArray< T, N >::mf_check_dshape (const IVector< N > & _index, const IVector< N > & _shape) inline protected
Definition at line 49 of file STArray.h.
References BTAS_THROW, and btas::STArray< T, N >::m_dn_shape.
Referenced by btas::STArray< T, N >::check_dshape(), and btas::STArray< T, N >::insert().
template<typename T, size_t N> size_t btas::STArray< T, N >::nnz () const inline
Returns number of non-zero sparse-blocks.
Definition at line 363 of file STArray.h.
References btas::STArray< T, N >::m_store.
Referenced by btas::thread_SDaxpy(), btas::thread_SDcopy(), btas::thread_SDgemm(), btas::thread_SDgemv(), btas::thread_SDger(), btas::thread_SDpermute(), and btas::thread_SDscal().
template<typename T, size_t N> STArray& btas::STArray< T, N >::operator= (const STArray< T, N > & other) inline
Copy assignment operator.
Definition at line 91 of file STArray.h.
References btas::STArray< T, N >::copy().
Referenced by btas::QSTArray< T, N, Q >::operator=().
template<typename T, size_t N> STArray& btas::STArray< T, N >::operator= (STArray< T, N > && other) inline
Move assignment operator.
Definition at line 119 of file STArray.h.
References btas::STArray< T, N >::m_dn_shape, btas::STArray< T, N >::m_shape, btas::STArray< T, N >::m_store, and btas::STArray< T, N >::m_stride.
template<typename T, size_t N> void btas::STArray< T, N >::operator= (const T & value) inline
fills all elements by value
Definition at line 251 of file STArray.h.
References btas::STArray< T, N >::fill().
template<typename T, size_t N> STArray btas::STArray< T, N >::permuted_view (const IVector< N > & pindex) const inline
return reference in which the sparse-blocks are permuted by pindex
dense-arrays are not permuted
Definition at line 577 of file STArray.h.
References btas::dot(), btas::STArray< T, N >::index(), btas::STArray< T, N >::m_dn_shape, btas::STArray< T, N >::m_store, btas::STArray< T, N >::m_stride, btas::permute(), btas::STArray< T, N >::reference(), and btas::STArray< T, N >::resize().
template<typename T, size_t N> void btas::STArray< T, N >::reference (const STArray< T, N > & other) inline
make reference to other
not complete reference, since elements in m_store are only shared. so, even if m_shape or m_stride is changed, it won't be affected.
Definition at line 131 of file STArray.h.
References btas::STArray< T, N >::m_dn_shape, btas::STArray< T, N >::m_shape, btas::STArray< T, N >::m_store, and btas::STArray< T, N >::m_stride.
Referenced by btas::STArray< T, N >::permuted_view(), btas::QSTArray< T, N, Q >::reference(), btas::SDcontract(), and btas::STArray< T, N >::transposed_view().
template<typename T, size_t N> iterator btas::STArray< T, N >::reserve (const int & _tag) inline
reserve non-zero block and return its iterator, by block tag
if the requested block already exists:
return its iterator
or, return error if it's not allowed if the requested block hasn't allocated
allocate dense-array block and return its iterator
or, return last iterator if it's not allowed, with warning message (optional)
Definition at line 444 of file STArray.h.
References BTAS_DEBUG, BTAS_THROW, btas::STArray< T, N >::end(), btas::STArray< T, N >::find(), btas::STArray< T, N >::index(), btas::STArray< T, N >::m_dn_shape, btas::STArray< T, N >::m_store, and btas::STArray< T, N >::mf_check_allowed().
Referenced by btas::QSDgesvd(), btas::QSTexpand(), btas::SDdiagonal(), btas::serial_SDaxpy(), btas::serial_SDcopy(), btas::serial_SDpermute(), btas::thread_QSDgesvd(), btas::thread_SDaxpy(), btas::thread_SDcopy(), btas::thread_SDgemm(), btas::thread_SDgemv(), btas::thread_SDger(), and btas::thread_SDpermute().
template<typename T, size_t N> iterator btas::STArray< T, N >::reserve (const IVector< N > & _index) inline
reserve non-zero block and return its iterator, by block index
Definition at line 470 of file STArray.h.
References BTAS_DEBUG, BTAS_THROW, btas::STArray< T, N >::end(), btas::STArray< T, N >::find(), btas::STArray< T, N >::m_dn_shape, btas::STArray< T, N >::m_store, btas::STArray< T, N >::mf_check_allowed(), and btas::STArray< T, N >::tag().
template<typename T, size_t N> void btas::STArray< T, N >::resize (const IVector< N > & _shape) inline
Resize by sparse-block shape.
Definition at line 189 of file STArray.h.
References btas::STArray< T, N >::m_dn_shape, btas::STArray< T, N >::m_shape, btas::STArray< T, N >::m_store, btas::STArray< T, N >::m_stride, and btas::STArray< T, N >::stride().
Referenced by btas::STArray< T, N >::check_net_dshape(), btas::STArray< T, N >::permuted_view(), btas::QSDgesvd(), btas::QSTArray< T, N, Q >::resize(), btas::STArray< T, N >::resize(), btas::SDaxpy(), btas::SDcopy(), btas::SDdiagonal(), btas::SDgemm(), btas::SDgemv(), btas::SDger(), btas::SDpermute(), btas::STArray< T, N >::STArray(), btas::STdsum(), btas::STArray< T, N >::subarray(), and btas::STArray< T, N >::transposed_view().
template<typename T, size_t N> void btas::STArray< T, N >::resize (const TVector< Dshapes, N > & _dn_shape, bool _allocate = true) inline
Resize by dense-block shapes using this->mf_check_allowed(index)
Definition at line 203 of file STArray.h.
References btas::STArray< T, N >::allocate(), btas::STArray< T, N >::m_dn_shape, btas::STArray< T, N >::resize(), and btas::STArray< T, N >::size().
template<typename T, size_t N> void btas::STArray< T, N >::resize (const TVector< Dshapes, N > & _dn_shape, const T & value) inline
Resize by dense-block shapes and fill all elements by value.
Definition at line 235 of file STArray.h.
References btas::STArray< T, N >::fill(), and btas::STArray< T, N >::resize().
Referenced by btas::STArray< T, N >::resize().
template<typename T, size_t N> template<class Generator > void btas::STArray< T, N >::resize (const TVector< Dshapes, N > & _dn_shape, Generator gen) inline
Resize by dense-block shapes and fill all elements by gen()
Definition at line 239 of file STArray.h.
References btas::STArray< T, N >::generate(), and btas::STArray< T, N >::resize().
Referenced by btas::STArray< T, N >::resize().
template<typename T, size_t N> template<class Archive > void btas::STArray< T, N >::serialize (Archive & ar, const unsigned int version) inline private
Definition at line 40 of file STArray.h.
References btas::STArray< T, N >::m_dn_shape, btas::STArray< T, N >::m_shape, btas::STArray< T, N >::m_store, and btas::STArray< T, N >::m_stride.
template<typename T, size_t N> const IVector<N>& btas::STArray< T, N >::shape () const inline
Returns sparse-block shape.
Definition at line 351 of file STArray.h.
References btas::STArray< T, N >::m_shape.
Referenced by btas::QSDcontract(), btas::QSDgesvd(), btas::QSTmerge(), btas::SDcontract(), btas::SDcopy(), btas::SDdidm(), btas::SDdot(), btas::STdsum(), btas::thread_QSDgesvd(), btas::thread_SDgemm(), btas::thread_SDgemv(), and btas::thread_SDger().
template<typename T, size_t N> const int& btas::STArray< T, N >::shape (int i) const inline
Returns sparse-block shape for rank i.
Definition at line 354 of file STArray.h.
References btas::STArray< T, N >::m_shape.
template<typename T, size_t N> size_t btas::STArray< T, N >::size () const inline
Returns total number of sparse-blocks (includes zero blocks)
Definition at line 366 of file STArray.h.
References btas::STArray< T, N >::m_shape, and btas::STArray< T, N >::m_stride.
Referenced by btas::STArray< T, N >::allocate(), btas::QSDaxpy(), btas::QSDgemm(), btas::QSDgemv(), btas::QSDger(), btas::QSDindexed_contract(), btas::QSTdsum(), btas::QSTmerge(), btas::QSTArray< T, N, Q >::resize(), btas::STArray< T, N >::resize(), btas::SDaxpy(), btas::SDdiagonal(), btas::SDdimd(), btas::SDgemm(), btas::SDgemv(), btas::SDger(), btas::SDindexed_contract(), btas::STdsum(), btas::STArray< T, N >::subarray(), btas::thread_QSDgesvd(), and btas::STArray< T, N >::transposed_view().
template<typename T, size_t N> const IVector<N>& btas::STArray< T, N >::stride () const inline
Returns sparse-block stride.
Definition at line 357 of file STArray.h.
References btas::STArray< T, N >::m_stride.
Referenced by btas::QSTexpand(), btas::QSTmerge(), and btas::STArray< T, N >::resize().
template<typename T, size_t N> const int& btas::STArray< T, N >::stride (int i) const inline
Returns sparse-block stride for rank i.
Definition at line 360 of file STArray.h.
References btas::STArray< T, N >::m_stride.
template<typename T, size_t N> STArray btas::STArray< T, N >::subarray (const TVector< Dshapes, N > & _indxs) const inline
Make subarray reference.
Parameters
_indxs contains subarray indices e.g. sparse shape = { 4, 4 } _indxs = { { 1, 3 }, { 0, 2, 3} }
0 1 2 3 0 2 3 +–+–+–+–+ +–+–+–+ 0 | | | | | -> 1 |**|**|**| +–+–+–+–+ +–+–+–+ 1 |**| |**|**| 3 |**|**|**| +–+–+–+–+ +–+–+–+ 2 | | | | | +–+–+–+–+ 3 |**| |**|**| +–+–+–+–+
** blocks are only kept to make subarray
Definition at line 157 of file STArray.h.
References btas::STArray< T, N >::index(), btas::STArray< T, N >::m_dn_shape, btas::STArray< T, N >::m_shape, btas::STArray< T, N >::m_store, btas::STArray< T, N >::resize(), btas::STArray< T, N >::size(), and btas::STArray< T, N >::tag().
Referenced by btas::QSDgesvd().
template<typename T, size_t N> int btas::STArray< T, N >::tag (const IVector< N > & _index) const inline
convert index to tag
Definition at line 344 of file STArray.h.
References btas::dot(), and btas::STArray< T, N >::m_stride.
Referenced by btas::STArray< T, N >::erase(), btas::STArray< T, N >::find(), btas::STArray< T, N >::insert(), btas::STArray< T, N >::lower_bound(), btas::STArray< T, N >::reserve(), btas::STArray< T, N >::subarray(), and btas::STArray< T, N >::upper_bound().
template<typename T, size_t N> STArray btas::STArray< T, N >::transposed_view (int K) const inline
return reference in which the sparse-blocks are transposed
dense-arrays are not transposed
Parameters
K is a rank to be transposed e.g. N = 6, K = 4 [i,j,k,l,m,n] -> [m,n,i,j,k,l] |1 2 3 4|5 6| |5 6|1 2 3 4|
Definition at line 554 of file STArray.h.
References btas::STArray< T, N >::m_dn_shape, btas::STArray< T, N >::m_store, btas::STArray< T, N >::m_stride, btas::STArray< T, N >::reference(), btas::STArray< T, N >::resize(), btas::STArray< T, N >::size(), and btas::transpose().
Referenced by btas::QSDgemm(), btas::QSDgemv(), btas::SDgemm(), and btas::SDgemv().
template<typename T, size_t N> const_iterator btas::STArray< T, N >::upper_bound (const IVector< N > & _index) const inline
Definition at line 415 of file STArray.h.
References btas::STArray< T, N >::m_store, and btas::STArray< T, N >::tag().
Referenced by btas::thread_SDgemm(), and btas::thread_SDgemv().
template<typename T, size_t N> iterator btas::STArray< T, N >::upper_bound (const IVector< N > & _index) inline
Definition at line 416 of file STArray.h.
References btas::STArray< T, N >::m_store, and btas::STArray< T, N >::tag().
template<typename T, size_t N> const_iterator btas::STArray< T, N >::upper_bound (const int & _tag) const inline
Definition at line 424 of file STArray.h.
References btas::STArray< T, N >::m_store.
template<typename T, size_t N> iterator btas::STArray< T, N >::upper_bound (const int & _tag) inline
Definition at line 425 of file STArray.h.
References btas::STArray< T, N >::m_store.
Friends And Related Function Documentation
template<typename T, size_t N> friend class boost::serialization::access friend
Definition at line 38 of file STArray.h.
Field Documentation
template<typename T, size_t N> TVector<Dshapes, N> btas::STArray< T, N >::m_dn_shape protected
dense-block shapes
Definition at line 609 of file STArray.h.
Referenced by btas::STArray< T, N >::allocate(), btas::STArray< T, N >::check_dshape(), btas::STArray< T, N >::clear(), btas::STArray< T, N >::copy(), btas::STArray< T, N >::dshape(), btas::STArray< T, N >::mf_check_dshape(), btas::STArray< T, N >::operator=(), btas::STArray< T, N >::permuted_view(), btas::STArray< T, N >::reference(), btas::STArray< T, N >::reserve(), btas::STArray< T, N >::resize(), btas::STArray< T, N >::serialize(), btas::STArray< T, N >::STArray(), btas::STArray< T, N >::subarray(), and btas::STArray< T, N >::transposed_view().
template<typename T, size_t N> IVector<N> btas::STArray< T, N >::m_shape protected
sparse-block shape
Definition at line 605 of file STArray.h.
Referenced by btas::STArray< T, N >::allocate(), btas::STArray< T, N >::check_net_dshape(), btas::STArray< T, N >::clear(), btas::STArray< T, N >::copy(), btas::STArray< T, N >::erase(), btas::STArray< T, N >::operator=(), btas::STArray< T, N >::reference(), btas::STArray< T, N >::resize(), btas::STArray< T, N >::serialize(), btas::STArray< T, N >::shape(), btas::STArray< T, N >::size(), btas::STArray< T, N >::STArray(), and btas::STArray< T, N >::subarray().
template<typename T, size_t N> DataType btas::STArray< T, N >::m_store protected
non-zero data array mapped by tag
Definition at line 617 of file STArray.h.
Referenced by btas::STArray< T, N >::allocate(), btas::STArray< T, N >::begin(), btas::STArray< T, N >::check_dshape(), btas::STArray< T, N >::check_net_dshape(), btas::STArray< T, N >::clear(), btas::STArray< T, N >::copy(), btas::STArray< T, N >::end(), btas::STArray< T, N >::erase(), btas::STArray< T, N >::fill(), btas::STArray< T, N >::find(), btas::STArray< T, N >::generate(), btas::STArray< T, N >::insert(), btas::STArray< T, N >::lower_bound(), btas::STArray< T, N >::nnz(), btas::STArray< T, N >::operator=(), btas::STArray< T, N >::permuted_view(), btas::STArray< T, N >::reference(), btas::STArray< T, N >::reserve(), btas::STArray< T, N >::resize(), btas::STArray< T, N >::serialize(), btas::STArray< T, N >::STArray(), btas::STArray< T, N >::subarray(), btas::STArray< T, N >::transposed_view(), and btas::STArray< T, N >::upper_bound().
template<typename T, size_t N> IVector<N> btas::STArray< T, N >::m_stride protected
stride for sparse-block
Definition at line 613 of file STArray.h.
Referenced by btas::STArray< T, N >::clear(), btas::STArray< T, N >::copy(), btas::STArray< T, N >::index(), btas::STArray< T, N >::operator=(), btas::STArray< T, N >::permuted_view(), btas::STArray< T, N >::reference(), btas::STArray< T, N >::resize(), btas::STArray< T, N >::serialize(), btas::STArray< T, N >::size(), btas::STArray< T, N >::STArray(), btas::STArray< T, N >::stride(), btas::STArray< T, N >::tag(), and btas::STArray< T, N >::transposed_view().
The documentation for this class was generated from the following file:
include/btas/SPARSE/STArray.h