Basic Tensor Algebra Subprograms (BTAS): btas::TArray< T, N > Class Template Reference
btas::TArray< T, N > Class Template Reference
Dense array class.
#include <TArray.h>
Public Types
typedef std::vector< T >::iterator iterator
TArray<T, N>::iterator.
typedef std::vector< T >
::const_iterator const_iterator
TArray<T, N>::const_iterator.
Public Member Functions
TArray ()
default constructor
~TArray ()
destructor
TArray (const TArray &other)
copy constructor
TArray & operator= (const TArray &other)
copy assignment operator
TArray & operator+= (const TArray &other)
addition assignment operator
void copy (const TArray &other)
copying from other to this
TArray copy () const
return copy of this
template<size_t M>
void copy (const TSubArray< T, M > &a)
Copy from sub-array to array.
void scale (const T &alpha)
scale by const value
void add (const TArray &other)
adding from other to this
template<size_t M>
TArray (const TSubArray< T, M > &sub)
copy constructor from sub-array
template<size_t M>
TArray & operator= (const TSubArray< T, M > &sub)
copy assignment from sub-array
TArray (TArray &&other)
move constructor
TArray & operator= (TArray &&other)
move assignment
void reference (const TArray &other)
take data reference from other
TArray reference () const
return data reference of this
TArray (int n01)
convenient constructor with array shape, for N = 1
TArray (int n01, int n02)
convenient constructor with array shape, for N = 2
TArray (int n01, int n02, int n03)
convenient constructor with array shape, for N = 3
TArray (int n01, int n02, int n03, int n04)
convenient constructor with array shape, for N = 4
TArray (int n01, int n02, int n03, int n04, int n05)
convenient constructor with array shape, for N = 5
TArray (int n01, int n02, int n03, int n04, int n05, int n06)
convenient constructor with array shape, for N = 6
TArray (int n01, int n02, int n03, int n04, int n05, int n06, int n07)
convenient constructor with array shape, for N = 7
TArray (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08)
convenient constructor with array shape, for N = 8
TArray (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09)
convenient constructor with array shape, for N = 9
TArray (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10)
convenient constructor with array shape, for N = 10
TArray (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10, int n11)
convenient constructor with array shape, for N = 11
TArray (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10, int n11, int n12)
convenient constructor with array shape, for N = 12
TArray (const IVector< N > &_shape)
convenient constructor with array shape, for arbitrary N
void resize (int n01)
resize array shape, for N = 1
void resize (int n01, int n02)
resize array shape, for N = 2
void resize (int n01, int n02, int n03)
resize array shape, for N = 3
void resize (int n01, int n02, int n03, int n04)
resize array shape, for N = 4
void resize (int n01, int n02, int n03, int n04, int n05)
resize array shape, for N = 5
void resize (int n01, int n02, int n03, int n04, int n05, int n06)
resize array shape, for N = 6
void resize (int n01, int n02, int n03, int n04, int n05, int n06, int n07)
resize array shape, for N = 7
void resize (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08)
resize array shape, for N = 8
void resize (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09)
resize array shape, for N = 9
void resize (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10)
resize array shape, for N = 10
void resize (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10, int n11)
resize array shape, for N = 11
void resize (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10, int n11, int n12)
resize array shape, for N = 12
void resize (const IVector< N > &_shape)
resize array by _shape, for arbitrary N
const_iterator begin () const
returns first iterator position (const)
iterator begin ()
returns first iterator position
const_iterator end () const
returns last iterator position (const)
iterator end ()
returns last iterator position
const IVector< N > & shape () const
returns array shape
int shape (int i) const
returns array shape for rank i
const IVector< N > & stride () const
returns array stride
int stride (int i) const
returns array stride for rank i
size_t size () const
returns allocated size
const T & operator() (int i01) const
returns array element (N = 1) without range check
const T & operator() (int i01, int i02) const
returns array element (N = 2) without range check
const T & operator() (int i01, int i02, int i03) const
returns array element (N = 3) without range check
const T & operator() (int i01, int i02, int i03, int i04) const
returns array element (N = 4) without range check
const T & operator() (int i01, int i02, int i03, int i04, int i05) const
returns array element (N = 5) without range check
const T & operator() (int i01, int i02, int i03, int i04, int i05, int i06) const
returns array element (N = 6) without range check
const T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07) const
returns array element (N = 7) without range check
const T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08) const
returns array element (N = 8) without range check
const T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09) const
returns array element (N = 9) without range check
const T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10) const
returns array element (N = 10) without range check
const T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11) const
returns array element (N = 11) without range check
const T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11, int i12) const
returns array element (N = 12) without range check
const T & operator() (const IVector< N > &_index) const
returns array element (arbitrary N) without range check
T & operator() (int i01)
returns array element (N = 1) without range check
T & operator() (int i01, int i02)
returns array element (N = 2) without range check
T & operator() (int i01, int i02, int i03)
returns array element (N = 3) without range check
T & operator() (int i01, int i02, int i03, int i04)
returns array element (N = 4) without range check
T & operator() (int i01, int i02, int i03, int i04, int i05)
returns array element (N = 5) without range check
T & operator() (int i01, int i02, int i03, int i04, int i05, int i06)
returns array element (N = 6) without range check
T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07)
returns array element (N = 7) without range check
T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08)
returns array element (N = 8) without range check
T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09)
returns array element (N = 9) without range check
T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10)
returns array element (N = 10) without range check
T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11)
returns array element (N = 11) without range check
T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11, int i12)
returns array element (N = 12) without range check
T & operator() (const IVector< N > &_index)
returns array element (arbitrary N) without range check
const T & at (int i01) const
returns array element (N = 1) with range check
const T & at (int i01, int i02) const
returns array element (N = 2) with range check
const T & at (int i01, int i02, int i03) const
returns array element (N = 3) with range check
const T & at (int i01, int i02, int i03, int i04) const
returns array element (N = 4) with range check
const T & at (int i01, int i02, int i03, int i04, int i05) const
returns array element (N = 5) with range check
const T & at (int i01, int i02, int i03, int i04, int i05, int i06) const
returns array element (N = 6) with range check
const T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07) const
returns array element (N = 7) with range check
const T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08) const
returns array element (N = 8) with range check
const T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09) const
returns array element (N = 9) with range check
const T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10) const
returns array element (N = 10) with range check
const T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11) const
returns array element (N = 11) with range check
const T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11, int i12) const
returns array element (N = 12) with range check
const T & at (const IVector< N > &_index) const
returns array element (arbitrary N) with range check
T & at (int i01)
returns array element (N = 1) with range check
T & at (int i01, int i02)
returns array element (N = 2) with range check
T & at (int i01, int i02, int i03)
returns array element (N = 3) with range check
T & at (int i01, int i02, int i03, int i04)
returns array element (N = 4) with range check
T & at (int i01, int i02, int i03, int i04, int i05)
returns array element (N = 5) with range check
T & at (int i01, int i02, int i03, int i04, int i05, int i06)
returns array element (N = 6) with range check
T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07)
returns array element (N = 7) with range check
T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08)
returns array element (N = 8) with range check
T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09)
returns array element (N = 9) with range check
T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10)
returns array element (N = 10) with range check
T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11)
returns array element (N = 11) with range check
T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11, int i12)
returns array element (N = 12) with range check
T & at (const IVector< N > &_index)
returns array element (arbitrary N) with range check
TSubArray< T, N > subarray (const IVector< N > &lbound, const IVector< N > &ubound) const
slice array to return sub-array object
const T * data () const
returns the first pointer of array elements
T * data ()
returns the first pointer of array elements
void fill (const T &val)
fills elements by constant value
void operator= (const T &val)
fills elements by constant value
template<class Generator >
void generate (Generator gen)
generates array elements by function gen
void clear ()
deallocate storage
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Enables to use boost serialization.
Private Attributes
IVector< N > m_shape
array shape
IVector< N > m_stride
array stride
shared_ptr< std::vector< T > > m_store
array storage
Friends
class boost::serialization::access
template<typename U , size_t M>
class TSubArray
Any TSubArray classes being friend of TArray<T, N>
Detailed Description
template<typename T, size_t N>
class btas::TArray< T, N >
Dense array class.
Fixed-rank array class implemented in terms of std::array and std::vector Since using C++11 features, not compatible for C++03 compiler
Parameters
T value type
N array rank
Definition at line 22 of file TArray.h.
Member Typedef Documentation
template<typename T, size_t N> typedef std::vector<T>::const_iterator btas::TArray< T, N >::const_iterator
TArray<T, N>::const_iterator.
Definition at line 61 of file TArray.h.
template<typename T, size_t N> typedef std::vector<T>::iterator btas::TArray< T, N >::iterator
TArray<T, N>::iterator.
Definition at line 58 of file TArray.h.
Constructor & Destructor Documentation
template<typename T, size_t N> btas::TArray< T, N >::TArray () inline
default constructor
Definition at line 72 of file TArray.h.
References btas::TArray< T, N >::m_shape, and btas::TArray< T, N >::m_stride.
template<typename T, size_t N> btas::TArray< T, N >::~TArray () inline
destructor
Definition at line 78 of file TArray.h.
template<typename T, size_t N> btas::TArray< T, N >::TArray (const TArray< T, N > & other) inline explicit
copy constructor
Definition at line 81 of file TArray.h.
References btas::TArray< T, N >::copy().
template<typename T, size_t N> template<size_t M> btas::TArray< T, N >::TArray (const TSubArray< T, M > & sub) inline explicit
copy constructor from sub-array
Definition at line 154 of file TArray.h.
References btas::TArray< T, N >::copy().
template<typename T, size_t N> btas::TArray< T, N >::TArray (TArray< T, N > && other) inline explicit
move constructor
Definition at line 166 of file TArray.h.
template<typename T, size_t N> btas::TArray< T, N >::TArray (int n01) inline explicit
convenient constructor with array shape, for N = 1
Definition at line 192 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> btas::TArray< T, N >::TArray (int n01, int n02) inline
convenient constructor with array shape, for N = 2
Definition at line 197 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> btas::TArray< T, N >::TArray (int n01, int n02, int n03) inline
convenient constructor with array shape, for N = 3
Definition at line 202 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> btas::TArray< T, N >::TArray (int n01, int n02, int n03, int n04) inline
convenient constructor with array shape, for N = 4
Definition at line 207 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> btas::TArray< T, N >::TArray (int n01, int n02, int n03, int n04, int n05) inline
convenient constructor with array shape, for N = 5
Definition at line 212 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> btas::TArray< T, N >::TArray (int n01, int n02, int n03, int n04, int n05, int n06) inline
convenient constructor with array shape, for N = 6
Definition at line 217 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> btas::TArray< T, N >::TArray (int n01, int n02, int n03, int n04, int n05, int n06, int n07) inline
convenient constructor with array shape, for N = 7
Definition at line 222 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> btas::TArray< T, N >::TArray (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08) inline
convenient constructor with array shape, for N = 8
Definition at line 227 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> btas::TArray< T, N >::TArray (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09) inline
convenient constructor with array shape, for N = 9
Definition at line 232 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> btas::TArray< T, N >::TArray (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10) inline
convenient constructor with array shape, for N = 10
Definition at line 237 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> btas::TArray< T, N >::TArray (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10, int n11) inline
convenient constructor with array shape, for N = 11
Definition at line 242 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> btas::TArray< T, N >::TArray (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10, int n11, int n12) inline
convenient constructor with array shape, for N = 12
Definition at line 247 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> btas::TArray< T, N >::TArray (const IVector< N > & _shape) inline
convenient constructor with array shape, for arbitrary N
Definition at line 252 of file TArray.h.
References btas::TArray< T, N >::resize().
Member Function Documentation
template<typename T, size_t N> void btas::TArray< T, N >::add (const TArray< T, N > & other) inline
adding from other to this
Definition at line 146 of file TArray.h.
References btas::fast_add(), btas::TArray< T, N >::m_shape, btas::TArray< T, N >::m_store, and btas::TArray< T, N >::m_stride.
Referenced by btas::TArray< T, N >::operator+=().
template<typename T, size_t N> const T& btas::TArray< T, N >::at (int i01) const inline
returns array element (N = 1) with range check
Definition at line 533 of file TArray.h.
Referenced by btas::TArray< T, N >::at().
template<typename T, size_t N> const T& btas::TArray< T, N >::at (int i01, int i02) const inline
returns array element (N = 2) with range check
Definition at line 539 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> const T& btas::TArray< T, N >::at (int i01, int i02, int i03) const inline
returns array element (N = 3) with range check
Definition at line 545 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> const T& btas::TArray< T, N >::at (int i01, int i02, int i03, int i04) const inline
returns array element (N = 4) with range check
Definition at line 551 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> const T& btas::TArray< T, N >::at (int i01, int i02, int i03, int i04, int i05) const inline
returns array element (N = 5) with range check
Definition at line 557 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> const T& btas::TArray< T, N >::at (int i01, int i02, int i03, int i04, int i05, int i06) const inline
returns array element (N = 6) with range check
Definition at line 563 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> const T& btas::TArray< T, N >::at (int i01, int i02, int i03, int i04, int i05, int i06, int i07) const inline
returns array element (N = 7) with range check
Definition at line 569 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> const T& btas::TArray< T, N >::at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08) const inline
returns array element (N = 8) with range check
Definition at line 575 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> const T& btas::TArray< T, N >::at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09) const inline
returns array element (N = 9) with range check
Definition at line 581 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> const T& btas::TArray< T, N >::at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10) const inline
returns array element (N = 10) with range check
Definition at line 587 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> const T& btas::TArray< T, N >::at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11) const inline
returns array element (N = 11) with range check
Definition at line 593 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> const T& btas::TArray< T, N >::at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11, int i12) const inline
returns array element (N = 12) with range check
Definition at line 599 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> const T& btas::TArray< T, N >::at (const IVector< N > & _index) const inline
returns array element (arbitrary N) with range check
Definition at line 605 of file TArray.h.
References btas::dot(), btas::TArray< T, N >::m_store, and btas::TArray< T, N >::m_stride.
template<typename T, size_t N> T& btas::TArray< T, N >::at (int i01) inline
returns array element (N = 1) with range check
Definition at line 610 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> T& btas::TArray< T, N >::at (int i01, int i02) inline
returns array element (N = 2) with range check
Definition at line 616 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> T& btas::TArray< T, N >::at (int i01, int i02, int i03) inline
returns array element (N = 3) with range check
Definition at line 622 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> T& btas::TArray< T, N >::at (int i01, int i02, int i03, int i04) inline
returns array element (N = 4) with range check
Definition at line 628 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> T& btas::TArray< T, N >::at (int i01, int i02, int i03, int i04, int i05) inline
returns array element (N = 5) with range check
Definition at line 634 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> T& btas::TArray< T, N >::at (int i01, int i02, int i03, int i04, int i05, int i06) inline
returns array element (N = 6) with range check
Definition at line 640 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> T& btas::TArray< T, N >::at (int i01, int i02, int i03, int i04, int i05, int i06, int i07) inline
returns array element (N = 7) with range check
Definition at line 646 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> T& btas::TArray< T, N >::at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08) inline
returns array element (N = 8) with range check
Definition at line 652 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> T& btas::TArray< T, N >::at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09) inline
returns array element (N = 9) with range check
Definition at line 658 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> T& btas::TArray< T, N >::at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10) inline
returns array element (N = 10) with range check
Definition at line 664 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> T& btas::TArray< T, N >::at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11) inline
returns array element (N = 11) with range check
Definition at line 670 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> T& btas::TArray< T, N >::at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11, int i12) inline
returns array element (N = 12) with range check
Definition at line 676 of file TArray.h.
References btas::TArray< T, N >::at().
template<typename T, size_t N> T& btas::TArray< T, N >::at (const IVector< N > & _index) inline
returns array element (arbitrary N) with range check
Definition at line 682 of file TArray.h.
References btas::dot(), btas::TArray< T, N >::m_store, and btas::TArray< T, N >::m_stride.
template<typename T, size_t N> const_iterator btas::TArray< T, N >::begin () const inline
returns first iterator position (const)
Definition at line 352 of file TArray.h.
References btas::TArray< T, N >::m_store.
template<typename T, size_t N> iterator btas::TArray< T, N >::begin () inline
returns first iterator position
Definition at line 355 of file TArray.h.
References btas::TArray< T, N >::m_store.
template<typename T, size_t N> void btas::TArray< T, N >::clear () inline
deallocate storage
Definition at line 718 of file TArray.h.
References btas::TArray< T, N >::m_shape, btas::TArray< T, N >::m_store, and btas::TArray< T, N >::m_stride.
Referenced by btas::Dcopy().
template<typename T, size_t N> void btas::TArray< T, N >::copy (const TArray< T, N > & other) inline
copying from other to this
Definition at line 98 of file TArray.h.
References btas::fast_copy(), btas::TArray< T, N >::m_shape, btas::TArray< T, N >::m_store, and btas::TArray< T, N >::m_stride.
Referenced by btas::TArray< T, N >::copy().
template<typename T, size_t N> TArray btas::TArray< T, N >::copy () const inline
return copy of this
Definition at line 105 of file TArray.h.
References btas::TArray< T, N >::copy().
Referenced by btas::TSubArray< T, N >::operator=(), btas::TArray< T, N >::operator=(), and btas::TArray< T, N >::TArray().
template<typename T, size_t N> template<size_t M> void btas::TArray< T, N >::copy (const TSubArray< T, M > & a) inline
Copy from sub-array to array.
Definition at line 113 of file TArray.h.
References btas::_fast_copy(), btas::TArray< T, N >::data(), btas::dot(), btas::TSubArray< T, N >::m_lower_bound, btas::TArray< T, N >::m_store, btas::TSubArray< T, N >::m_upper_bound, and btas::TArray< T, N >::stride().
template<typename T, size_t N> const T* btas::TArray< T, N >::data () const inline
returns the first pointer of array elements
Definition at line 693 of file TArray.h.
References btas::TArray< T, N >::m_store.
Referenced by btas::TSubArray< T, N >::copy(), btas::TArray< T, N >::copy(), btas::Daxpy(), btas::Dcopy(), btas::DcopyFlatten(), btas::Ddiagonal(), btas::Ddidm(), btas::Ddimd(), btas::Ddot(), btas::Dgeev(), btas::Dgemm(), btas::Dgemv(), btas::Dger(), btas::Dgesv(), btas::Dgesvd(), btas::Dgetrf(), btas::Dggev(), btas::Dnrm2(), btas::Dpermute(), btas::Dscal(), btas::Dsyev(), and btas::Dsygv().
template<typename T, size_t N> T* btas::TArray< T, N >::data () inline
returns the first pointer of array elements
Definition at line 696 of file TArray.h.
References btas::TArray< T, N >::m_store.
template<typename T, size_t N> const_iterator btas::TArray< T, N >::end () const inline
returns last iterator position (const)
Definition at line 358 of file TArray.h.
References btas::TArray< T, N >::m_store.
Referenced by btas::QSDgesvd().
template<typename T, size_t N> iterator btas::TArray< T, N >::end () inline
returns last iterator position
Definition at line 361 of file TArray.h.
References btas::TArray< T, N >::m_store.
template<typename T, size_t N> void btas::TArray< T, N >::fill (const T & val) inline
fills elements by constant value
Definition at line 699 of file TArray.h.
References btas::TArray< T, N >::m_store.
Referenced by btas::TArray< T, N >::operator=(), and btas::QSTmerge().
template<typename T, size_t N> template<class Generator > void btas::TArray< T, N >::generate (Generator gen) inline
generates array elements by function gen
Generator is either default constructible class or function pointer, which can be called by gen()
Definition at line 709 of file TArray.h.
References btas::TArray< T, N >::m_store.
Referenced by DENSE_TEST().
template<typename T, size_t N> const T& btas::TArray< T, N >::operator() (int i01) const inline
returns array element (N = 1) without range check
Definition at line 379 of file TArray.h.
Referenced by btas::TArray< T, N >::operator()().
template<typename T, size_t N> const T& btas::TArray< T, N >::operator() (int i01, int i02) const inline
returns array element (N = 2) without range check
Definition at line 385 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> const T& btas::TArray< T, N >::operator() (int i01, int i02, int i03) const inline
returns array element (N = 3) without range check
Definition at line 391 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> const T& btas::TArray< T, N >::operator() (int i01, int i02, int i03, int i04) const inline
returns array element (N = 4) without range check
Definition at line 397 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> const T& btas::TArray< T, N >::operator() (int i01, int i02, int i03, int i04, int i05) const inline
returns array element (N = 5) without range check
Definition at line 403 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> const T& btas::TArray< T, N >::operator() (int i01, int i02, int i03, int i04, int i05, int i06) const inline
returns array element (N = 6) without range check
Definition at line 409 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> const T& btas::TArray< T, N >::operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07) const inline
returns array element (N = 7) without range check
Definition at line 415 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> const T& btas::TArray< T, N >::operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08) const inline
returns array element (N = 8) without range check
Definition at line 421 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> const T& btas::TArray< T, N >::operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09) const inline
returns array element (N = 9) without range check
Definition at line 427 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> const T& btas::TArray< T, N >::operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10) const inline
returns array element (N = 10) without range check
Definition at line 433 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> const T& btas::TArray< T, N >::operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11) const inline
returns array element (N = 11) without range check
Definition at line 439 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> const T& btas::TArray< T, N >::operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11, int i12) const inline
returns array element (N = 12) without range check
Definition at line 445 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> const T& btas::TArray< T, N >::operator() (const IVector< N > & _index) const inline
returns array element (arbitrary N) without range check
Definition at line 451 of file TArray.h.
References btas::dot(), btas::TArray< T, N >::m_store, and btas::TArray< T, N >::m_stride.
template<typename T, size_t N> T& btas::TArray< T, N >::operator() (int i01) inline
returns array element (N = 1) without range check
Definition at line 456 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> T& btas::TArray< T, N >::operator() (int i01, int i02) inline
returns array element (N = 2) without range check
Definition at line 462 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> T& btas::TArray< T, N >::operator() (int i01, int i02, int i03) inline
returns array element (N = 3) without range check
Definition at line 468 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> T& btas::TArray< T, N >::operator() (int i01, int i02, int i03, int i04) inline
returns array element (N = 4) without range check
Definition at line 474 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> T& btas::TArray< T, N >::operator() (int i01, int i02, int i03, int i04, int i05) inline
returns array element (N = 5) without range check
Definition at line 480 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> T& btas::TArray< T, N >::operator() (int i01, int i02, int i03, int i04, int i05, int i06) inline
returns array element (N = 6) without range check
Definition at line 486 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> T& btas::TArray< T, N >::operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07) inline
returns array element (N = 7) without range check
Definition at line 492 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> T& btas::TArray< T, N >::operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08) inline
returns array element (N = 8) without range check
Definition at line 498 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> T& btas::TArray< T, N >::operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09) inline
returns array element (N = 9) without range check
Definition at line 504 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> T& btas::TArray< T, N >::operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10) inline
returns array element (N = 10) without range check
Definition at line 510 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> T& btas::TArray< T, N >::operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11) inline
returns array element (N = 11) without range check
Definition at line 516 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> T& btas::TArray< T, N >::operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11, int i12) inline
returns array element (N = 12) without range check
Definition at line 522 of file TArray.h.
References btas::TArray< T, N >::operator()().
template<typename T, size_t N> T& btas::TArray< T, N >::operator() (const IVector< N > & _index) inline
returns array element (arbitrary N) without range check
Definition at line 528 of file TArray.h.
References btas::dot(), btas::TArray< T, N >::m_store, and btas::TArray< T, N >::m_stride.
template<typename T, size_t N> TArray& btas::TArray< T, N >::operator+= (const TArray< T, N > & other) inline
addition assignment operator
Definition at line 92 of file TArray.h.
References btas::TArray< T, N >::add().
template<typename T, size_t N> TArray& btas::TArray< T, N >::operator= (const TArray< T, N > & other) inline
copy assignment operator
Definition at line 86 of file TArray.h.
References btas::TArray< T, N >::copy().
template<typename T, size_t N> template<size_t M> TArray& btas::TArray< T, N >::operator= (const TSubArray< T, M > & sub) inline
copy assignment from sub-array
Definition at line 160 of file TArray.h.
References btas::TArray< T, N >::copy().
template<typename T, size_t N> TArray& btas::TArray< T, N >::operator= (TArray< T, N > && other) inline
move assignment
Definition at line 170 of file TArray.h.
References btas::TArray< T, N >::m_shape, btas::TArray< T, N >::m_store, and btas::TArray< T, N >::m_stride.
template<typename T, size_t N> void btas::TArray< T, N >::operator= (const T & val) inline
fills elements by constant value
Definition at line 704 of file TArray.h.
References btas::TArray< T, N >::fill().
template<typename T, size_t N> void btas::TArray< T, N >::reference (const TArray< T, N > & other) inline
take data reference from other
Definition at line 178 of file TArray.h.
References btas::TArray< T, N >::m_shape, btas::TArray< T, N >::m_store, and btas::TArray< T, N >::m_stride.
Referenced by btas::Dcontract(), and btas::TArray< T, N >::reference().
template<typename T, size_t N> TArray btas::TArray< T, N >::reference () const inline
return data reference of this
Definition at line 185 of file TArray.h.
References btas::TArray< T, N >::reference().
Referenced by btas::TSubArray< T, N >::TSubArray().
template<typename T, size_t N> void btas::TArray< T, N >::resize (int n01) inline
resize array shape, for N = 1
Definition at line 261 of file TArray.h.
Referenced by btas::_lsv_truncate(), btas::_rsv_truncate(), btas::Daxpy(), btas::Dcopy(), btas::Ddiagonal(), btas::Dgeev(), btas::Dgemm(), btas::Dgemv(), btas::Dger(), btas::Dgesvd(), btas::Dgetrf(), btas::Dggev(), btas::Dpermute(), btas::Dreshape(), btas::Dsyev(), btas::Dsygv(), btas::TArray< T, N >::resize(), and btas::TArray< T, N >::TArray().
template<typename T, size_t N> void btas::TArray< T, N >::resize (int n01, int n02) inline
resize array shape, for N = 2
Definition at line 267 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> void btas::TArray< T, N >::resize (int n01, int n02, int n03) inline
resize array shape, for N = 3
Definition at line 273 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> void btas::TArray< T, N >::resize (int n01, int n02, int n03, int n04) inline
resize array shape, for N = 4
Definition at line 279 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> void btas::TArray< T, N >::resize (int n01, int n02, int n03, int n04, int n05) inline
resize array shape, for N = 5
Definition at line 285 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> void btas::TArray< T, N >::resize (int n01, int n02, int n03, int n04, int n05, int n06) inline
resize array shape, for N = 6
Definition at line 291 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> void btas::TArray< T, N >::resize (int n01, int n02, int n03, int n04, int n05, int n06, int n07) inline
resize array shape, for N = 7
Definition at line 297 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> void btas::TArray< T, N >::resize (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08) inline
resize array shape, for N = 8
Definition at line 303 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> void btas::TArray< T, N >::resize (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09) inline
resize array shape, for N = 9
Definition at line 309 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> void btas::TArray< T, N >::resize (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10) inline
resize array shape, for N = 10
Definition at line 315 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> void btas::TArray< T, N >::resize (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10, int n11) inline
resize array shape, for N = 11
Definition at line 321 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> void btas::TArray< T, N >::resize (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10, int n11, int n12) inline
resize array shape, for N = 12
Definition at line 327 of file TArray.h.
References btas::TArray< T, N >::resize().
template<typename T, size_t N> void btas::TArray< T, N >::resize (const IVector< N > & _shape) inline
resize array by _shape, for arbitrary N
detects rank-mismatching error at compilation time
Definition at line 334 of file TArray.h.
References btas::TArray< T, N >::m_shape, btas::TArray< T, N >::m_store, btas::TArray< T, N >::m_stride, and btas::TArray< T, N >::stride().
template<typename T, size_t N> void btas::TArray< T, N >::scale (const T & alpha) inline
scale by const value
Definition at line 141 of file TArray.h.
References btas::fast_scal(), and btas::TArray< T, N >::m_store.
template<typename T, size_t N> template<class Archive > void btas::TArray< T, N >::serialize (Archive & ar, const unsigned int version) inline private
Enables to use boost serialization.
Definition at line 53 of file TArray.h.
References btas::TArray< T, N >::m_shape, btas::TArray< T, N >::m_store, and btas::TArray< T, N >::m_stride.
template<typename T, size_t N> const IVector<N>& btas::TArray< T, N >::shape () const inline
returns array shape
Definition at line 364 of file TArray.h.
References btas::TArray< T, N >::m_shape.
Referenced by btas::_lsv_truncate(), btas::_rsv_truncate(), btas::Daxpy(), btas::Dcontract(), btas::Dcopy(), btas::Ddiagonal(), btas::Ddidm(), btas::Ddimd(), btas::Ddot(), btas::Dgeev(), btas::Dgemm(), btas::Dgemv(), btas::Dger(), btas::Dgesv(), btas::Dgesvd(), btas::Dgetrf(), btas::Dggev(), btas::Dpermute(), btas::Dsyev(), btas::Dsygv(), btas::STArray< T, N >::insert(), and btas::QSTexpand().
template<typename T, size_t N> int btas::TArray< T, N >::shape (int i) const inline
returns array shape for rank i
Definition at line 367 of file TArray.h.
References btas::TArray< T, N >::m_shape.
template<typename T, size_t N> size_t btas::TArray< T, N >::size () const inline
returns allocated size
Definition at line 376 of file TArray.h.
References btas::TArray< T, N >::m_store.
Referenced by btas::TSubArray< T, N >::copy(), btas::Daxpy(), btas::Dcopy(), btas::DcopyFlatten(), btas::Ddiagonal(), btas::Ddidm(), btas::Ddimd(), btas::Ddot(), btas::decompose(), btas::Dgeev(), btas::Dgemm(), btas::Dgemv(), btas::Dger(), btas::Dgesv(), btas::Dgesvd(), btas::Dggev(), btas::Dindexed_contract(), btas::Dnrm2(), btas::Dpermute(), btas::Dscal(), btas::Dsyev(), btas::Dsygv(), and btas::indexed_decompose().
template<typename T, size_t N> const IVector<N>& btas::TArray< T, N >::stride () const inline
returns array stride
Definition at line 370 of file TArray.h.
References btas::TArray< T, N >::m_stride.
Referenced by btas::TArray< T, N >::copy(), btas::Ddiagonal(), and btas::TArray< T, N >::resize().
template<typename T, size_t N> int btas::TArray< T, N >::stride (int i) const inline
returns array stride for rank i
Definition at line 373 of file TArray.h.
References btas::TArray< T, N >::m_stride.
template<typename T, size_t N> TSubArray<T, N> btas::TArray< T, N >::subarray (const IVector< N > & lbound, const IVector< N > & ubound) const inline
slice array to return sub-array object
sub-array is constructed from array elements [lbound[0]:ubound[0], lbound[1]:ubound[1], ...]
Definition at line 688 of file TArray.h.
Referenced by btas::QSTexpand().
Friends And Related Function Documentation
template<typename T, size_t N> friend class boost::serialization::access friend
Definition at line 45 of file TArray.h.
template<typename T, size_t N> template<typename U , size_t M> friend class TSubArray friend
Any TSubArray classes being friend of TArray<T, N>
Definition at line 49 of file TArray.h.
Field Documentation
template<typename T, size_t N> IVector<N> btas::TArray< T, N >::m_shape private
array shape
Definition at line 732 of file TArray.h.
Referenced by btas::TArray< T, N >::add(), btas::TArray< T, N >::clear(), btas::TArray< T, N >::copy(), btas::TArray< T, N >::operator=(), btas::TArray< T, N >::reference(), btas::TArray< T, N >::resize(), btas::TArray< T, N >::serialize(), btas::TArray< T, N >::shape(), and btas::TArray< T, N >::TArray().
template<typename T, size_t N> shared_ptr<std::vector<T> > btas::TArray< T, N >::m_store private
array storage
Definition at line 740 of file TArray.h.
Referenced by btas::TArray< T, N >::add(), btas::TArray< T, N >::at(), btas::TArray< T, N >::begin(), btas::TArray< T, N >::clear(), btas::TArray< T, N >::copy(), btas::TArray< T, N >::data(), btas::TArray< T, N >::end(), btas::TArray< T, N >::fill(), btas::TArray< T, N >::generate(), btas::TArray< T, N >::operator()(), btas::TArray< T, N >::operator=(), btas::TArray< T, N >::reference(), btas::TArray< T, N >::resize(), btas::TArray< T, N >::scale(), btas::TArray< T, N >::serialize(), and btas::TArray< T, N >::size().
template<typename T, size_t N> IVector<N> btas::TArray< T, N >::m_stride private
array stride
Definition at line 736 of file TArray.h.
Referenced by btas::TArray< T, N >::add(), btas::TArray< T, N >::at(), btas::TArray< T, N >::clear(), btas::TSubArray< T, N >::copy(), btas::TArray< T, N >::copy(), btas::TArray< T, N >::operator()(), btas::TArray< T, N >::operator=(), btas::TArray< T, N >::reference(), btas::TArray< T, N >::resize(), btas::TArray< T, N >::serialize(), btas::TArray< T, N >::stride(), and btas::TArray< T, N >::TArray().
The documentation for this class was generated from the following file:
include/btas/DENSE/TArray.h