Basic Tensor Algebra Subprograms (BTAS): btas::TSubArray< T, N > Class Template Reference
btas::TSubArray< T, N > Class Template Reference
Sub-array of dense array TArray.
#include <TArray.h>
Public Member Functions
TSubArray (const TArray< T, N > &a, const IVector< N > &lbound, const IVector< N > &ubound)
Constructor, from dense array object and lower/upper boundary indices.
template<size_t M>
void copy (const TArray< T, M > &a)
Copy from array to sub-array.
template<size_t M>
void operator= (const TArray< T, M > &other)
Copy assignment operator from TArray.
Private Member Functions
TSubArray ()
Not default-constructible.
Private Attributes
IVector< N > m_lower_bound
lower boundary indices
IVector< N > m_upper_bound
upper boundary indices
Friends
template<typename U , size_t M>
class TArray
Any TArray classes being friend of TSubArray<T, N>
Additional Inherited Members
Protected Types inherited from btas::TArray< T, N >
typedef std::vector< T >::iterator iterator
TArray<T, N>::iterator.
typedef std::vector< T >
::const_iterator const_iterator
TArray<T, N>::const_iterator.
Protected Member Functions inherited from btas::TArray< T, N >
TArray ()
default constructor
~TArray ()
destructor
TArray (const TArray &other)
copy constructor
TArray & operator= (const TArray &other)
copy assignment operator
TArray & operator+= (const TArray &other)
addition assignment operator
void copy (const TArray &other)
copying from other to this
TArray copy () const
return copy of this
template<size_t M>
void copy (const TSubArray< T, M > &a)
Copy from sub-array to array.
void scale (const T &alpha)
scale by const value
void add (const TArray &other)
adding from other to this
template<size_t M>
TArray (const TSubArray< T, M > &sub)
copy constructor from sub-array
template<size_t M>
TArray & operator= (const TSubArray< T, M > &sub)
copy assignment from sub-array
TArray (TArray &&other)
move constructor
TArray & operator= (TArray &&other)
move assignment
void reference (const TArray &other)
take data reference from other
TArray reference () const
return data reference of this
TArray (int n01)
convenient constructor with array shape, for N = 1
TArray (int n01, int n02)
convenient constructor with array shape, for N = 2
TArray (int n01, int n02, int n03)
convenient constructor with array shape, for N = 3
TArray (int n01, int n02, int n03, int n04)
convenient constructor with array shape, for N = 4
TArray (int n01, int n02, int n03, int n04, int n05)
convenient constructor with array shape, for N = 5
TArray (int n01, int n02, int n03, int n04, int n05, int n06)
convenient constructor with array shape, for N = 6
TArray (int n01, int n02, int n03, int n04, int n05, int n06, int n07)
convenient constructor with array shape, for N = 7
TArray (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08)
convenient constructor with array shape, for N = 8
TArray (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09)
convenient constructor with array shape, for N = 9
TArray (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10)
convenient constructor with array shape, for N = 10
TArray (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10, int n11)
convenient constructor with array shape, for N = 11
TArray (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10, int n11, int n12)
convenient constructor with array shape, for N = 12
TArray (const IVector< N > &_shape)
convenient constructor with array shape, for arbitrary N
void resize (int n01)
resize array shape, for N = 1
void resize (int n01, int n02)
resize array shape, for N = 2
void resize (int n01, int n02, int n03)
resize array shape, for N = 3
void resize (int n01, int n02, int n03, int n04)
resize array shape, for N = 4
void resize (int n01, int n02, int n03, int n04, int n05)
resize array shape, for N = 5
void resize (int n01, int n02, int n03, int n04, int n05, int n06)
resize array shape, for N = 6
void resize (int n01, int n02, int n03, int n04, int n05, int n06, int n07)
resize array shape, for N = 7
void resize (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08)
resize array shape, for N = 8
void resize (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09)
resize array shape, for N = 9
void resize (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10)
resize array shape, for N = 10
void resize (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10, int n11)
resize array shape, for N = 11
void resize (int n01, int n02, int n03, int n04, int n05, int n06, int n07, int n08, int n09, int n10, int n11, int n12)
resize array shape, for N = 12
void resize (const IVector< N > &_shape)
resize array by _shape, for arbitrary N
const_iterator begin () const
returns first iterator position (const)
iterator begin ()
returns first iterator position
const_iterator end () const
returns last iterator position (const)
iterator end ()
returns last iterator position
const IVector< N > & shape () const
returns array shape
int shape (int i) const
returns array shape for rank i
const IVector< N > & stride () const
returns array stride
int stride (int i) const
returns array stride for rank i
size_t size () const
returns allocated size
const T & operator() (int i01) const
returns array element (N = 1) without range check
const T & operator() (int i01, int i02) const
returns array element (N = 2) without range check
const T & operator() (int i01, int i02, int i03) const
returns array element (N = 3) without range check
const T & operator() (int i01, int i02, int i03, int i04) const
returns array element (N = 4) without range check
const T & operator() (int i01, int i02, int i03, int i04, int i05) const
returns array element (N = 5) without range check
const T & operator() (int i01, int i02, int i03, int i04, int i05, int i06) const
returns array element (N = 6) without range check
const T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07) const
returns array element (N = 7) without range check
const T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08) const
returns array element (N = 8) without range check
const T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09) const
returns array element (N = 9) without range check
const T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10) const
returns array element (N = 10) without range check
const T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11) const
returns array element (N = 11) without range check
const T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11, int i12) const
returns array element (N = 12) without range check
const T & operator() (const IVector< N > &_index) const
returns array element (arbitrary N) without range check
T & operator() (int i01)
returns array element (N = 1) without range check
T & operator() (int i01, int i02)
returns array element (N = 2) without range check
T & operator() (int i01, int i02, int i03)
returns array element (N = 3) without range check
T & operator() (int i01, int i02, int i03, int i04)
returns array element (N = 4) without range check
T & operator() (int i01, int i02, int i03, int i04, int i05)
returns array element (N = 5) without range check
T & operator() (int i01, int i02, int i03, int i04, int i05, int i06)
returns array element (N = 6) without range check
T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07)
returns array element (N = 7) without range check
T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08)
returns array element (N = 8) without range check
T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09)
returns array element (N = 9) without range check
T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10)
returns array element (N = 10) without range check
T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11)
returns array element (N = 11) without range check
T & operator() (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11, int i12)
returns array element (N = 12) without range check
T & operator() (const IVector< N > &_index)
returns array element (arbitrary N) without range check
const T & at (int i01) const
returns array element (N = 1) with range check
const T & at (int i01, int i02) const
returns array element (N = 2) with range check
const T & at (int i01, int i02, int i03) const
returns array element (N = 3) with range check
const T & at (int i01, int i02, int i03, int i04) const
returns array element (N = 4) with range check
const T & at (int i01, int i02, int i03, int i04, int i05) const
returns array element (N = 5) with range check
const T & at (int i01, int i02, int i03, int i04, int i05, int i06) const
returns array element (N = 6) with range check
const T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07) const
returns array element (N = 7) with range check
const T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08) const
returns array element (N = 8) with range check
const T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09) const
returns array element (N = 9) with range check
const T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10) const
returns array element (N = 10) with range check
const T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11) const
returns array element (N = 11) with range check
const T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11, int i12) const
returns array element (N = 12) with range check
const T & at (const IVector< N > &_index) const
returns array element (arbitrary N) with range check
T & at (int i01)
returns array element (N = 1) with range check
T & at (int i01, int i02)
returns array element (N = 2) with range check
T & at (int i01, int i02, int i03)
returns array element (N = 3) with range check
T & at (int i01, int i02, int i03, int i04)
returns array element (N = 4) with range check
T & at (int i01, int i02, int i03, int i04, int i05)
returns array element (N = 5) with range check
T & at (int i01, int i02, int i03, int i04, int i05, int i06)
returns array element (N = 6) with range check
T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07)
returns array element (N = 7) with range check
T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08)
returns array element (N = 8) with range check
T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09)
returns array element (N = 9) with range check
T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10)
returns array element (N = 10) with range check
T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11)
returns array element (N = 11) with range check
T & at (int i01, int i02, int i03, int i04, int i05, int i06, int i07, int i08, int i09, int i10, int i11, int i12)
returns array element (N = 12) with range check
T & at (const IVector< N > &_index)
returns array element (arbitrary N) with range check
TSubArray< T, N > subarray (const IVector< N > &lbound, const IVector< N > &ubound) const
slice array to return sub-array object
const T * data () const
returns the first pointer of array elements
T * data ()
returns the first pointer of array elements
void fill (const T &val)
fills elements by constant value
void operator= (const T &val)
fills elements by constant value
template<class Generator >
void generate (Generator gen)
generates array elements by function gen
void clear ()
deallocate storage
Detailed Description
template<typename T, size_t N>
class btas::TSubArray< T, N >
Sub-array of dense array TArray.
Expression template providing copy semantics between TArray and TSubArray
Parameters
T value type
N array rank
Definition at line 23 of file TArray.h.
Constructor & Destructor Documentation
template<typename T, size_t N> btas::TSubArray< T, N >::TSubArray () private
Not default-constructible.
template<typename T, size_t N> btas::TSubArray< T, N >::TSubArray (const TArray< T, N > & a, const IVector< N > & lbound, const IVector< N > & ubound) inline
Constructor, from dense array object and lower/upper boundary indices.
Definition at line 39 of file TSubArray.h.
References btas::TSubArray< T, N >::m_lower_bound, btas::TSubArray< T, N >::m_upper_bound, and btas::TArray< T, N >::reference().
Member Function Documentation
template<typename T, size_t N> template<size_t M> void btas::TSubArray< T, N >::copy (const TArray< T, M > & a) inline
Copy from array to sub-array.
Definition at line 47 of file TSubArray.h.
References btas::_fast_copy(), btas::TArray< T, N >::data(), btas::dot(), btas::TSubArray< T, N >::m_lower_bound, btas::TArray< T, N >::m_stride, btas::TSubArray< T, N >::m_upper_bound, and btas::TArray< T, N >::size().
template<typename T, size_t N> template<size_t M> void btas::TSubArray< T, N >::operator= (const TArray< T, M > & other) inline
Copy assignment operator from TArray.
Definition at line 76 of file TSubArray.h.
References btas::TArray< T, N >::copy().
Friends And Related Function Documentation
template<typename T, size_t N> template<typename U , size_t M> friend class TArray friend
Any TArray classes being friend of TSubArray<T, N>
Definition at line 31 of file TSubArray.h.
Field Documentation
template<typename T, size_t N> IVector<N> btas::TSubArray< T, N >::m_lower_bound private
lower boundary indices
Definition at line 81 of file TSubArray.h.
Referenced by btas::TSubArray< T, N >::copy(), btas::TArray< T, N >::copy(), and btas::TSubArray< T, N >::TSubArray().
template<typename T, size_t N> IVector<N> btas::TSubArray< T, N >::m_upper_bound private
upper boundary indices
Definition at line 84 of file TSubArray.h.
Referenced by btas::TSubArray< T, N >::copy(), btas::TArray< T, N >::copy(), and btas::TSubArray< T, N >::TSubArray().
The documentation for this class was generated from the following files:
include/btas/DENSE/TArray.h
include/btas/DENSE/TSubArray.h